### ISSUE TITLE
Contains Filter not available

### ISSUE THREAD

**Issue by fvisticot** [tekartik/sembast.dart#10]
The db is containing model with firstName, lastName.
I need to query by firstName containing a pattern

**Comment by alextekartik** [comment]
There is not convenient way to do that yet but I could easily add a way to query using a RegExp or glob pattern (I like glob as I can easily read it but it is more file name oriented and RegExp seems more powerful)

**Comment by Benoss** [comment]
I would love one or the other, my use case it for implementing startsWith(string), can already do it by doing lessThan and greaterThan but a bit inefficient .

**Comment by alextekartik** [comment]
I have added reg exp pattern matching using `Filter.matches`. It can be used to perform filters like `contains`, `startsWith`, `endsWith` and of course many more assuming you speak regular expression fluently (which is not my case).

Some docs here: <https://github.com/tekartik/sembast.dart/blob/master/doc/queries.md#filtering-using-regexp-patten>

Published in 1.12.0
