### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by lcuis** [tekartik/sembast.dart#101]
Thank you very much for sembast, it is really useful to me!

I was trying to find a way to make the sembast database files smaller on the mobile devices. I looked into the [codec approach](https://github.com/tekartik/sembast.dart/blob/master/sembast/test/encrypt_codec.dart) with compression in mind. The issue there for me is that the input strings received by the codec are too small for a standard compression using the gz, bz, zlib compressors from the [archive Flutter plugin](https://pub.dev/packages/archive) to lead to a smaller db file size.

Here is how I changed the referred code:
```
//based on https://github.com/tekartik/sembast.dart/blob/master/sembast/test/encrypt_codec.dart

SembastCodec getEncryptSembastCodec({@required String password}) =>
      SembastCodec(
          signature: _encryptCodecSignature,
          codec: _CEncryptCodec(_cGenerateEncryptPassword(password)));

var _cRandom = Random.secure();

Uint8List _cRandBytes(int length) {
  return Uint8List.fromList(
      List<int>.generate(length, (i) => _cRandom.nextInt(256)));
}

Uint8List _cGenerateEncryptPassword(String password) {
  var blob = Uint8List.fromList(md5.convert(utf8.encode(password)).bytes);
  assert(blob.length == 16);
  return blob;
}

class _CEncryptEncoder extends Converter<Map<String, dynamic>, String> {
  final Salsa20 salsa20;
  ZLibEncoder zEnc=ZLibEncoder();

  _CEncryptEncoder(this.salsa20);

  @override
  String convert(Map<String, dynamic> input) {
    Uint8List iv = _cRandBytes(8);
    String ivEncoded = base64.encode(iv);
    assert(ivEncoded.length == 12);
    if(_cRandom.nextInt(256)==1)
    print("input: ${jsonEncode(input).toString()}");
    String encoded =
        base64Encode(zEnc.encode(Encrypter(salsa20).encrypt(json.encode(input), iv: IV(iv)).bytes,level:9));
    return '$ivEncoded$encoded';
  }
}

class _CEncryptDecoder extends Converter<String, Map<String, dynamic>> {
  final Salsa20 salsa20;
  ZLibDecoder zDec=ZLibDecoder();

  _CEncryptDecoder(this.salsa20);

  @override
  Map<String, dynamic> convert(String input) {
    assert(input.length >= 12);
    Uint8List iv = base64.decode(input.substring(0, 12));
    input = input.substring(12);
    var decoded = json.decode(Encrypter(salsa20).decrypt16(zDec.decodeBytes(base64Decode(input)).toString(), iv: IV(iv)));
    if (decoded is Map) {
      return decoded.cast<String, dynamic>();
    }
    throw FormatException('invalid input $input');
  }
}

class _CEncryptCodec extends Codec<Map<String, dynamic>, String> {
  _CEncryptEncoder _encoder;
  _CEncryptDecoder _decoder;

  _CEncryptCodec(Uint8List passwordBytes) {
    var salsa20 = Salsa20(Key(passwordBytes));
    _encoder = _CEncryptEncoder(salsa20);
    _decoder = _CEncryptDecoder(salsa20);
  }

  @override
  Converter<String, Map<String, dynamic>> get decoder => _decoder;

  @override
  Converter<Map<String, dynamic>, String> get encoder => _encoder;
}
```
My attempts with some 1000 strings containing each more than 4000 characters show that none of the encoders I tried (gz - level 9, bz2, zlib - level 9) lead to a smaller file size while the operations are slower.

I don't wish to compress and decompress the file at the app start/stop because there is no way to make sure a clean exit can happen and I would like to save space even when the app is running.

Would there be a way to use some kind of compression/decompression pipe at the file write/read level or any better way to make the sembast db files smaller?

**Comment by alextekartik** [comment]
Indeed the codec approach has big limitation (each encoded data must end up as a single line string) which makes it hard to optimize. The append only approach without any schema has big redundancies too. Small file was not a goal of sembast. Since everything is loaded into memory, files can never be too big anyway.

**Comment by lcuis** [comment]
Thank you very much @alextekartik for your answer. I understand.
