### ISSUE TITLE
notifier 1.0.2 is incompatible with sembast >=1.14.0.

### ISSUE THREAD

**Issue by RIddhiIroid** [tekartik/sembast.dart#102]
Full error is here, I'm using the latest version for notifier and sembast.

Because notifier 1.0.2 depends on synchronized ^1.5.3+2 and sembast >=1.14.0 depends on synchronized >=2.1.0 <4.0.0, notifier 1.0.2 is incompatible with sembast >=1.14.0.
So, because ke_employee depends on both sembast 1.17.0 and notifier 1.0.2, version solving failed.

if I'm using version 1.9.0 for sembast, error will be one
but `intMapStoreFactory` is undefined is showing

**Comment by alextekartik** [comment]
The easiest would be to have notifier update its dependency. Otherwise you can try using dependency_overrides in your project
