### ISSUE TITLE
add key and value to existing store not working

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#105]
how to add a new key and value to an existing store.

I have this store with data in there already
final _user = intMapStoreFactory.store('user');
with data like this [{id: 788, username: mmt, firstname: john, lastname: doe, email: jd@mail.com, phone_number: +22220000000}]

and am try to add this key to the existing data set using
await _user.add(await db, {"user_image": "imageData"})

but it's not working.
what am I doing wrong

**Comment by alextekartik** [comment]
you must know the key your are updating (key might not be the id field) and do

```dart
await _user.record(key).update(db, {"user_image": "imageData"});
```

More info here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#using-auto-generated-int-key

**Comment by MichaelSowah** [comment]
I am not updating I want to add to the store

**Comment by alextekartik** [comment]
```
await _user.add(db, {"user_image": "imageData"});
```
More info here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#using-auto-generated-int-key

Can you write a unit test showing what is not working?

**Comment by MichaelSowah** [comment]
when I run this await _user.add(await db, {"user_image": "imageData"}), it returns me an int after its done which should me its done and successful right? 
but when I fetch from the final _user = intMapStoreFactory.store('user'); it returns null for the value

**Comment by alextekartik** [comment]
Have you looked at the link I sent twice?

```dart
// Use the main store for storing map data with an auto-generated
// int key
var store = intMapStoreFactory.store();

// Add the data and get its new generated key
var key = await store.add(db, {'value': 'test'});

// Retrieve the record
var record = store.record(key);
var readMap = await record.get(db);
```

Each store has multiple record that you can access by key.

**Comment by MichaelSowah** [comment]
ok so I have this record in the store
{
    "token": "",
    "id":"",
    "username" : "",
    "phonenumber" :"",
    "first_name": "",
    "last_name": "",
    "full_name": "",
    "email":"",
    "location": "",
    "userImageBytesData": "",
}

and I want to update this in "userImageBytesData": "",  from the record.
and this is on a different page from the  the place the save was done.

**Comment by MichaelSowah** [comment]
Thanks, I figured it out
