### ISSUE TITLE
Get store names list

### ISSUE THREAD

**Issue by mariomka** [tekartik/sembast.dart#107]
Hi!

Is there any way to get the store names list (A list of used stores)?

For example:
```
['settings', 'user']
```

Thank you!

**Comment by alextekartik** [comment]
Unfortunately that's not possible. A store only "exists" when it contains records but deleting all records does not really delete a store. You could maintain a list of store names in a singleton for example.

**Comment by mariomka** [comment]
Ok, thank you!
