### ISSUE TITLE
Doesn't work in Singleton

### ISSUE THREAD

**Issue by BobbyKitten** [tekartik/sembast.dart#11]
Hello, then I'm trying to do something like this:
```dart
class NotesHelper {
   final NotesHelper _instance;
   Database _db;

   Future<NotesHelper> instance() async {
      if (_instance == null) {
         _instance = NotesHelper();
         _instance._db = await databaseFactoryIo.openDatabase(dbPath);
       }
       return _instance;
    }
}
```
Instance is created, but _db is always null and database doesn't create. There is no errors in log. I tried to move Database opening to another method and call it in instance, but no luck.
And if I am trying to make Database static, then it couldn't be opened too.
Could you help?

**Comment by alextekartik** [comment]
Indeed, there is some race condition where _db can be null (i.e. the second time you call instance - which should be static - if openDatabase is not done, _db is still null). Your question regarding singleton is not sembast related. You might consider using StackOverflow for such usage question in the future. Here is an old but still good question about singleton in dart: https://stackoverflow.com/questions/12649573/how-do-you-build-a-singleton-in-dart

Assuming you then know how to make a singleton, here is what could be on OpenHelper:
```dart
///
/// Helper to open a single instance of a database
/// This should be a global or singleton
///
class OpenHelper {
  final String path;
  Database _db;
  Completer<Database> _completer;

  OpenHelper(this.path);

  /// Get the opened database
  Future<Database> getDatabase() async {
    if (_completer == null) {
      _completer = Completer();
      _openDatabase();
    }
    return _completer.future;
  }

  Future<Database> _openDatabase() async {
    _db = await databaseFactoryIo.openDatabase(path);
    // Mark as opened
    _completer.complete(_db);
    return _db;
  }
}
```

that can be used to safely get a unique database instance

```dart
// Make openHelper a singleton
var openHelper = OpenHelper(dbPath);

// Get the database in a safe way
var db = await openHelper.getDatabase();
await db.put('value', 'key');
```
