### ISSUE TITLE
Size limit for data storage

### ISSUE THREAD

**Issue by rizwan-dev** [tekartik/sembast.dart#110]
I want to store approx 40000 records. Will sembast would be suitable for it? Is there any performance issue with such big data?
Please let me know about the size constraint of sembast DB. I have to take the decision for my project.

**Comment by alextekartik** [comment]
The main issue is that everything is loaded into memory (!!!) on start so it will likely gives poor start performance. 

The main size constraint is memory, the storage itself is not very optimized neither. I would say at first that sembast is not the best choice here (although I have tried once with 100k records). Assuming you use flutter, sqflite would have better performance.

**Comment by rizwan-dev** [comment]
Thanks for your reply Alex. Actually I want to use no SQL db for data storage in my app. Could you please suggest any no SQL db with record storage in json format and also it can store upto 50000 records.

**Comment by 926** [comment]
@alextekartik this is alarming news, what if we need to download a list of 50 000 objects ?
I ran a simulation and it seems that there is a limit at 50 000.
Do you see any alternative ?

**Comment by 926** [comment]
Hi @alextekartik,

I understand that everything is loaded into memory on start,
But isn't there a way to turn around this problem ?
What about using an isolate or compute not to block the main thread ?
I init sembast in .main and it causes up to 6 minutes delay for some users

> flutter: before entering db 2021-03-12 18:45:10.855035
> flutter: after open db 2021-03-12 18:51:12.128178

```
print('before entering db ${DateTime.now()}');
  Database database =
      await dbFactory.openDatabase(path, codec: codec, version: 1);
  print('after open db ${DateTime.now()}');
```

**Comment by alextekartik** [comment]
What is the size of database and the platform it is running on? Also, it depends on the codec used. Do you have an easy way to test with or without the codec?

**Comment by 926** [comment]
Thank you for lightning speed reply, again !
db weighs 90 mo and runs on desktop,
Indeed codec slows things down, if I remove it, db is loaded twice faster,
This is already a big step forward thanks :)

[ +305 ms] flutter: before entering db 2021-03-13 10:39:20.039770
[+176153 ms] flutter: after open db 2021-03-13 10:42:16.194147

**Comment by alextekartik** [comment]
Even with 90mb, it should more be around 10s than 3mn. I'll be interested in seeing the db if that is possible.
