### ISSUE TITLE
boolean value cannot be sorted.

### ISSUE THREAD

**Issue by vifird** [tekartik/sembast.dart#112]

**Comment by alextekartik** [comment]
I wonder what should be the order? false then true, or true then false

**Comment by vifird** [comment]
`true` can be treated as number `1`, `false` can be treated as number `0`?

**Comment by alextekartik** [comment]
Other database I have tried firestore and indexedDB don't support indexing/sorting on boolean neither. If you need sorting I suggest using 1 and 0.

**Comment by vifird** [comment]
@alextekartik Got it, thanks.
