### ISSUE TITLE
Not able to open database using sembast in flutter WEB

### ISSUE THREAD

**Issue by VarmaTech** [tekartik/sembast.dart#113]
I want  independent local database for Web, Android and IOS application with same code base . so i used sembast but not able to get the path for Database , 
i launch application in chrome and below are my logs of flutter .

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.2-pre.54, on Mac OS X 10.15.2 19C57, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!
```

Please let me know what mistake i am making

**Comment by alextekartik** [comment]
Sembast is io only and not supported in Flutter Web.

**Comment by VarmaTech** [comment]
is there a way to have local database that supports Flutter Web

**Comment by alextekartik** [comment]
That is not the purpose on sembast. The only real database on the web is indexeddb so you can use that or any solution on top of that (hive, idb_shim/idb_sqflite)

**Comment by furkansarihan** [comment]
@alextekartik Why am I be able to run sembast on Flutter Web project? It just works on chrome but I could not figure it out that caching the .db file, so I am here to asking for information, thanks.

**Comment by alextekartik** [comment]
An experimental version of [sembast_web](https://pub.dev/packages/sembast_web) has been published
