### ISSUE TITLE
Records are not being deleted

### ISSUE THREAD

**Issue by matiapa** [tekartik/sembast.dart#116]
When I delete a document a "deleted: true" is added, and when I update it a new record is created but the old one keeps in the .db file.

How can I actually remove the document? I dont have a lot of space so I'd like to avoid this behaviour.

**Comment by alextekartik** [comment]
That's per design, the database use an append-only format. It will get compacted and removed at some point. See explanation here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md

**Comment by matiapa** [comment]
> That's per design, the database use an append-only format. It will get compacted and removed at some point. See explanation here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md

Thank you. Is there any way to manually compact the database or change the algoritm rules for starting compaction?

**Comment by alextekartik** [comment]
The `compact()` method is not exported. It has a cost as it will rewrite the whole database. If you really need you can access it by including a private import:
```dart
import 'package:sembast/src/database_impl.dart';

await (db as SembastDatabase).compact();
```

Nobody asked for it so far and I'm not sure it makes sense in exporting it (as it is a no-op for in memory database for example). If other people want it I can make it a public API.
