### ISSUE TITLE
Ordering by property of nested object

### ISSUE THREAD

**Issue by fvisticot** [tekartik/sembast.dart#12]
By exemple:
Records:
{firstname: 'fred', lastName: 'toto', address: {city: 'paris'}}

The filter:
 SortOrder('address.city')

**Comment by alextekartik** [comment]
Thanks for filling a request. It makes sense and can easily be done. Will tackle that after the holidays

**Comment by alextekartik** [comment]
Hi, this is implemented as of 1.13.0. Let me know if that works for you

**Comment by GregorySech** [comment]
Does the `mapname.keyname` notation work on Filter(s) too?

**Comment by alextekartik** [comment]
Yes:
https://github.com/tekartik/sembast.dart/blob/498641374589e87a56b6f8641937da67b5c20bdf/test/find_test.dart#L456-L457
