### ISSUE TITLE
Pagination Query

### ISSUE THREAD

**Issue by VarmaTech** [tekartik/sembast.dart#125]
Hi,

i have table with huge records , so i want to show like pull to refresh . how to get data on every request (ex LIMIT 10,20  ) , 
in sembast . please help out .

**Comment by alextekartik** [comment]
Finder has a offset and limit parameter

**Comment by saravananmnm** [comment]
@alextekartik 
It was not working as expected. It was returned always first 25 records only, but it has total records 50.

` List<OrdersMasterDTO> orderDetails = [];
    var finder = Finder(filter: Filter.equals('orderUploadsStatus', uploadStatus),limit: pageSize??null,offset: pageNumber??null);
    await ordersMasterStore.find(db, finder: finder).then((onData) {
      if (onData != null) {
        for (var items in onData) {
          orderDetails.add(OrdersMasterDTO.fromJson(items.value));
        }
      }
    }).catchError((e) {
      return null;
    });
    return orderDetails;`
