### ISSUE TITLE
[Question] How to get grouped records count?

### ISSUE THREAD

**Issue by vifird** [tekartik/sembast.dart#129]
For example, i have a `order` store, and it has a `category` field inside, now i want to get the order count of each category, how to write the query?

**Comment by alextekartik** [comment]
Indeed NoSql databases are not the best to perform such operation. I think MongoDB has some aggregate/mapReduce feature that I'm not familiar with. If you have suggestions for a convenient (strongly typed) API, you are welcome.

In the mean time, this is what is possible using multiple queries.

Assuming the following content:

```dart
var store = intMapStoreFactory.store('order');
await store.addAll(db, [
  {'category': 'cat1'},
  {'category': 'cat1'},
  {'category': 'cat2'}
]);
```
You can count easily for one category using the following
```dart
// Count for 1 category
var myCategory = 'cat1';
var count =
    await store.count(db, filter: Filter.equals('category', myCategory));
expect(count, 2);
```

To get the result for every category, fastest is to loop through each record (it is in memory so it is fast)

```dart
// Count by category
var counts = <String, int>{};
await for (var snapshot in store.stream(db)) {
  var category = snapshot['category'];
  counts[category] = (counts[category] ?? 0) + 1;
}
expect(counts, {'cat1': 2, 'cat2': 1});
```

**Comment by vifird** [comment]
@alextekartik Got it, thanks a lot.
