### ISSUE TITLE
How to use streamBuilder to read your data from sembast db

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#131]
How do I use streamBuilder to read my data from sembast db, so that the stream will be listening to changes from my local db to make changes to the Ui accordingly...would be very grateful for a basic example, please

**Comment by alextekartik** [comment]
There is a super basic example here: https://github.com/alextekartik/flutter_app_example/tree/master/demosembast
only listening for a record change.

There is a pending work in progress https://github.com/tekartik/sembast_flutter_more.dart/tree/master/sembast_flutter_example that I need to work on to add edition. but it does use StreamBuilder and onSnapshot to track store changes.

Basically it can be used like firestore using onSnapshot(s) to listen to query or record changes. Sorry I don't have any better public example yet.

**Comment by alextekartik** [comment]
I created a basic notepad using sembast available here:
https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast

Online demo:
https://alextekartik.github.io/flutter_app_example/notepad_sembast/
