### ISSUE TITLE
There is support to many-to-many relationships?

### ISSUE THREAD

**Issue by daybson** [tekartik/sembast.dart#135]
I want to be able to have a model like this, where Item can belong to more than one Owner, and a Owner can have multiples Item.

```
class Owner 
{ 
int id;
List<Item> items; 
}

class Item
{ 
int id;
int description;
}

```

But in my model I want to be able to do something like:
`owner.items();`

and automatically load all Items objects from the owner object.

**Comment by alextekartik** [comment]
sembast does not have any relationship built-in. You have to load all owner items manually or embed them in the owner object.
