### ISSUE TITLE
how to use Multi table in sembast 

### ISSUE THREAD

**Issue by VarmaTech** [tekartik/sembast.dart#145]
Hi , 

I am not able to fetch data when multi table which are having relationship . so can any one help as per the below image 

![image](https://user-images.githubusercontent.com/16360182/78145225-3ee9c400-744e-11ea-823b-06c8130dcf64.png)

finally i need data like 
ORDER_ID, USER_FULL_NAME, PRODUCT_NAME, PRODUCT_PRICE .  from 3 different table . 

please help me out.

**Comment by alextekartik** [comment]
Sembast does not provide a way to query multiple stores unfortunately. However getting an entity by id (here a user or a product) is almost immediate (`store.record(id).get(db)` or `store.records(ids).get(db)`) so I think your best bet is to query the order_items store and fetch the users and products by ids.
