### ISSUE TITLE
Filter.matchesRegEx not working on nested field

### ISSUE THREAD

**Issue by tobinharris** [tekartik/sembast.dart#146]
Sembast is great. But struggling to get this filter working Here's the query:

```
var filter = Filter.or([      
      Filter.matchesRegExp('tags.tag', reg, anyInList: true),
      Filter.matchesRegExp('name', reg)
    ]);
```

And the structure I'm querying looks like this

```
"name": "Blah",
"tags": [
                {
                    "id": 2,
                    "tag": "veggie"
                }
            ],
```
If the filter matches on name, it always works fine. But if I try and match on a tag, it never works. Am I missing something"

I've also tried just doing an `equals` or `matches` filter on just the nested field, no composite `or`. Still doesn't work.

**Comment by alextekartik** [comment]
Unfortunately field name `xxx.yyy` means nested map i.e.:
```dart
{
  "xxx": {
    "yyy": ...
  }
}
```

and not nested list of map like you have
```dart
{
  "xxx": [
    {
      "yyy": ...
    },
    {
      "yyy": ...
    }
  ]
}
```

In you query, this would mean that the data should have been in the following form:
```
{
  'name': 'Blah',
  'tags': {
    'tag': ['veggie', 'other_tag']
  },
}
```

Basically looking into nested list of objects is not supported using basic filters. While we could make it smart to handle both format, it means deeper lever access `xxx.yyy.zzz` would be even more confusing (i.e. is xxx, yyy or zzz a list?).

However there is a solution for your needs using custom filter:
```dart
// Custom filter matching any tag inner object with [reg] RegExp.
var customFilter = Filter.custom((record) {
  var tags = (record['tags'] as List)
      .map((tag) => (tag as Map)['tag'] as String);
  for (var tag in tags) {
    if (reg.hasMatch(tag)) {
      return true;
    }
  }
  return false;
});
var filter =
    Filter.or([customFilter, Filter.matchesRegExp('name', reg)]);
```

This should give the selection you expect (I think but I can be wrong).

**Comment by tobinharris** [comment]
HI, many thanks @alextekartik, that custom filter worked great. 
 
![image](https://user-images.githubusercontent.com/25578/78970214-b4196100-7b00-11ea-9936-7a19ac76695d.png)

🥇
