### ISSUE TITLE
Filter specific field in List

### ISSUE THREAD

**Issue by chitgoks** [tekartik/sembast.dart#147]
So currently, Filter.match() has an anyInList property. 

This is more of a feature request, where you can specifically identify the field of the list's item so other fields will be ignored.

Currently the anyInList example states // if `categories` field is a list with text elements

so if the list is an array of objects, then this is not possible? the matches() will only work with anyInList if the array contains text strings, not objects?

**Comment by chitgoks** [comment]
ok never mind. was looking into closed issues nad saw the sample custom filter

**Comment by nhatnam240996** [comment]
I have the same issue. Do you have a solution?

**Comment by chitgoks** [comment]
please see my previous comment.

**Comment by yemenpoint** [comment]
###    **my solution**
### Filter by creator id


```

{

"id":11,
"name":"any",
"creators":[
{
  "id":1, 
  "name":"name1"
 },
{
  "id":2, 
  "name":"name2"
 }
]

}


```


```
   static Future<List<Products>> ofCreator(int creatorID,
      [int fromID = 0]) async {
    var allrecoreds = await store_box.find(await BaseRepo.getDatabase(),
        finder: Finder(
            limit: 20,
            filter: Filter.and([
              Filter.greaterThan("id", fromID),
              Filter.custom((record) {
                var fieldValue = record["creators"];
                if (fieldValue is Iterable) {
                  for (var itemValue in fieldValue) {
                    if (itemValue["id"] == creatorID) {
                      return true;
                    }
                  }
                }
                return false;
              })
            ])));
    return allrecoreds.map((e) => Products.fromJson(e.value)).toList();
  }

```
