### ISSUE TITLE
Converting object to an encodable object failed: Instance of 'ImmutableMap<String, dynamic>'

### ISSUE THREAD

**Issue by Virendra-Varma** [tekartik/sembast.dart#150]
Hi I am getting this issue while tying to save Map<String, dynamic> value

`Converting object to an encodable object failed: Instance of 'ImmutableMap<String, dynamic>'
I/flutter (30845): #0      _JsonStringifier.writeObject (dart:convert/json.dart:659:7)
I/flutter (30845): #1      _JsonStringifier.writeMap (dart:convert/json.dart:740:7)
I/flutter (30845): #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:695:21)
I/flutter (30845): #3      _JsonStringifier.writeObject (dart:convert/json.dart:650:9)
I/flutter (30845): #4      _JsonStringStringifier.printOn (dart:convert/json.dart:846:17)
I/flutter (30845): #5      _JsonStringStringifier.stringify (dart:convert/json.dart:831:5)
I/flutter (30845): #6      JsonEncoder.convert (dart:convert/json.dart:260:30)
I/flutter (30845): #7      JsonCodec.encode (dart:convert/json.dart:168:45)
I/flutter (30845): #8      SembastDatabase.encodeRecordMap (package:sembast/src/database_impl.dart:214:49)
I/flutter (30845): #9      SembastDatabase.storageCommitRecords (package:sembast/src/database_impl.dart:414:23)
I/flutter (30845): #10     SembastDatabase.transaction.<anonymous closure>.postTransaction (package:sembast/src/database_impl.dart:1150:25)
I/flutter (30845): #11     SembastDatabase.databaseOperation.<anonymous closure> (package:sembast/src/database_impl.dart:1042:28)
I/flutter (30845): #12     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:2`

my Flutter doctor -v output is 

`flutter>flutter doctor -v
[√] Flutter (Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.15063], locale en-US)
    • Flutter version 1.17.0-3.2.pre at D:\flutter
    • Framework revision 2a7bc389f2 (5 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\AndroidStudioSDK
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!`

**Comment by alextekartik** [comment]
Hi and thanks for the report
What is likely happening here is that you have a field which is not json encodable in your data (not in bool, num, String, List, Map, Timestamp, Blob). Do you have more information about that data you are saving? For example a DateTime could produce the issue (although there should be some warning logs in the console before so there is likely an issue in sembast when parsing the value).

**Comment by alextekartik** [comment]
Also can you tell me which version of sembast you are using (and try the latest >=2.4.2 if not using it yet). Thanks!

**Comment by Virendra-Varma** [comment]
Please close this issue Actually in my map one entry have null key
