### ISSUE TITLE
Reactive Streams NoSQL Example

### ISSUE THREAD

**Issue by rafaband** [tekartik/sembast.dart#155]
It would be nice to have some real functional example for seambast stream. All the examples are snippets.

Something using a Serialized class, without Provider or RxDart. Some tasks app, just to show the real power about it

**Comment by alextekartik** [comment]
I created a basic notepad using sembast available here:
https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast

Online demo:
https://alextekartik.github.io/flutter_app_example/notepad_sembast/

**Comment by rafaband** [comment]
I found your git just great. Reading my own comment I forgot to write the "without" LOL.

I don't know, maybe I'm wrong, but A simple CRUD, simple stream working example, will help others to use Sembast.

I'm new with Dart and Flutter, and just loving it!! But I didn't found any tutorial about using and saving local data.

Every tutorial uses Firebase, some uses SQLite and seambast. But none make it simple.

I'll try to build something like it based on your git!!

**Comment by alextekartik** [comment]
In the same repo there is a raw example:
https://github.com/alextekartik/flutter_app_example/tree/master/demosembast

No 3rd party dependency, the simple counter button application with persistency and usage of a stream on one record, all in one file based on the flutter application template: https://github.com/alextekartik/flutter_app_example/blob/master/demosembast/lib/main.dart

I'm aware of the lack of documentation. You are welcome to write some after your first experiment!

**Comment by rafaband** [comment]
I did one simple CRUD based on the links you sent. Check it out.
https://github.com/rafaband/flutter_sembast_stream_crud
