### ISSUE TITLE
SembastStoreRef has no instance method 'query' Error, after update to 2.4.3 from 2.1.2+3

### ISSUE THREAD

**Issue by thetpaingsoe** [tekartik/sembast.dart#156]
Hi,

I am trying to update from version 2.1.2+3 to 2.4.3. I got this error
'SembastStoreRef<String, Map<String, dynamic>>' has no instance method 'query'.
But when i put back 2.1.2+3, everything is working fine. Only not working after update 2.4.3.

After this line run,
![Screen Shot 2020-05-04 at 4 31 39 PM](https://user-images.githubusercontent.com/3047856/80955152-c008f200-8e24-11ea-9c8b-405fa19b447f.png)

This error is come out.
![Screen Shot 2020-05-04 at 4 30 57 PM](https://user-images.githubusercontent.com/3047856/80955117-abc4f500-8e24-11ea-93d3-e391f43f989a.png)

**Comment by alextekartik** [comment]
Thanks for the report. 

Do you have the following import?:
```dart
import 'package:sembast/sembast.dart';
```

What has change indeed is that in 2.4.3, query is defined in an extension (so meaning SDK >= 2.6) but the API should be the same.

If you import sembast methods using hide and show (for example explicitely showing StoreRef only, you might need to add explicitely:
```dart
import 'package:sembast/sembast.dart' show SembastStoreRefExtension;
```

Sorry for the trouble, the goal is decoupled the definition of a store and its methods in the future.

**Comment by thetpaingsoe** [comment]
When i try to run with 2.4.2, everything is working fine. 
Only happened at 2.4.3.

And it is not only "query", other function also.
![Screen Shot 2020-05-04 at 9 31 43 PM](https://user-images.githubusercontent.com/3047856/80982643-9adea880-8e51-11ea-8346-89c57a3aa980.png)

And i can't explicitly import only **StoreRef**, because i also using others. So, my import become like this. But its still not working.
`
import 'package:sembast/sembast.dart'
    show
        Database,
        Filter,
        Finder,
        QueryRef,
        SembastStoreRefExtension;
'

Thanks for your reply.

**Comment by alextekartik** [comment]
That's weird indeed. Can you extract your issue in one file to try to analyze the issue?

**Comment by thetpaingsoe** [comment]
When i change this code,  it's working now. I tried with v2.4.3.

```
StoreRef<String, dynamic> storeRef;

storeRef = stringMapStoreFactory.store(getStoreName());
```

From this code. This code is worked till v2.4.2.
```
dynamic storeRef;

storeRef = stringMapStoreFactory.store(getStoreName());
```

For intMapStoreFactory
```
StoreRef<int, dynamic> storeRef;

storeRef = intMapStoreFactory.store(getStoreName());
```

**Comment by alextekartik** [comment]
Yes this should not work as flutter cannot infer the type of storeRef that you explicately set as dynamic:

```
dynamic storeRef;
storeRef = stringMapStoreFactory.store(getStoreName())
```

This should work however
```
var storeRef = stringMapStoreFactory.store(getStoreName())
```

I encourage you [to turn on strong mode](https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks) at least implicit-casts to catch code potential error at compile time.

**Comment by thetpaingsoe** [comment]
> I encourage you to turn on strong mode at least implicit-casts to catch code potential error at compile time.

Thanks, i will check.
