### ISSUE TITLE
Timestamp.nowUtc(), please

### ISSUE THREAD

**Issue by deakjahn** [tekartik/sembast.dart#158]
Very simple feature request: in addition to `Timestamp.now()`, can we have a `Timestamp.nowUtc()` as well? Yes, it's rather straightforward to do

    Timestamp.fromDateTime(DateTime.now().toUtc())

but it would be sooo nice. :-)

**Comment by alextekartik** [comment]
There is no timezone information in a timestamp. Everything is utc. So basically, whatever your timezone is. The result is the same.

Quick example now in my timezone:

```
print(DateTime.now().toUtc());
print(DateTime.now());
print(Timestamp.fromDateTime(DateTime.now().toUtc()));
print(Timestamp.fromDateTime(DateTime.now()));
```
gives
```
2020-05-12 20:51:36.653541Z
2020-05-12 22:51:36.655645
Timestamp(2020-05-12T20:51:36.655806Z)
Timestamp(2020-05-12T20:51:36.656715Z)
```

As you see the datetime are different but the timestamp are the same whether or not toUtc() was used.

**Comment by deakjahn** [comment]
Then please, mention this in the code comment. I might not be the only one culpable that doesn't check but still starts yapping... :-)

**Comment by alextekartik** [comment]
I added some doc https://github.com/tekartik/sembast.dart/commit/d721fa7e9f48d854cab05c7b9e3ac2637f2d3c86

If you think of a specific note, phrase that could help in improving the document that you would expect for this specific constructor, let me know!

**Comment by deakjahn** [comment]
Just perfect, thanks.
