### ISSUE TITLE
[Question] Multi-subscription streams

### ISSUE THREAD

**Issue by andreyeurope** [tekartik/sembast.dart#164]
Any idea if you would support multi-subscription streams in the future?

**Comment by alextekartik** [comment]
Hi. I'm not sure yet what would be the need. You can use `asBroadcastStream` to convert it if needed. Personally I feed RxDart BehaviorSubject and I think anybody is free to use anything they want. I'm not an expert here so I wonder what would be the need and why should we differ from standard io stream like File. 

onSnapshot(s) stream uses RAM so proper cancellation to avoid memory leaks is a must.

Do you some idea what should the API look like and what would be the usage (without breaking compatibility)? I wanted the onSnapshot stream be somehow similar to firestore. Are firestore stream single or multi-subscription?

**Comment by andreyeurope** [comment]
Ah.. you are right about the `.asBroadcastStream`. I forgot about it.
About the firestore package, I am not 100%, but they might be using the single subscription stream as well because you can easily change it to a multi subscription stream.
