### ISSUE TITLE
onSnapshots(db) gives me errors

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#169]
I get my db instance this way: Future<Database> get db async => await RmgDB.instance.db;

but when I use in the stream : 
Stream<List<FarmerTransactions>> onInputs({farmerId}) {
      // Database _db = RmgDB.instance.db;
      Database _db;
      var finder = Finder(filter: Filter.equals('farmer_id', farmerId));
     
      return _farmersInputAllocations
          .query(finder: finder)
          .onSnapshots(db)
          .transform(notesTransformer);
    }

I get this error The argument type 'Future<Database>' can't be assigned to the parameter type 'Database'

Please how do I resolve this?

**Comment by alextekartik** [comment]
`db` is a future

```dart
Future get db async => await RmgDB.instance.db;
```

so you should await it:

```dart
onSnapshots(await db)
```

**Comment by MichaelSowah** [comment]
I did that but I get error The await expression can only be used in an async function.
Stream<List<FarmerTransactions>> onInputs({farmerId}) {
      // Database _db = RmgDB.instance.db;
      Database _db;
      var finder = Finder(filter: Filter.equals('farmer_id', farmerId));
     
      return _farmersInputAllocations
          .query(finder: finder)
          .onSnapshots(await db)
          .transform(notesTransformer);
    }

**Comment by alextekartik** [comment]
Make sure you db object is ready before.

**Comment by MichaelSowah** [comment]
> Make sure your db object is ready before. Otherwise you have to create your own stream controller first and pipe data from it

How do I do that because I used the sample from the sembast demo app

**Comment by alextekartik** [comment]
Hard to say without seeing your code. make sure you db object is a Database and not a Future<Database>, you can await for it before calling runApp

**Comment by MichaelSowah** [comment]
I Solved it
