### ISSUE TITLE
meta dependency

### ISSUE THREAD

**Issue by LandReagan** [tekartik/sembast.dart#17]
Hi!
A quick one: your 1.13.3 depends on meta ^1.1.7 but Flutter is still on 1.1.6 (not above), which makes the version solving to fail, for Flutter users.
Workaround is to use your sembast dependency at ^1.13.2 while waiting for Flutter to upgrade its meta dependency...
All the best,

**Comment by alextekartik** [comment]
Thanks for catching this. Fixed in 1.13.3+1 published now
