### ISSUE TITLE
Pass multiple fields in one filter?

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#171]
Can I pass more than one field in the filter?
eg: Finder(filter: Filter.equals('product', 'AF8', 'name', 'myname'));

**Comment by alextekartik** [comment]
You can do:
```dart
Filter.equals('product', 'AF8') & Filter.equals('name', 'myname')
```
See: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/queries.md#composite-filter

AFAIK dart does not support arbitrary number of positionned arguments (you have to list them all even if optionnal).
