### ISSUE TITLE
[web] Peformance

### ISSUE THREAD

**Issue by deakjahn** [tekartik/sembast.dart#175]
How would you suggest to log and check performance issues? I have the following

    final result = await db.Attributes.find(productDb,
        finder: Finder(
          filter: Filter.equals('sku', sku) & Filter.equals('is_primary', true),
        ));

now taking literally more than 30 seconds to run (around a thousand records to find from). Than can't be for real. :-)

Oh, it's on Flutter Web, not mobile.

I tried `var _debug = true;` in `jdb_factory_idb.dart` that does emit lots of items (good thing, I spotted another problem of mine :-) ), but nothing around here, actually.

**Comment by deakjahn** [comment]
Partly related question. Using `_debug` revealed to me that using a simple `StoreRef.count()` actually reads all relevant records just to count them. Is this really so?

**Comment by deakjahn** [comment]
To counter that, I had the idea of reducing this overhead at least partially, because I actually only need to check whether the count is greater than zero, to:

      final result = await db.Products.findFirst(productDb, finder: Finder(limit: 1));
      return result != null;

but `_debug` shows that it doesn't stop at the first product it finds.

**Comment by deakjahn** [comment]
Another day, system restarted, web browser including. It isn't 30 seconds now. Not instantaneous but much better, so it might have been something else.

The second question still remains, if you could give some suggestions. :-)

**Comment by deakjahn** [comment]
Well, new day, systems restarted. On first run, it was significantly better, just a few seconds, but on subsequent runs (not hot reloads, completely new compilation, Chrome started again from not running) and we're back in the dozens of seconds range. So, definitely something fishy going on, just that I can't yet see how to investigate this. :-)

**Comment by alextekartik** [comment]
Thanks for the reports. Indeed query performance can be improved. Initial loading could be slow however query should not take 10s to run though. Can you confirm that you get this result just for the query (i.e. not including open)?

I will look into some optimization (especially when there is no sort order)

**Comment by deakjahn** [comment]
I've just checked. Release mode is just fine. I do expect debug to be somewhat slower but the difference here is much too large for actual work while debugging. :-)

Yes, just the query. I went down to `forEachRecords()` in `store_impl.dart`. Of course, when I start sending messages to the log for each record, this alters the timing more than drastically, so it's not easy to measure this. But my hunch is that every filter check for each record consumes on the order of magnitude of 100 ms now, multiplied that with the number of records in the range of a thousand, this results in the timeouts I can see now.

**Comment by alextekartik** [comment]
> StoreRef.count() actually reads all records in the database

I added an optimization when no filter are used to avoid going through all the records.

> (findFirst) shows that it doesn't stop at the first product it finds.

Here as well I added an optimization when no sort order are used.

Published in 2.4.4+3

**Comment by deakjahn** [comment]
Does this mean that a single

      return await db.Products.count(await productDb);

shouldn't emit all records when using `_debug = true`. It still does for me. The findFirst() was actually an attempt to make it cheaper if we have to enumerate all records to see which belong to the table.

**Comment by deakjahn** [comment]
Oops, you know what I found? With

    // no filter optimization
    print(filter);
    if (filter == null) {

in 'store_impl.dart`, I get all the records in the log, *then* comes the print(filter) that emits null. :-) I'll dive down to see who emits them before, too.

**Comment by alextekartik** [comment]
I think the log line (`[idb-1] reading entry [n]`) you are seeing are logged when opening the database (the database is loaded into memory), not when performing the count operation.

**Comment by deakjahn** [comment]
Could well be. Then I turn it off because is skews everything else...

**Comment by deakjahn** [comment]
Well, let's consider the `count()` and the other solved, they will be just fine. That leaves the question of the normal find query, the last run was like this:

![Annotation 2020-06-07 180727](https://user-images.githubusercontent.com/2234271/83973917-e0c3dc00-a8e9-11ea-99ab-6059ba771a4b.png)

And in release it's lightning, no reason to time it at all. What could result is such a difference in debug mode? And if you don't see anything remotely similar, even more interesting. I have a plain vanilla Chrome, last version, and my Flutter is

```
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.836], locale en-US)
    • Flutter version 1.18.0-11.1.pre at E:\Android\flutter-beta
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)
```

And I couldn't say that Sembast would always be that slow throughout my app because it isn't. Yes, debug is sure slower than release but completely usable to test the operation of the app. Just these pesky find()s where obviously I don't grab a record by its key but have to iterate through everything to get what matches.

**Comment by alextekartik** [comment]
I think sembast cooperator (weird concept to allow some heavy algorithms without blocking the UI) is causing the long day issue in Debug mode on the web. If there is a way to detect that the user is debugging the app (?), maybe its timing could be adapted. I think I have avoided to debug as much as possible on the web (I debug mostly on Android and just 'run' on the web) so I never encountered such issue.

If the mean time, can you try to call `disableSembastCooperator()` in your main before any database operation to see if it solves your issue temporarily?

**Comment by deakjahn** [comment]
I will right now but what do you actually mean by "If there is a way to detect that the user is debugging the app (?)"? The fact itself that it's running is debug mode? Because detecting that would be the easiest thing on Earth, it's in the framework (actually, you don't need `env_utils.dart` at all, it could be removed completely).

**Comment by alextekartik** [comment]
I meant debugging, not running in debug mode.

Le dim. 7 juin 2020 à 19:53, Gábor DEÁK JAHN <notifications@github.com> a
écrit :

**Comment by deakjahn** [comment]
Absolutely and definitively. With the cooperator disabled, it works just like it's supposed to work. What does this beastie do, apart from doing harm? :-)

**Comment by deakjahn** [comment]
Oh, I see in the source, question retracted. The real question is whether what it does could not be accomplished in a different way...

**Comment by deakjahn** [comment]
What if you turned it around? Keeping it disabled normally, and emitting log messages in debug mode (I means always, not just on the web), and only when sorting is actually called for, to suggest that if the user experiences jerkyness, it could be turned on?

**Comment by alextekartik** [comment]
That could be a solution. I need to spend more time on flutter web and debugging to see how we could avoid this. In the meantime, you can call `disableSembastCooperator()` manually in debug mode.

**Comment by deakjahn** [comment]
I actually don't need sorting anywhere now, so I simply disable it at start. I'll test it, though.

**Comment by alextekartik** [comment]
I published a new sembast version (2.4.6) that specifies different delay for the cooperator on the web. It still impact performance (about 20% in my testing) to the benefit of no jank (that could be seen while scrolling a huge list while fetching data).

Hopefully you should not need to call disableSembastCooperator. As note, you can now specify custom timing in enableSembastCooperator, although my wish is that nobody needs that.

**Comment by deakjahn** [comment]
I'll test is but I still think I'll trade the 20% improvement for it because I don't really use operations that would benefit from it. :-)

My initial database population is rather time consuming so I already cut that down by using several databases and only doing the minimum at first, storing the incoming data and setting up the rest when the user first goes that route. That second pass could still benefit from some added speed, so I don't want to reduce it in any way. Apart from that, all my reads are small.

**Comment by deakjahn** [comment]
This is a part of my app that needs to be revisited because the timing is still unacceptable for the user, so these are the current timings. Debug mode, intentionally. 34 secs with cooperator, 30 secs without. Small difference but still.

What would really help would be a way to do bulk inserts directly in your code, without going through the many additional operations for each one. You just receive a list of records somehow and insert them as fast as possible, without needing to do the usual routine, calling through layers, checking filters and everything that caters for the general case. I don't know if it's feasible but that's what would really help.

I remember a similar case, when I was doing a .NET app using Entity Framework, if you know it. It makes database operations rather simple by creating strongly typed classes for everything and abstracting away all relations. Bulk insert was abysmal, though, becasue it started to check for and manipulate foreign keys (and doing who knows what else) for every single insert. Fortunately, it was possible to turn all that off, dump the data into the tables, turn it on again, and it was a breeze then.

**Comment by alextekartik** [comment]
Indeed 34s is not acceptable. How many records are inserted? I have a sample app here: https://notelio.surge.sh where you can try insert action from the menu. Adding 100 records should not take more than 2s (on the desktop it is almost immediate), web is definitely slower.

There are 2 ways to do bulk insert:
- use [`store.addAll`](https://pub.dev/documentation/sembast/latest/sembast/SembastStoreRefExtension/addAll.html)
- use a [transaction](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/transactions.md)

Typically I use a transaction and group writes/add by 100 like I do also with SQLite, it gives good performance without locking the database.

**Comment by deakjahn** [comment]
I use `addAll` where I can, and I always use transactions. Here is the relevant code:

    _extraDb = await _dbFactory.openDatabase(await getDatabasePath(_EXTRA_FILENAME), version: _VERSION, mode: DatabaseMode.empty);
    return await _extraDb.transaction<bool>((txn) async {
      progress(1);
      final locale = WidgetsBinding.instance.window.locale;
      if (data.backgrounds != null) {
        final backgrounds = <Map<String, dynamic>>[];
        for (final background in data.backgrounds) {
          background.setNames(locale.languageCode);
          backgrounds.add(background.toMap());
        }
        await Illustrations.addAll(txn, backgrounds);
      }

      return true;
    });
  }

And, as you can see, it goes into an empty database, so even that shouldn't count. The `setNames()` call represents a single variable assignment. And I collect the data first and send it in one go to make it faster. I'll add a few timing logs now just to make sure.

**Comment by deakjahn** [comment]
Oh, yes, the count. About a thousand or so, Could be more in the future, though. :-)

**Comment by deakjahn** [comment]
Definitely. I added the lines above:

    1 2020-07-06 13:51:36.017
    2 2020-07-06 13:51:36.019
    3 2020-07-06 13:51:36.034
    4 2020-07-06 13:52:06.184

**Comment by alextekartik** [comment]
Ok a transaction is not even needed with a single call here. As a note, a transaction should be idempotent (like firestore transaction) as it could be ran multiple times if there was a confliting change at the same time (other tab of other action). Here there might a risk that `data.backgrounds` changes which does not make it safe. You should prepare the data before the transaction if you keep it (not for the time it takes but to be idempotent). You should also try to group (i.e. wait for more items to save) and split (by 100 for example) the list of records added as the longer the transaction last, the risk of other conflicting changes gets higher.

IndexedDB can be slow (backend used by sembast_web) too and there is not much that can be done here.

**Comment by alextekartik** [comment]
As a another note, if you have more than 1000 items to save each time and plan to have a 100K records database, you might also consider using raw IndexedDB on the Web for some specific data.

**Comment by deakjahn** [comment]
Yes, I noted that but it's the same without the transaction. Actually, this was simply a pattern I use everywhere, normally with more than one operation inside. It was just copypaste and the outer transaction stayed the same... Nothing changes, those `data` values are a single large JSON that I download from the server and it contains the contents to be placed in the databases.

I actually want to bulk save once. Later on, I just use the data from the database (I also read and write other things, but that's irrelevant, small and fast). It happens on first launch, later if the whole data set is upgraded and the user can also trigger a reset.

**Comment by deakjahn** [comment]
I started to delve deeper into the code and adding logs here and there. And I started to wonder if it's -- at least partly -- to do the fact the even your basic operations (like generating keys) are all async. This always means waiting for the event loop and, of course, there might be also be differences between the platforms in how they handle this.

**Comment by deakjahn** [comment]
For instance. Here I have an empty database, meaning that keys are free to use. You can easily get away with a simple running index from one upwards. Yet, you `await generateUniqueIntKey()` for each record, and that in turn `await` calls a generator, then increments, then even `await` calls to check if it's really unique. And that check doesn't look like that cheap, either.

**Comment by alextekartik** [comment]
You're correct, I need to revisit some await. The impact was minimal on mobile/desktop but seems higher on the web. And yes some optimization could be added, especially for the unique id generation.

**Comment by deakjahn** [comment]
Do you think a function could be provided where the user is allowed to supply a full key-value map and simply dumping that into the database, without any extra checks? The user is responsible for making sure the keys are uniqe and if they're not, well, their problem. :-)

**Comment by deakjahn** [comment]
As a side note, when you mention desktop, which desktop is it? I'm contemplating trying that out, too (although the web browser is a rather good alternative these days for sure) but I don't know how useable it already is. Besides, I always had the impression that it's just a browser engine packaged with the app to make it look like desktop, but is actually web. If you say the performance is different then probably I'm mistaken.

**Comment by alextekartik** [comment]
> Yet, you await generateUniqueIntKey() for each record

I will look into the unique id generation to only read once per store in a transaction (for the first added record) and increment for the remaining of the transaction. Thanks for pointing this out.

>  supply a full key-value map and simply dumping that into the database, without any extra checks? 

Yes you can use `store.record(your_key).put/add(db, your_value)` and even `store.recods(list_of_keys)`.put/add(db, list_of_values)` to avoid slow id generation.

**Comment by alextekartik** [comment]
> As a side note, when you mention desktop, which desktop is it?

sembast_io/sembast_sqflite also works on DartVM/Flutter MacOS/Win/Linux. It is super fast (maybe too fast compare to the web). If you just have UI, http and database, Desktop works fine (Personnally I'm on Linux). As soon as you get into a plugin missing, it is a nightmare. No it is not web, it is flutter compiled natively like for mobile. The [notepad_sembast](https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast) sample application can run on the Desktop (just switch to the proper channel, dev on linux/mac, master on windows), run `flutter create .` then `flutter run -d linux/mac/window`. A real good developer experience.

**Comment by alextekartik** [comment]
You definitely point out a relevant point:
in my testing: 
- add 1000 records with id generation: 6s
- writing 1000 records without id generation: 1s

6 times faster! As you said, it ain't cheap. I will look at fixing this.

**Comment by deakjahn** [comment]
I'll try the desktop on my notebook, I don't want to mess with the channel I'm on here right now. I'm on Windows but these days, installing an Ubuntu just like any other application under Windows is just a few clicks away (actually, I've just done it two days ago to compile the Flutter engine for myself but I've deleted it for now because while it did compile, it compiles to Linux executables and that can't be used to run on Windows, anyway; I might want to get back to it and run the debug on Linux, though). And, small items, but I was really happy to see that while in a Linux inside VirtualBox I had to install half of the net to get the keyboard layout and console font I prefer, in the Windows Subsystem for Linux I just change the console font with a single click. :-)

The plugins will be missing, yes. No surprise there, I had to solve quite a few plugins for the web myself as well. I'll check it out, that will be the next step. However, not that terribly important if the web works all right.

**Comment by deakjahn** [comment]
Excellent, that's already enough to solve my problem:

    final keys = List.generate(backgrounds.length, (i) => i);
    await Illustrations.records(keys).add(txn, backgrounds);

some 4 to 5 s in debug, I didn't time it with a stopwatch now, just by feeling. I'll check my other places whether I can use the same trick.

**Comment by alextekartik** [comment]
Can you try to bump sembast (not sembast_web) to 2.4.7-dev.3?. You should see a similar improvment (6 times faster) - and with id safety (especially if you have 2 tabs adding records at the same time), thanks to you!

**Comment by deakjahn** [comment]
Yes, it has the same feeling as the one without `addAll()` and specifiy the records themselves.

**Comment by alextekartik** [comment]
performances have improved for insert and listeners. Can I close this issue?

**Comment by deakjahn** [comment]
The one above looks pretty fine to me, yes. I'll do it for ya. :-)
