### ISSUE TITLE
query on nested field not working

### ISSUE THREAD

**Issue by Edijae** [tekartik/sembast.dart#179]
I have stored a list of records in my store. An e.g of the record is 

`{objectId: ewXXl3, createdAt: 2020-03-12T12:55:06.421Z, updatedAt: 2020-06-08T09:22:12.025Z,  owner: { objectId: tf7KIYLF}}`

Now, i try to query for a record with a specific owner id like below

```
var filter = Filter.equals('owner.objectId', 'tf7KIYLF');
 var finder = Finder(filter: filter);
 var record = await intMapStoreFactory.store("Accounts").find(_database, finder: finder);
```

It returns empty list. When i follow the flow, i realize the method below in the filter_impl.dart file returns false for my record above

```
/// We can match if record is a map or if we are accessing the key or value
bool canMatch(String field, dynamic recordValue) =>
    (recordValue is Map) || (field == Field.value) || (field == Field.key);


```

**Comment by alextekartik** [comment]
Thanks for the report. I've tried the following unit test which works fine:
```dart
test('Issue#179', () async {
  var store = intMapStoreFactory.store('Accounts');
  await store.add(db, {
    'owner': {'objectId': 'other1'}
  });
  var expectedKey = await store.add(db, {
    'owner': {'objectId': 'tf7KIY'}
  });
  await store.add(db, {
    'owner': {'objectId': 'other2'}
  });

  var filter = Filter.equals('owner.objectId', 'tf7KIY');
  var finder = Finder(filter: filter);
  var records = await store.find(db, finder: finder);
  expect(records.length, 1);
  expect(records.first.key, expectedKey);
});
```
Can you dump the store 'Accounts' before the query to see if it indeed exists? Or can try to isolate the issue in a unit test? thanks!

**Comment by Edijae** [comment]
@alextekartik I'm receiving data from the backend thus i cannot separate the value of the field `owner` which is an object and save it separately. I want to store each Account object with it nested objects as one record. below is one of the record i'm receiving from backend.

`{className: Accounts, objectId: ewXXl31VF, createdAt: 2020-03-12T12:55:06.421Z, updatedAt: 2020-06-08T09:22:12.025Z,  userId: tf7KIYLFF0, total: 8, owner: {__type: Pointer, className: _User, objectId: tf7KIYLF}}`

Thus when doing a query, i want to get An account object where the value of the `owner` field contains an object with the specified id.

**Comment by alextekartik** [comment]
Is 'tf7KIY' a typo error in your query (the record has objectId set to tf7KIYF - with an extra F)?

**Comment by Edijae** [comment]
I've edited the question to correct the error.

**Comment by alextekartik** [comment]
> When i follow the flow, i realize the method below in the filter_impl.dart file returns false for my record above

To confirm, are you indeed storing the record as a map (need for field query) and not as a json string?

**Comment by fatahzull** [comment]
hi, this my sample data stored in box

```
{
  "id": "1",
  "name": "Apple",
  "isSweet": true,
  "leaves": [
    {
      "id": "1",
      "name": "leaveOne"
    },
    {
      "id": "2",
      "name": "leaveTwo"
    },
    {
      "id": "3",
      "name": "leaveThree"
    }
  ]
}
```

I just try finder = Finder(
        filter: Filter.and([
          Filter.equals('id', '1'),
          Filter.equals('leaves.id', '2')
        ]));

it wont work. The result return null. please help..

**Comment by alextekartik** [comment]
@fatahzull 

Unfortunately field name `xxx.yyy` means nested map i.e.:
```dart
{
  "xxx": {
    "yyy": ...
  }
}
```

and not nested list of map like you have
```dart
{
  "xxx": [
    {
      "yyy": ...
    },
    {
      "yyy": ...
    }
  ]
}
```

In your query, this would mean that the data should have been in the following form:
```
{
  'id': '1',
  'leaves': {
    'id': '2'
  },
}
```

Basically looking into nested list of objects is not supported using basic filters. While we could make it smart to handle both format, it means deeper lever access `xxx.yyy.zzz` would be even more confusing (i.e. is xxx, yyy or zzz a list?).

However there is a solution for your needs using custom filter (to replace the wrong `Filter.equals('leaves.id', '2')`)
```dart
// Custom filter matching any tag inner object with [reg] RegExp.
var customFilter = Filter.custom((record) {
  var leaveIds = (record['leaves'] as List)
      .map((tag) => (tag as Map)['id'] as String);
  return leaveIds?.contains('2');
});
var filter =
    Filter.or([customFilter, Filter.matchesRegExp('name', reg)]);
```

This should give the selection you expect (I think but I can be wrong).

**Comment by fatahzull** [comment]
Hi @alextekartik , Thank you for the quick response.
as per your explanation, I just try using custom filter to look into nested List. 

```
var customFilter = Filter.custom((Record) {
      var leaveIds = (Record['leaves'] as List)
          .map((tag) => (tag as Map)['id'] as String);
      return leaveIds?.contains('2');
    });
    final finder = Finder(filter: Filter.and([
      Filter.equals('id', '1'),
      customFilter
    ]));

```

printed Snapshot : 
`[Record(audit_table, 1) {id: 1, name: Apple, isSweet: true, leaves: [{id: 1, name: leaveOne}, {id: 2, name: leaveTwo}, {id: 3, name: leaveThree}]}]`

Since its AND operation, expected result should be 
`[Record(audit_table, 1) {id: 1, name: Apple, isSweet: true, leaves: [ {id: 2, name: leaveTwo}]}]`

if cant resolve this issue, worst case might be put leaves object into separate "Table".

**Comment by alextekartik** [comment]
The result printed is correct since your object was designed this way (your apple object has 3 leaves declared). If you want to seperate record for each leave, indeed you should create a separate store

**Comment by sjoudi** [comment]
I have a similar issue with nested query. I don't have the above issue of nested list of map with data.

A sample of data stored in sembast is below:
```json
{
        "value": {
		"className": "News",
		"title": "The Title",
		"description": "The description.",
		"date": "22/03/2021",
	},
	"objectId": "tQrOhHsSoz",
	"createdAt": 1619472367329,
	"updatedAt": 1619731305905
}
```
If I query data on objectId, createdAt, or updatedAt fields everything works fine.
```javascript
var filter = Filter.equals('objectId', 'tQrOhHsSoz');
var finder = Finder(filter: filter);
var records = await store.find(db, finder: finders);
print(records);
```
Results:
```javascript
Record(repository_news, tQrOhHsSoz) {
        value: {
		"className": "News",
		"title": "The Title",
		"description": "The description.",
		"date": "22/03/2021",
	},
	objectId: tQrOhHsSoz,
	createdAt: 1619472367329,
	updatedAt: 1619731305905
}
```
However, if I query store based on any of subfields in value field,  Sembast just returns null.
```javascript
var filter = Filter.equals('value.title', 'The Title');
var finder = Finder(filter: filter);
var records = await store.find(db, finder: finder);
print(records);
```

Result is an empty list.
```javascript
 []
```
although this works fine:
```javascript
var filter = Filter.notNull('value');
var finder = Finder(filter: filter);
var records = await store.find(db, finder: finders);
```
Results: I get all records in store as long as value field contains data

I just wonder what could be wrong.
