### ISSUE TITLE
Usage as a event sourcing storage

### ISSUE THREAD

**Issue by renatoathaydes** [tekartik/sembast.dart#18]
Hey, I've been looking at this project with an interest in using it as a event sourcing storage for small datasets - in the order of thousands of records per database.

My idea is to synchronize the small DB between different users of the same database (just a few users/db) via events so it's never necessary to send the whole database to new users except first time they connect... so users should see each other's changes, which should happen infrequently...

Do you think this database would fit the bill? I like that it is written entirely in Dart, so I don't need to rely on external software and could potentially use both on web clients and mobile phones.

Thanks for making this project public and open source by the way, the idea is nice and the code, from what I've seen, of high quality!

**Comment by alextekartik** [comment]
Thanks for your interest. It can definitely hold 100K+ records as long as it fits in memory. For web client, there is no support (yet) for convenient persistence (i.e. for now you have to load it in memory - ok for reading) but writing would require some additional code (that I could add if necessary)

**Comment by renatoathaydes** [comment]
Ok. Sembast  could probably use indexed_db (https://api.dartlang.org/stable/2.1.1/dart-indexed_db/dart-indexed_db-library.html) as a backend (as opposed to the file system) on the browser, no? People could then use the Sembast API on the browser, Dart VM with the filesystem and mobile (maybe even sqlflite for Flutter)?

**Comment by alextekartik** [comment]
Definitely indexeddb for the browser. For flutter, a file system is more appropriate for now as it won't take any benefit from sqflite

**Comment by alextekartik** [comment]
As a note, sembast_web has been released which supports web client.
