### ISSUE TITLE
Is Filter and on two separate record fields possible ?

### ISSUE THREAD

**Issue by vinnytwice** [tekartik/sembast.dart#181]
Hi, I'm trying to find a record passing in a `date` which gets converted to milliseconds. The record has a `int bookingStart` and an `int bookingEnd` fields, so the record to be found is the one where `date` falls between `bookingStart` and `bookingEnd`. I tried having `Filter.and` with both `greaterOrEquals` than bookingStart and `lessThan` bookingEnd but with `and` none is found. If I use `or`instead any date will wrongly succeed.
I see that in Finder there are `start:` and `end:`  but I can't really understand how to set Boundary()  to use it in my scenario.
Can you se what I'm doing wrong?

```
Future<Booking> loadBookingDetails(DateTime date) async {
    var timeSlotDate = date.millisecondsSinceEpoch;

    var start = Filter.greaterThanOrEquals('bookingStart', timeSlotDate);
    var end = Filter.lessThan('bookingEnd', timeSlotDate);

    Boundary from = Boundary();
    Boundary to = Boundary();

    final finder = Finder(
        filter: Filter.and([start, end]),
        sortOrders: [SortOrder('bookingStart', true, true)]);

    Booking booking;
    try {
      final RecordSnapshot<dynamic, dynamic> snapshot =
          await _bookingFolder.findFirst(await _db, finder: finder);
      if (snapshot != null) {
        booking = Booking.fromMap(snapshot.value);
      } else {
        print('BookingRepository().loadBookingDetails() : No booking found');
      }
      return booking;
    } catch (e) {
      print('BookingRepository().loadBookingDetails() error: $e');
    }
  }
```

**Comment by alextekartik** [comment]
Hi I understand the confusion.

If we put the boundary concept apart, i think your filter is the opposite of what you have written. You want the bookingStart less or equal than and bookingEnd greater than.

Something like this should work.

```dart
Future<Booking> loadBookingDetails(DateTime date) async {
  var timeSlotDate = date.millisecondsSinceEpoch;

  final finder = Finder(
      // bookingEnd must must be after the date and booking start before
      filter: Filter.greaterThan('bookingEnd', timeSlotDate) &
          Filter.lessThanOrEquals('bookingStart', timeSlotDate),
      sortOrders: [SortOrder('bookingStart', true, true)]);

  Booking booking;
  try {
    final RecordSnapshot<dynamic, dynamic> snapshot =
        await _bookingFolder.findFirst(await _db, finder: finder);
    if (snapshot != null) {
      booking = Booking.fromMap(snapshot.value);
    } else {
      print(
          'BookingRepository().loadBookingDetails() : No booking found');
    }
    return booking;
  } catch (e) {
    print('BookingRepository().loadBookingDetails() error: $e');
  }
  return null;
}
```

Now back to the boundary concept (similar to firestore and indexed_db). The boundary can only be used relative to the current sort order(s). Basically you set a lower and upper bound so it cannot really be on different fields. In your case, you can set an upper bound (max bookingStart) and use a filter for the end.

```dart
Future<Booking> loadBookingDetails(DateTime date) async {
  var timeSlotDate = date.millisecondsSinceEpoch;

  final finder = Finder(
      // bookingEnd must must be after the date
      filter: Filter.greaterThan('bookingEnd', timeSlotDate),
      // Use the end boundary so that bookingStart is before the date (included)
      end: Boundary(include: true, values: [timeSlotDate]),
      sortOrders: [SortOrder('bookingStart', true, true)]);

  Booking booking;
  try {
    final RecordSnapshot<dynamic, dynamic> snapshot =
        await _bookingFolder.findFirst(await _db, finder: finder);
    if (snapshot != null) {
      booking = Booking.fromMap(snapshot.value);
    } else {
      print(
          'BookingRepository().loadBookingDetails() : No booking found');
    }
    return booking;
  } catch (e) {
    print('BookingRepository().loadBookingDetails() error: $e');
  }
  return null;
}
```

**Comment by vinnytwice** [comment]
@alextekartik Hi and thanks for the code fix, it now works. I guess that Filter works the opposite of what is normally used in queries . The way I set them I was expecting Finder to find any record that "does" match the filters, it looks instead that it finds any record that "doesn't" match the filters.
Filter does the comparison "field vs value" and I thought it was "value vs field" hence mine  was working the opposite.. right?
Just as an example:

record to be found:
bookingStart 10:00
bookingEnd 11:00

expected result for passed in date:
date 10:00 => record match found
date 10:30 => record match found
date 11:00 => no record match found

so my business logic was ( value vs field ):
 date >= bookingStart & date < bookingEnd 

right business logic is  (field vs value ):

 date <= bookingStart & > bookingEnd

As for boundaries I can see its use case. 

Thank you very much again.

**Comment by alextekartik** [comment]
> Filter does the comparison "field vs value" and I thought it was "value vs field" hence mine was working the opposite.. right?

That's correct. Maybe I should made this clearer.

Filter.greaterThan('field', 'value') means field value greater than 'value' (so to read from left to right).

>  I guess that Filter works the opposite of what is normally used in queries

Well here, I'm not sure. [Firestore where](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/where.html) has the same meaning.

The correct logic should have been.
`boundaryStart <= date < boundaryEnd`

which means:

`boundaryStart <= date && boundaryEnd > date`

**Comment by vinnytwice** [comment]
> > Filter does the comparison "field vs value" and I thought it was "value vs field" hence mine was working the opposite.. right?
> 
> That's correct. Maybe I should made this clearer.
> 
> Filter.greaterThan('field', 'value') means field value greater than 'value' (so to read from left to right).

Yes, that was my confusion.

> > I guess that Filter works the opposite of what is normally used in queries
> 
> Well here, I'm not sure. [Firestore where](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Query/where.html) has the same meaning.

Well I use Real Time Database but there queries are also field compared to provided value so I guess I jus got confused and set it all wrongly..

Thanks for bringing me back on tracks..train wreck avoided ;)
