### ISSUE TITLE
Question: How to decrypt an encrypted Sembast db file

### ISSUE THREAD

**Issue by leozaragoza** [tekartik/sembast.dart#185]
Hello @alextekartik  I'm currently using Sembast with encryption for a project. To implement I followed https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/codec.md and https://github.com/tekartik/sembast.dart/blob/master/sembast/test/encrypt_codec.dart guides which are working great. So if I have access to the device db file and the password used to encrypt the database. In case I want to debug and check if the data is being saved correctly what would be the most convenient/fastest way to open the db decrypted file and check its data?

**Comment by alextekartik** [comment]
The purpose of encryption is indeed to make it hard to read. I can think of 2 ways:
- manually decrypt each line
- export the database (exportDatabase) and import it in a non encrypted database.

Unfortunately there is no general database viewer for sembast at this time.

**Comment by rammesaran** [comment]
@alextekartik  Hi, Is there any database viewer is available to view sembast db file?
