### ISSUE TITLE
FormatException: Bad UTF-8 encoding 0xa4 (at offset 49153)

### ISSUE THREAD

**Issue by Lidgett** [tekartik/sembast.dart#187]
Hello.  My app has just recently started to kick out this error.  It previously worked well with Android and iOS, and until today it worked flawlessly.  

Whenever I try to open the database it returns me this error -> FormatException: Bad UTF-8 encoding 0xa4 (at offset 49153)

If I wrap the db opening method in a try catch I get this (below):

I/flutter ( 3188): #0      _Utf8Decoder.convert (dart:convert/utf.dart:532:13)
I/flutter ( 3188): #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
I/flutter ( 3188): #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
I/flutter ( 3188): #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
I/flutter ( 3188): #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
I/flutter ( 3188): #5      _rootRunUnary (dart:async/zone.dart:1192:38)
I/flutter ( 3188): #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
I/flutter ( 3188): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
I/flutter ( 3188): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter ( 3188): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
I/flutter ( 3188): #10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
I/flutter ( 3188): #11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
I/flutter ( 3188): #12     intListStreamToUint8ListStream.<anonymous closure> (package:sembast/src/utils.dart:541:12)

Where the crash log jumps to this method (which line it appears to fail at is in capitals):

// 2.5 compatibility change
//
// TODO 2019/07/08 This could be removed once the stable API returns Uint8List everywhere
/// Tmp 2.5 compatibility change
Stream<Uint8List> intListStreamToUint8ListStream(Stream stream) {
  if (stream is Stream<Uint8List>) {
    return stream;
  } else if (stream is Stream<List<int>>) {
    return stream.transform(
        StreamTransformer<List<int>, Uint8List>.fromHandlers(
            handleData: (list, sink) {
      sink.add(Uint8List.fromList(list));  // !THIS IS WHERE IT APPEARS TO FAIL!
    }));
  } else {
    throw ArgumentError('Invalid stream type: ${stream.runtimeType}');
  }
}

Any ideas?

**Comment by alextekartik** [comment]
That's sounds like a corruption issue since it fails during utf8 conversion (i.e. converting the bytes to lines of string). Would it be possible to send me your database file?

**Comment by Lidgett** [comment]
Thanks for the speedy reply!  You are indeed correct.  I can't really send the file as it potentially has sensitive data.  However I can confirm that when I open the .db file as a text file, there are some "unique" characters, for example, 9�c)�J��d���i�;��*�9�8�ij{��F�;��*�9�8�ij{��F�;��*�9�8�ij.... and this goes on for a while.  The data before it and after it looks good.  So of course I'm taking this as my error, or at least the error of the data that was given to me, I hope you agree with this?
But I wonder if you could further help me with this issue.  What would be the recommended way to fix this issue if I can't get access to the db?  Without access, I can't wipe it, so I can't set up anything that will allow the user to clear the db if I discover this issue again (via code checks and UI interactions).
Also, I wonder if there is a prevention to this?  If the data isn't good, shouldn't if fail before adding it into the file?  Are there any recommendations you can share?

Thanks again, any help is appreciated.  If you require the db file I can send it personally to you (I'd have to remove some info out of it obviously), but I can't really attach it here.

**Comment by alextekartik** [comment]
> I can't really send the file as it potentially has sensitive data

I understand you cannot attach it here. If you can at least send me a part of (some lines before and some lines after) to my personal email (alex@tekartik.com) that would be great.
Also if you can tell me whether you encountered this on iOS or Android, the size of file or whether your storage (internal? external?) was full that would be good information.

> So of course I'm taking this as my error, or at least the error of the data that was given to me, I hope you agree with this?

Well that should not happen. input data is sanitized and json encoded before writing. So no that is not your error!

> What would be the recommended way to fix this issue

That is what I want to figure out or at least provide a way for resolution (ignore corrupted data, wipe data, report error...).

> Also, I wonder if there is a prevention to this? If the data isn't good, shouldn't if fail before adding it into the file?

As I said that should not happen. If you have some info on the schema you are using (well there is no schema per say but the store typically has a key and data type)

> Are there any recommendations you can share?

Personally I use sembast_sqflite on flutter/dartvm and sembast_idb on flutter web so I that I can ensure data corruption is not on my side but that does not mean this should not be fixed for what I call "sembast io"

**Comment by alextekartik** [comment]
I finally tackle this issue. Indeed utf8 converter was simply failing, discarding the whole file. It does not explain why the corruption happened (if it was during development, hot reload/restart could in edge cases corrupt data).

I published a dev version - i.e. you have to explicitly make `sembast: '>=2.4.7-dev.1'` to try it.

I would appreciate if you can tell me if that fixes your issue. Thanks in advance!

**Comment by vinnytwice** [comment]
@alextekartik Hi, could it be the reason why after saving the UintList `Image.memory()` doesn't show the image or reading it?
I print the List before saving( when picking the image) and when loading it from db and they seem identical.. I tried json   coding/decoding it but I see reading above that that's automatically done, that's explains that I have no difference in the prints with or without encoding..
Would you rather me opening a new issue for my case?
Thanks

**Comment by vinnytwice** [comment]
@alextekartik ok..found the problem .. sembast ani't supporting Uint8List at all.. base64 coding/decoding does the trick dough. So reading the above confused me a bit.. is it due to support Uint8List?
Thanks again.

**Comment by alextekartik** [comment]
@vinnytwice Yes that is a different issue. Uint8List is supported in sembast using [Blob](https://pub.dev/documentation/sembast/latest/sembast_blob/Blob-class.html). I definitely don't recommend storing big blob in sembast as big data killls loading time. Consider saving to an external file and only keep a reference in the database.

Inside the database record stored on the disk, blob is base64 encoded which is not super performance/space efficient.

The original issue was about some invalid data in a sembast io file which in theory should not happen but well...it happened.

**Comment by vinnytwice** [comment]
@alextekartik I see. so base64encode(imageData) is kinda the same as Blob(imageData)? Thanks for the performance tip. I'll look into it.

**Comment by alextekartik** [comment]
> so base64encode(imageData) is kinda the same as Blob(imageData)? 

Correct

**Comment by Lidgett** [comment]
Thanks for sorting the issue Alex.  It does appear to be fine now.  I will keep testing and if something arises I'll let you know straight away.

For anyone else interested, I'm pretty certain this error is due to hot reload, and really hot reload only when certain circumstances are met (I say this because replicating it has been pretty difficult but I have achieved it once since).  The exact way to do it is still unknown however, I may find the answer soon.  
I'd like to note for anyone keeping an eye on this, this isn't something this package is at fault for, it's a consequence of other actions out of it's control.  However measures have now been put in place to ensure it can recover correctly if this ever does happen for what ever reason.  

So once again thanks for the package and all the hard work supporting it!  Keep it up.
