### ISSUE TITLE
Unique or Distinct data of particular column 

### ISSUE THREAD

**Issue by VarmaTech** [tekartik/sembast.dart#188]
i have category column in which there are repeated names but i need unique or distinct values of those
 can any one guide to achieve it .

**Comment by alextekartik** [comment]
I'm not sure what you mean by unique but you can get the distinct values of a column using something like this (here the column `name`):
```dart
var distinctNames = Set<String>.from(
        (await store.find(db)).map((snapshot) => snapshot['name'] as String));
```

**Comment by VarmaTech** [comment]
thanks a lot , it worked . this what i am looking for .

**Comment by sooryaraj** [comment]
```
 Future<List<MessageObj>> getAllMessages() async {
    final recordSnapshot = await _messageFolder.find(await _db);

    var getRocord = recordSnapshot.map((snapshot) {
      final messages = MessageObj.fromJson(snapshot.value);
      return messages;
    }).toList();
  }
```

how can i return unique message

**Comment by alextekartik** [comment]
@sooryaraj You might open a new issue as I'm not sure I understand what you mean by unique message. If you mean "single" message, you can use `findFirst` instead of `find` or you can access a record by key using `store.record(key).get(db)`
