### ISSUE TITLE
[web] can't open database on release flutter build web

### ISSUE THREAD

**Issue by ductranit** [tekartik/sembast.dart#195]
I'm having a trouble with the open database with `flutter build web` (it works fine on debug)
Here is my code (I print log to see which line has error)
```
print('open db');
try{
    var db = await databaseFactoryWeb.openDatabase('notes.db');
}
print('opened db ');
```

Here is the web console
```
open db
Uncaught Error: undefined js_helper.dart:1129:36
d js_helper.dart:1129
    $0 async_patch.dart:706
    b8K schedule_microtask.dart:41
    b93 schedule_microtask.dart:50
    $1 async_patch.dart:49
    bb0 js_helper.dart:1825
    s main.dart.js:2438
```

Flutter doctor:
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)
```
I also tried the dev version `2.4.7-dev.2` but it has same error.
I'm not sure whether it causes by the new flutter version (I tested on both master and beta channel), as I worked for me before.

p/s: if I put a try catch into `databaseFactoryWeb.openDatabase`
```
try {
        var db = await databaseFactoryWeb.openDatabase('notes.db');
      } catch (error, stack) {
        print(error);
        print(stack);
      }
```
then it shows the following error
```
Instance of 'minified:aJ'
<empty string>
```

**Comment by alextekartik** [comment]
Thanks for the report. Puzzling indeed. Does it happen for the notepad_sembast example: https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast (`flutter create . ; flutter run -d chrome`)?

I just checked that is working fine with the latest flutter beta.

What you can try (especially when switching channel or upgrading flutter):
- flutter clean
- flutter pub upgrade

And for sake of testing with a clean database:
- try in chrome incognito window

**Comment by ductranit** [comment]
You're right. It's the cache issue. It works after I run `flutter clean ` & `flutter pub upgrade`
I must think about this one in the first place.

**Comment by ductranit** [comment]
I can confirm this issue still happens on Firefox. 
I tried:
- `flutter clean`
- `flutter pub upgrade`
- clear Firefox data
- run in private window.

```
open db
Uncaught Error: undefined js_helper.dart:1129:36
    d js_helper.dart:1129
    $0 async_patch.dart:706
    b7D schedule_microtask.dart:41
    b7X schedule_microtask.dart:50
    $1 async_patch.dart:49
    b9U js_helper.dart:1825
    s main.dart.js:2430
```

The same error on your demo site https://alextekartik.github.io/flutter_app_example/notepad_sembast in Firefox

**Comment by alextekartik** [comment]
Thanks for the report.
As far as I know, IndexedDB is not supported in Firefox private mode (and any sites using indexedDB failed in this mode). Since sembast_web relies on it (and there is really no acceptable alternative on the web), it won't work. Sorry but I don't see any solution for this scenario. It should however work in Safari private mode and Chrome incognito mode.

**Comment by ductranit** [comment]
Ok, I find [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1639542) is working in progress .
Let's come back when it's ready
