### ISSUE TITLE
[web] stuck at insert multiple records in multiple async

### ISSUE THREAD

**Issue by ductranit** [tekartik/sembast.dart#196]
I have about 10 tables and I want to write data into sembast at the same time with `Future.wait`
```
var tasks = List<Future>();
for (var table in tables) {
      tasks.add(_syncTable(table);
}

await Future.wait(tasks);
print('completed');
```
And in the sync table method, I write records one by one:
```
Future<void> _syncTable(String table) {
     // ...get data for table from server...
    var listDocs = await getData(table);
    for(var doc in listDocs) {
       var index = listDocs.indexOf(doc);
        await _saveMap(table, doc["id"], doc, index);
   }

   print('sync table $table completed');
}

Future<void> saveMap(String tableName, String id, Map map, int index) {
    final db = _db[tableName];
    final store = Sembast.StoreRef.main();

    print('[start putting record $tableName $id at {$index}]');
    await store.record(id).put(db, map);  // STUCK at this line
    print('[end putting record $tableName $id at {$index}]'); // never reach this line
}

```
The line `await store.record(id).put(db, map);` is stuck at some position and it can't go to next record.
This problem doesn't happen for all, just for some random table (_syncTable method). For example, the table B has 400 records, but it stop putting at index 67, table C has 100 records and stop putting at index 44 and the rest of tables are completed.
This issue happens on `build web release` in Safari macos and ios devices. Sometime my client report the same issue in Chrome but I can't reproduce it.
Do you have any suggestion to deal with the threading on sembast?

 My flutter doctor
```
[✓] Flutter (Channel master, 1.20.0-3.0.pre.130, on Mac OS X 10.15.4 19E287, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 4.0)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by alextekartik** [comment]
> I have about 10 tables

It sounds more like you have 10 databases instead of 10 tables. In sembast a store (and there can be multiples stores in a database) is similar to a table in SQL world). But that is just a naming convention.

> And in the sync table method, I write records one by one

You should use a transaction to add multiple records. Adding records one by one will trigger too many notifications (that could explain partially the 'stuck')

> The line await store.record(id).put(db, map); is stuck at some position and it can't go to next record

Maybe an exception is thrown and you are not stuck. How can you tell in release mode that you are stuck with just a print? Are you catching the exception to see if anything went worng?

You should definitely use pedantic, strong mode and types the store you are using - i.e. not StoreRef.main() but StoreRef<String, Map<String, dynamic>() - it should help tracking issues if any in the typing.

My 2 recommendation would lead to something similar to this:
```dart
Future<void> _syncTable(String table) async {
  // ...get data for table from server...
  var listDocs = await getData(table);

  // Get the proper database
  final db = _db[table];
  // Enforce type: key is String, data is Map (StoreRef<String, Map<String, dynamic>)
  // Use the main store of the database
  final store = stringMapStoreFactory.store();

  try {
    print('start sync table $table (${listDocs.length} items)');
    await db.transaction((txn) async {
      for (var doc in listDocs) {
        var id = doc['id'];
        await store.record(id).put(txn, doc);
      }
    });
  } catch (e) {
    // Print failure if any
    print('failure $e');
  }

  print('sync table $table completed');
}
```

**Comment by alextekartik** [comment]
To see the transaction benefit you can try the following test program: https://notelio.surge.sh
See if the difference if you choose from the top right menu:
- add 100 records
- add 100 records (no txn)

In the first case, the list (using query.onSnapshots) is refreshed once, while in the second case, it is refreshed for each record added.

**Comment by ductranit** [comment]
@alextekartik thank you so much. It works great with the transaction
I must read the document in detail before doing stuff like that.
