### ISSUE TITLE
Filtering/Querying by multiple fields

### ISSUE THREAD

**Issue by DevilWarrior** [tekartik/sembast.dart#20]
Can someone point me to the correct way to filter by multiple fields? For example:

Give this data previously stored:

```
{
  'timestamp': '6846876879',
  'type: 'message'
  'address: '+1 789 789 7788',
  'message: 'ABC'
}
```

I would like to filter/query entries that are `{'type': 'message', 'address': '+1 789 789 7788'}`

**Comment by alextekartik** [comment]
You can do it this way:

```dart
await db.findRecords(Finder(
      filter: Filter.and([
    Filter.equals('type', 'message'),
    Filter.equals('address', '+1 789 789 7788')
  ])));
```

**Comment by kururu-abdo** [comment]
how to use LIKE operator ?

**Comment by alextekartik** [comment]
> how to use LIKE operator ?

I'm not sure how this is related with the orginal issue. You might better ask StackOverflow or create a new issue if you don't manage using[`Filter.matchesRegExp`](https://pub.dev/documentation/sembast/latest/sembast/Filter/Filter.matchesRegExp.html) or just [`Filter.custom`](https://pub.dev/documentation/sembast/latest/sembast/Filter/Filter.custom.html).

See the doc [here](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/queries.md#filtering-using-regexp-patten) where it can mimic what you would expect with SQL LIKE operator.
