### ISSUE TITLE
FileSystemException when opening database in iOS

### ISSUE THREAD

**Issue by edsonboldrini** [tekartik/sembast.dart#203]
In Android works smoothly but when I ask to open the sembast in iOS, it prompts this exception to me:
```
Unhandled Exception: FileSystemException: Cannot create file, path = '/var/mobile/Containers/Data/Application/8BD98777-6A5B-4F07-B327-97029A686E08/Documentssembast.db' (OS Error: Operation not permitted, errno = 1)
```
My code:
![image](https://user-images.githubusercontent.com/31242886/88717462-f9d15800-d0f6-11ea-8b0e-f2b2e53d57de.png)

**Comment by alextekartik** [comment]
It seems you are trying to create a document named `Documentssembast.db` in `/var/mobile/Containers/Data/Application/8BD98777-6A5B-4F07-B327-97029A686E08/` where you might not have write access.

You could try to simply use:
```dart
// Use relative path to getDatabasesPath()
var dbPath = 'sembast.db';
```

or
```dart
import 'package:path/path.dart'
// Use absolute path (but make sure the parent directory exists and that you have write access)
var dbPath = join(dir.path, 'sembast.db');
```

**Comment by edsonboldrini** [comment]
Understood, I'll try!
