### ISSUE TITLE
How to use sembast_web in cross-platform project

### ISSUE THREAD

**Issue by Pe-te** [tekartik/sembast.dart#204]
Are there any examples or tutorials how to support both the normal sembast on mobile apps (for now Android and iOS) and sembast_web on a webapp?

**Comment by alextekartik** [comment]
I'm not sure I have seen tutorials on sembast_web yet.

There is a simple package here: https://github.com/tekartik/app_flutter_utils.dart/tree/dart2/app_sembast that provides a convenient way to get a database factory to use on flutter web/desktop/mobile and the 2 samples using it:

* [Flutter counter template with added persistency](https://github.com/alextekartik/flutter_app_example/tree/master/demosembast) available, [online demo](https://alextekartik.github.io/flutter_app_example/demosembast)
* Basic [notepad using sembast](https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast) available, [online demo](https://alextekartik.github.io/flutter_app_example/notepad_sembast/)
