### ISSUE TITLE
Sorting using Firestore Timestamp does not work well yet

### ISSUE THREAD

**Issue by zenkog** [tekartik/sembast.dart#205]
I have a listener to a record list in local database like this:
```
final sortOrder = SortOrder(date, false);
final finder = Finder(sortOrders: [sortOrder]);
      
// Subscribe to local DB record
_subscription = itemStore
          .query(finder: finder)
          .onSnapshots(db)
          .distinct()
          .listen((_) {});

_subscription.onData(_displayData);
```

Then on one occasion I updated a field in one of the data like this:
```
final updateData = {someValue: '1234'};
await itemStore.record(key).update(db, updateData);
```

Then when I come back to the list, I found that the updated data has moved to different position in the list. This is strange because there was no change to the `date` field that supposed to be used for sorting and I have made sure of this by printing them out.

Moreover, `date` is a Firestore Timestamp object. 
I'm using `sembastFirestoreCodec` created by @alextekartik which can be found [here](https://github.com/tekartik/sembast.dart/issues/149#issuecomment-619391297)

**Comment by zenkog** [comment]
So I discovered that the problem is due to the sorting using a field that is a Firestore Timestamp object. 
When I sort the list again using :
```
items.sort((a, b) => b.date.compareTo(a.date));
```

This resorts the list again correctly. 

So probably we need a way to map the Firestore's Timestamp to Sembast's Timestamp or else we need to convert it all to `milliseconds`

**Comment by alextekartik** [comment]
I see. Thanks for the report, I need to check indeed that custom object are correctly ordered (assuming they implements Comparable which is the case here).

**Comment by alextekartik** [comment]
There was actually a general bug in initial onSnapshots ordering. This should be fixed in sembast 2.4.7+5 just published. Can you check that it fixes your issue?

**Comment by zenkog** [comment]
It works!! Thank you @alextekartik !!

**Comment by zenkog** [comment]
Sorry, I just found same related bug when doing:
`findFirst` and probably `find` as well.

Maybe I reopen the issue?

**Comment by alextekartik** [comment]
This should be fixed too (maybe in 2.4.7+6). Can you reproduce your issue in a simple unit test or give more information on how to reproduce the issue? thanks!

**Comment by zenkog** [comment]
I'm sorry it's been a crazy week for me

How to reproduce:
1. Store data from Firestore that has a Timestamp document field into local database using Sembast:
```
 // Create the list of keys: id
final List<String> keys =
              snapshots.documents.map((snapshot) => snapshot.documentID).toList();
// Create the list of data: data
final List<Map<String, dynamic>> data = snapshots.documents
              .map((snapshot) => ItemDB.fromDocumentSnapshotToMap(snapshot)
              .toList();

// Insert into local DB
db.transaction((txn) => storeRef.records(keys).put(txn, data));
```

2. Then query from local like this:
```
final sortOrder = SortOrder(updatedDate, false);
final finder = Finder(sortOrders: [sortOrder]);

final latestUpdatedData = await storeRef.findFirst(db, finder: finder);
```

But the query above does not return the latest updated data because the sorting is not working properly when I use `findFirst` and I have tried `find` also the same result.

**Comment by alextekartik** [comment]
For confirmation, are you properly 'awaiting' your put transaction before reading?
