### ISSUE TITLE
[web] Uncaught SyntaxError: Unexpected token '|' where call some method!

### ISSUE THREAD

**Issue by lyf571321556** [tekartik/sembast.dart#211]
plugin:
sembast: ^2.4.7+6
sembast_web: ^1.2.0
when i call some code jusk like below:
await _store.delete(dbClinet);
or
await _store.update(dbClinet);

tow of them produced same error.

i had post a ussue to flutter and dart  too! 
https://github.com/flutter/flutter/issues/63546
https://github.com/dart-lang/sdk/issues/43014

have some sugesstion to avoid this error?
thanks.

**Comment by alextekartik** [comment]
I think this issue is related to: https://github.com/dart-lang/sdk/issues/42712

There is an issue in dart2js compiler which is now fixed in beta but not dev and master yet. Can you confirm it happens on the beta channel too?
