### ISSUE TITLE
Unable to open database from sql lite browser.

### ISSUE THREAD

**Issue by saravananmnm** [tekartik/sembast.dart#215]
How to view the stored the data's manually, like realm studio browser?
is it possible?

[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18362.1016], locale en-IN)
    • Flutter version 1.20.2 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision bbfbf1770c (3 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Genymotion 9 0 New (mobile) • 192.168.241.101:5555 • android-x86 • Android 9 (API 28)

• No issues found!

**Comment by saravananmnm** [comment]
any solution?

**Comment by alextekartik** [comment]
sembast is not a SQL file so you cannot open using sqlite browser (unless you use sembast_sqflite). There is no solution I am aware of (but the format is plain json).
