### ISSUE TITLE
Two Flutter (Android) apps, one Sembast DB

### ISSUE THREAD

**Issue by natgross** [tekartik/sembast.dart#218]
Although Sembast DB is not designed for two apps to simultaneously use the same db (stored in an external Android folder), nevertheless is it possible to do so IF one app only reads, and will never write?
Can I consider it safe in such a scenario? If the app that is writing uses transactions, would it help?
tnx.

**Comment by natgross** [comment]
Woa! I just bumped into your sembast_sqflite pkg! Does this use the exact same api calls as Sembast? Is it simply a technical implementation where you use sqlite instead of ram? Does this also mean that my app(s) that enjoy the use of Sembast will work as-is simply by using sembast_sqflite instead of plain sembast?
I have built an entire framework around Sembast, so I don't want to start using good old sql which I have not touched for almost a decade now.

**Comment by alextekartik** [comment]
Standard sembast io is not cross isolate/process safe. There can be only one reader/writer.

sembast_sqlite is cross process safe (but not cross isolate safe which should not matter as you should always use sembast in the main isolate). It still loads the content in memory but uses sqflite as its backend storage. The API is the same, you only need to use a different factory to open the database.

It you compile https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast for the desktop, you can start multiple instances of an app on the desktop (mac/linux/windows). While the content will not refresh in real time in both apps, you can add an item in one instance and when you add an item in another instance, both should appear.

**Comment by natgross** [comment]
Thanks for the clarification.
