### ISSUE TITLE
Database closed exception, when i try to open its getting database is closed error.

### ISSUE THREAD

**Issue by saravananmnm** [tekartik/sembast.dart#219]
When user logged out, by that time close the database and delete the entire database. Thereafter try to open the database when user logged in. It's getting closed exception.

How we can solve this issue.?

`class Storage {
  Database _database;

  Storage() {
    openDB();
  }

  Future<Database> openDB() async {
    if (_database == null) {
      _database = await _openDatabase();
    }
    return _database;
  }

  Future closeDataBase() async {
    return await _database.close();
  }

  Future deleteDataBase() async {
    await closeDataBase();
    return await databaseFactoryIo.deleteDatabase(await getDBPath());
  }

  Future getDBPath() async {
    final appDocumentDir = await getApplicationDocumentsDirectory();
    final dbPath = join(appDocumentDir.path, 'wdsi.db');
    return dbPath;
  }

  Future _openDatabase() async {
    final database = await databaseFactoryIo.openDatabase(await getDBPath());
    return database;
  }
}`

**Comment by alextekartik** [comment]
Dealing with open/closing database exposes to this kind of issue. In your example, maybe try to set _database to null when you close the database

**Comment by 926** [comment]
Tekartiks seems to recommend to open the .db only once, when app launches and then provide the database across  services.  

There is an example here with bloc : 

- https://github.com/alextekartik/flutter_app_example/blob/master/demo_sembast/lib/main.dart

There is another example In the notepad repo, where no other state management package is used but tekartikspeak : 

- https://github.com/alextekartik/flutter_app_example/blob/master/notepad_sembast/lib/provider/note_provider.dart

My assumption is that closing the .db is a used for testing or in exceptional use case.
