### ISSUE TITLE
Update issues

### ISSUE THREAD

**Issue by phillwiggins** [tekartik/sembast.dart#22]
Hey

Before I start, amazing work! This library works really well.

I'm struggling somewhat with my updates though. I've tried a few ways and it us probably me being dumb. I have successfully created a local repository that can add, get, delete. I seem to be stuck on update though and cannot figure out if it's the way I am doing things?

Here is how I successfully store a record:-

`
@override
  Future<ApiResponse> add(UserFood item) async {
    final Map<String, dynamic> values = convertItemToStorageMap(item);
    final Record recordToAdd = Record(_store, values, item.objectId);
    final Record recordFromDB = await _db.putRecord(recordToAdd);
    return ApiResponse(true, 200, convertRecordToItem(recordFromDB), null);
  }
`

As you can see I am storing an object as a map, using the objectId as a key to store my record to be retrieved. 

Here is how I get:-

`
@override
  Future<ApiResponse> getById(String id) async {
    final Record record = await _store.getRecord(id);
    if (record != null) {
      final UserFood userFood = convertRecordToItem(record);
      return ApiResponse(true, 200, userFood, null);
    } else {
      return errorResponse;
    }
  }
`

Now the issue seems to be with update, I have tried this in similar ways but cannot figure this out. I have tried using _db.update, and _store update but both just do not work.

'@override
  Future<ApiResponse> update(UserFood item) async {
    final Map<String, dynamic> values = convertItemToStorageMap(item);
    final Record recordToUpdate = Record(_store, values, item.objectId);
    final Record recordFromDb = await _db.update(recordToUpdate, item.objectId);

    if (recordFromDb == null) {
      return errorResponse;
    }

    return ApiResponse(true, 200, recordFromDb.value, null);
  }'

It either returns null or that it cannot find the record. Is update suppose to return null or return the value you have tried to store?

**Comment by alextekartik** [comment]
Sometimes the API is a pain, too many `dynamic` arguments that are error-prone. In you case I think the mistake is here:

```dart
final Map<String, dynamic> values = convertItemToStorageMap(item);
final Record recordToUpdate = Record(_store, values, item.objectId);
final Record recordFromDb = await _db.update(recordToUpdate, item.objectId);
```

Calling `update` on the database updates a record in the 'main' store which is not what you want (and it returns null since the record only exist in another - i will guess named food - store). Also `update` expect a value, not a record so you should do (no need to use a record here):

```dart
final Map<String, dynamic> values = convertItemToStorageMap(item);
values = await _store.update(values, item.objectId)
```

`update` returns the value merged or null if not found. You might say, hey there is no updateRecord. I wanted to add it but I'm working on a better API (the exisiting will remain) to access the data.

**Comment by phillwiggins** [comment]
Amazing, that worked thanks!

I appreciate the quick response. While I have your attention, another quick on to check. I'm adding an item to the DB then calling remove. When I check my .db file I see that there is 2 entries, both the same entry but one has the value delete attached to it. This seems to causing issues as I essentially have a deleted version of the item and a none deleted. Is this correct?

**Comment by alextekartik** [comment]
Yes that is actually normal. It might sounds weird but writes are optimized to only 'append' to an existing file. Database will eventually get compacted at any time using some predefined rules (at least 5 records and 20% obsolete lines) and then both lines will be removed. I will try to write down the details of the implementation at some point...

**Comment by phillwiggins** [comment]
Thank you. 

I was unit testing a local repository class that is using Sembast that looked something like this:-

`test('delete UserFood from DB', () async {
    // Given
    final UserFood actual = _getMockFoodItem();
    await repository.add(actual);

    // When
    await repository.remove(actual);
    final ApiResponse response = await repository.getById(actual.objectId);

    // Then
    expect(response.result == null, true);
  });`

So your saying that this is correct and due to then clean up process not yet taking place, this would fail? If that's correct, that's fine.

**Comment by alextekartik** [comment]
(I edited your post which was hard to read, sorry).
No this test (if the implementation is correct) should succeed. Trying to get a deleted record should return null

**Comment by phillwiggins** [comment]
No worries, apologies, I just couldn't format that correctly for some reason.

Right, strange. My implementation must be incorrect then. When I called getById, it still returns a non null object.

My implementation looks like this, and called in this order:-

**Add**
```
@override
  Future<ApiResponse> add(UserFood item) async {
    final Map<String, dynamic> values = convertItemToStorageMap(item);
    final Record recordToAdd = Record(_store, values, item.objectId);
    final Record recordFromDB = await _db.putRecord(recordToAdd);
    return ApiResponse(
        true, 200, convertRecordToItem(record: recordFromDB), null);
  }
```

**Remove**
```
@override
  Future<ApiResponse> remove(UserFood item) async {
    await _db.delete(item.objectId);
    return ApiResponse(true, 200, null, null);
  }
```

**GetById**
```
@override
  Future<ApiResponse> getById(String id) async {
    final Record record = await _store.getRecord(id);
    if (record != null && record.deleted != null || record.deleted == false) {
      final UserFood userFood = convertRecordToItem(record: record);
      return ApiResponse(true, 200, userFood, null);
    } else {
      return errorResponse;
    }
  }
```

This is the order my unit test works in, all of it is called via async/await so it shouldn't be race conditions but for some reason, getById will still find the correct record. In my tests, my setup and teardown clear the db and recreate it every time too.

**Comment by alextekartik** [comment]
You are making the same mistate for remove.

This remove the item in the main store:
```dart
await _db.delete(item.objectId);
```
It should be:
```dart
await _store.delete(item.objectId);
```

**Comment by phillwiggins** [comment]
I'm an idiot!

I tried that earlier but due to a different error on my implementation, I
assumed the above was the issue.

All sorted and working really well. Thank you so much for this library and
your help!
