### ISSUE TITLE
"Invalid argument" error only within sembast-web

### ISSUE THREAD

**Issue by michaelyfan** [tekartik/sembast.dart#221]
Hello. Any help is appreciated.

I recently migrated my Flutter project to web. This included upgrading Sembast to use `sembast-web`. Here is my setup:

```
import 'package:sembast/sembast.dart';
import 'package:sembast_web/sembast_web.dart';
```

Here are my sembast versions--I deleted `pubspec.lock`, ran `flutter clean`, then did a `flutter pub get`:
```
  sembast: ^2.4.7+7
  sembast_web: ^1.2.0
```

However, though my code builds and runs and a webpage opens, this function leads to a Sembast-related error (the erroring line is indicated):

```
Future<void> functionName(List<MyClass> objects) async {
  StoreRef store = stringMapStoreFactory.store();
  var factory = databaseFactoryWeb;
  var db = await factory.openDatabase('db1');
  Database localDb = await getLocalDb();

  List<Map<String, dynamic>> toAdd = objects
    .map((MyClass object) => object.convertToMap())
    .toList();

  return store.delete(localDb).then((int n) {
    return store.addAll(localDb, toAdd ); // this line causes the error
  });
}
```

The error I receive is:
```
Invalid argument: type MappedListIterable<String, Map<String, String>> not supported: Instance of 'MappedListIterable<String, Map<String, String>>'
```
The full error text can be found here: https://www.codepile.net/pile/WR9bVM72

Similar code before I migrated my Flutter project to web works without any problems. In migrating to web, I only changed the database factory (`databaseFactoryWeb`), but didn't change how I was interacting with data in the database.

Any idea what's happening? I'm aware that `.map` returns `MappedListIterable`, but `.toList()` should have turned it into a `List<>`. I assume `store.addAll` only takes `List<>` for its second parameter. I wonder if Sembast is doing anything I'm not expecting? 

Thanks in advance.

**Comment by alextekartik** [comment]
Thanks for the report. Your assumption is correct. `toList()` is needed in your case and fine.

My guess is that `MyClass.convertToMap()` is doing something wrong (likely a call to `map()` without a `toList()` but I could be wrong). What puzzled me is that it should also fail in a non web scenario also but you say it is not the case. Would you mind sharing your implementation `MyClass.convertToMap()` of so I can take a deeper look.

The behavior is similar to json encoding (unless you are using custom type like blob and timestamp). So calling jsonEncode on you convertToMap result should also fail.

**Comment by michaelyfan** [comment]
@alextekartik,
I figured it out, turned out to be my mistake. Yes, you were right that `convertToMap()` was making a call to `map()` without `toList()`, which was causing the error.

The reason why it wasn't happening in a non-web scenario is because, I realized, part of my web migration was upgrading my `sembast` version. When I went back to the non-web branch and updated `sembast` it worked as intended. 

So, mostly my fault. We now know though that this error won't show up in `sembast` 2.1 even if data is malformed. You can close this!
