### ISSUE TITLE
Delete is not working local db

### ISSUE THREAD

**Issue by saravananmnm** [tekartik/sembast.dart#222]
I have deleted some records from particular store. But it showing still some records.

{"version":1,"sembast":1}
{"key":1,"store":"savedOrderDetails","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"uploadStatus":1}}
{"key":2,"store":"savedOrderDetails","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"uploadStatus":1}}
{"key":3,"store":"savedOrderDetails","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"uploadStatus":1}}
{"key":4,"store":"savedOrderDetails","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"uploadStatus":1}}
{"key":1,"deleted":true,"store":"savedOrderDetails"}
{"key":2,"deleted":true,"store":"savedOrderDetails"}
{"key":3,"deleted":true,"store":"savedOrderDetails"}
{"key":4,"deleted":true,"store":"savedOrderDetails"}

**Comment by alextekartik** [comment]
Some explanation on the storage format and how it workds are available here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md
