### ISSUE TITLE
Filter AND is not working with Finder  its getting exception

### ISSUE THREAD

**Issue by saravananmnm** [tekartik/sembast.dart#223]
`
  Future<PobPodDetailsModel> getOrderByStatusId(
      String orderId, String statusId) async {
    PobPodDetailsModel model;
    var db = await storage.openDB();
    List<Filter> fd = [];
    fd.add(Filter.equals('orderId', orderId));
    fd.add(Filter.equals('statusId', statusId));
    var finder = Finder(filter: Filter.and(fd));
    await savedOrdersDetailsStore.find(db, finder: finder).then((data) {
      if(data!=null){
        for (var items in data){
          model = PobPodDetailsModelSerializer().fromMap(items.value);
        }
      }
    }).catchError(() {
      model=new PobPodDetailsModel();
    });
    return model;
  }`

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments, and return a a valid result: Closure: () => Null
E/flutter (20781): #0      _registerErrorHandler (dart:async/future_impl.dart:828:3)
E/flutter (20781): #1      Future.catchError (dart:async/future_impl.dart:308:17)
E/flutter (20781): #2      SaveOrdersDetailsDAO.getOrderByStatusId (package:courier_alliance/src/localprovider/savedordersdetailsdao.dart:66:8)
E/flutter (20781): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (20781): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (20781): #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (20781): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (20781): #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (20781): #8      Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
E/flutter (20781): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (20781): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20781): #11     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (20781): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (20781): #13     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (20781): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (20781):

**Comment by alextekartik** [comment]
I'm not sure the exception come from sembast but I could be wrong. The error seems to be in how you use catchError. I think the function takes at least on parameter: `catchError((error) ...`

Personnally I avoid catchError (since it does not catch synchronous error) and use regular try/catch with await.

More information here: https://dart.dev/guides/libraries/futures-error-handling
