### ISSUE TITLE
DB record override, when i insert new records.

### ISSUE THREAD

**Issue by saravananmnm** [tekartik/sembast.dart#230]
I have used latest sembast db version 2.4.8+1

`Future<bool> saveOrdersDetails(PobPodDetailsModel model) async {
    var db = await storage.openDB();
    await db.transaction((txn) async {
      var key = await savedOrdersDetailsStore.add(
          txn, PobPodDetailsModelSerializer().toMap(model));
      savedOrdersDetailsStore.record(key);
    }).catchError((e) {
      return false;
    });
    print('table rows inserted');
    return true;
  }`

In the above code is insert the new records. But it will updated all the records as like new one inserted.
How we can solve this insertion.?

`class Storage {
  Database _database;
  Completer<Database> _dbOpenCompleter;

  Storage() {
    openDB();
  }

  Future<Database> openDB() async {
    if (_dbOpenCompleter == null) {
      _dbOpenCompleter = Completer();
      // Calling _openDatabase will also complete the completer with database instance
      _openDatabase();
    }
    // If the database is already opened, awaiting the future will happen instantly.
    // Otherwise, awaiting the returned future will take some time - until complete() is called
    // on the Completer in _openDatabase() below.
    return _dbOpenCompleter.future;
  }

  Future closeDataBase() async {
    return await _database.close();
  }

  Future deleteDataBase() async {
    await closeDataBase();
    return await databaseFactoryIo.deleteDatabase(await getDBPath());
  }

  Future getDBPath() async {
    final appDocumentDir = await getApplicationDocumentsDirectory();
    final dbPath = join(appDocumentDir.path, 'wdsi.db');
    return dbPath;
  }

  Future _openDatabase() async {
    _database = await databaseFactoryIo.openDatabase(await getDBPath());
    // Any code awaiting the Completer's future will now start executing
    _dbOpenCompleter.complete(_database);
  }
}`

{"version":1,"sembast":1}
{"key":2,"store":"ordersMaster","value":{"orderId":"CA000002504","noOfParcels":10,"orderStatus":"Assigned","orderStatusCode":"ASIG","orderStatusId":"STY8","vehicleType":"Bicycle","vehicleTypeId":null,"totalDistance":62.19552789186,"entityId":"EN19","entityName":"Toms Logistics","accountId":null,"accountName":null,"serviceTypeId":null,"creationDateTime":null,"pickUpDateTime":"2020-12-29T23:00:00Z","deliverDateTime":"2020-12-31T10:00:00Z","orderNotes":null,"cancellationReason":null,"collectionContact":"","collectionPhoneNumber":"","collectionLatitude":9.6924703,"collectionLongitude":78.4523366,"collectionNotes":"I haven’t tried yet, but I think it works with iOS devices because we just make HTTP POST request to Firebase Server, then it will send Notification to devices which have subscribed TOPIC.","collectionAddress":"Manamadurai Police Station, Tamil Nadu 641009, India","deliveryContact":"","deliveryPhoneNumber":"","deliveryLatitude":11.3469297,"deliveryLongitude":77.71945769999999,"deliveryNotes":"Added new Cast Receiver SDK for Android TV apps. The SDK allows Android TV apps to be compliant to the Cast protocol so that they behave as Receiver apps. For details, refer to the Cast Android Sender SDK Release Notes.","deliveryAddress":"1154, Mettur Rd, Municipal Colony, Edayankattuvalasu, Erode, Tamil Nadu 638011, India","winningBid":"320.00","currencyCode":"INR","systemReference":"TEST SARO","customerReference2":"","customerReference3":"","customerReference4":"","customerReference1":"reff","collectBy":null,"deliverBy":null,"orderGroupId":null,"mUserID":"USER51","orderUploadsStatus":2,"pobParcels":11}}
{"key":3,"store":"ordersMaster","value":{"orderId":"CA000002503","noOfParcels":10,"orderStatus":"Assigned","orderStatusCode":"ASIG","orderStatusId":"STY7","vehicleType":"Bicycle","vehicleTypeId":null,"totalDistance":62.19552789186,"entityId":"EN19","entityName":"Toms Logistics","accountId":null,"accountName":null,"serviceTypeId":null,"creationDateTime":null,"pickUpDateTime":"2020-12-29T23:00:00Z","deliverDateTime":"2020-12-31T10:00:00Z","orderNotes":null,"cancellationReason":null,"collectionContact":"","collectionPhoneNumber":"","collectionLatitude":9.6924703,"collectionLongitude":78.4523366,"collectionNotes":"I haven’t tried yet, but I think it works with iOS devices because we just make HTTP POST request to Firebase Server, then it will send Notification to devices which have subscribed TOPIC.","collectionAddress":"Manamadurai Police Station, Tamil Nadu 641009, India","deliveryContact":"","deliveryPhoneNumber":"","deliveryLatitude":11.3469297,"deliveryLongitude":77.71945769999999,"deliveryNotes":"Added new Cast Receiver SDK for Android TV apps. The SDK allows Android TV apps to be compliant to the Cast protocol so that they behave as Receiver apps. For details, refer to the Cast Android Sender SDK Release Notes.","deliveryAddress":"1154, Mettur Rd, Municipal Colony, Edayankattuvalasu, Erode, Tamil Nadu 638011, India","winningBid":"320.00","currencyCode":"INR","systemReference":"TEST SARO","customerReference2":"","customerReference3":"","customerReference4":"","customerReference1":"reff","collectBy":null,"deliverBy":null,"orderGroupId":null,"mUserID":"USER51","orderUploadsStatus":2,"pobParcels":10}}
{"key":4,"store":"ordersMaster","value":{"orderId":"CA000002506","noOfParcels":1,"orderStatus":"Assigned","orderStatusCode":"ASIG","orderStatusId":"STY9","vehicleType":"Bicycle","vehicleTypeId":null,"totalDistance":103.79508631998,"entityId":"EN19","entityName":"Toms Logistics","accountId":null,"accountName":null,"serviceTypeId":null,"creationDateTime":null,"pickUpDateTime":"2020-12-30T00:00:00Z","deliverDateTime":"2020-12-31T00:00:00Z","orderNotes":null,"cancellationReason":null,"collectionContact":"","collectionPhoneNumber":"","collectionLatitude":11.664325,"collectionLongitude":78.1460142,"collectionNotes":"","collectionAddress":"Salem, Tamil Nadu, India","deliveryContact":"","deliveryPhoneNumber":"","deliveryLatitude":11.0168445,"deliveryLongitude":76.9558321,"deliveryNotes":"","deliveryAddress":"Coimbatore, Tamil Nadu, India","winningBid":"121.00","currencyCode":"INR","systemReference":"","customerReference2":"","customerReference3":"","customerReference4":"","customerReference1":"VTEST","collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","orderGroupId":null,"mUserID":"USER51","orderUploadsStatus":2,"pobParcels":1}}
{"key":"-MPhsthFpv7sUer6Z10N","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":"2020-12-29T13:55:56Z","arrivedAndDeliveryDateTime":"2020-12-29T14:32:43Z","pobComments":"","pobLatitude":null,"pobLongitude":null,"pobNoOfParcels":1,"pobSignature":"https://s3.us-west-2.amazonaws.com/images.iloads.in/Iex_Testing/CA000002502POB_1609230453123.png","pobSignedBy":"","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29T13:57:31Z","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":1,"collectBy":"2020-12-29T23:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY9","orderId":"CA000002502","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPhtBqFoT2R7xg44-t0","store":"savedOrderDetails","value":{"arrivedAndCollectionDateTime":"2020-12-29T13:55:56Z","arrivedAndDeliveryDateTime":"2020-12-29T14:32:43Z","pobComments":"","pobLatitude":null,"pobLongitude":null,"pobNoOfParcels":1,"pobSignature":"https://s3.us-west-2.amazonaws.com/images.iloads.in/Iex_Testing/CA000002502POB_1609230453123.png","pobSignedBy":"","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29T13:57:31Z","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":1,"collectBy":"2020-12-29T23:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY9","orderId":"CA000002502","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPhu0kpDjSnN8W9sZGq","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"pobComments":"","pobLatitude":9.8034583,"pobLongitude":78.4765433,"pobNoOfParcels":11,"pobSignature":"","pobSignedBy":" ","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29 15:27:51","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":null,"deliverBy":null,"collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY8","orderId":"CA000002504","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPhvksivQZufAJJFH6b","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"pobComments":"","pobLatitude":9.8034583,"pobLongitude":78.4765433,"pobNoOfParcels":11,"pobSignature":"","pobSignedBy":" ","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29 15:27:51","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":null,"deliverBy":null,"collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY8","orderId":"CA000002504","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi1W6-wqtofKbk7Wws","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":"2020-12-29 15:57:44","arrivedAndDeliveryDateTime":null,"pobComments":null,"pobLatitude":null,"pobLongitude":null,"pobNoOfParcels":null,"pobSignature":null,"pobSignedBy":null,"podSignature":null,"podDateTime":null,"pobDateTime":null,"podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":10,"collectBy":null,"deliverBy":null,"collectionLatitude":9.8034583,"collectionLongitude":78.4765433,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY7","orderId":"CA000002503","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi4QiltDLbzFjDTNHg","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"pobComments":"","pobLatitude":9.8034583,"pobLongitude":78.4765433,"pobNoOfParcels":1,"pobSignature":"","pobSignedBy":" ","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29 16:11:02","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY8","orderId":"CA000002506","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi4Z6YnHpIQCdSKTT4","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"pobComments":"","pobLatitude":9.8034583,"pobLongitude":78.4765433,"pobNoOfParcels":1,"pobSignature":"","pobSignedBy":" ","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29 16:11:02","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY8","orderId":"CA000002506","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi4gH02Rj1apjF_BQ2","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":null,"pobComments":"","pobLatitude":9.8034583,"pobLongitude":78.4765433,"pobNoOfParcels":1,"pobSignature":"","pobSignedBy":" ","podSignature":null,"podDateTime":null,"pobDateTime":"2020-12-29 16:11:02","podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":null,"deliveryLongitude":null,"statusId":"STY8","orderId":"CA000002506","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi4QiltDLbzFjDTNHg","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":"2020-12-29 16:11:36","pobComments":null,"pobLatitude":null,"pobLongitude":null,"pobNoOfParcels":1,"pobSignature":null,"pobSignedBy":null,"podSignature":null,"podDateTime":null,"pobDateTime":null,"podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":9.8034583,"deliveryLongitude":78.4765433,"statusId":"STY9","orderId":"CA000002506","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi4Z6YnHpIQCdSKTT4","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":"2020-12-29 16:11:36","pobComments":null,"pobLatitude":null,"pobLongitude":null,"pobNoOfParcels":1,"pobSignature":null,"pobSignedBy":null,"podSignature":null,"podDateTime":null,"pobDateTime":null,"podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":9.8034583,"deliveryLongitude":78.4765433,"statusId":"STY9","orderId":"CA000002506","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}
{"key":"-MPi4gH02Rj1apjF_BQ2","store":"**savedOrderDetails**","value":{"arrivedAndCollectionDateTime":null,"arrivedAndDeliveryDateTime":"2020-12-29 16:11:36","pobComments":null,"pobLatitude":null,"pobLongitude":null,"pobNoOfParcels":1,"pobSignature":null,"pobSignedBy":null,"podSignature":null,"podDateTime":null,"pobDateTime":null,"podLatitude":null,"podComments":null,"podLongitude":null,"podNoOfParcels":null,"podSignedBy":null,"noOfParcels":null,"collectBy":"2020-12-30T00:00:00Z","deliverBy":"2020-12-31T00:00:00Z","collectionLatitude":null,"collectionLongitude":null,"deliveryLatitude":9.8034583,"deliveryLongitude":78.4765433,"statusId":"STY9","orderId":"CA000002506","uploadStatus":1,"podCapturedImages":null,"unDeliveredComments":null,"reasonId":null}}

**Comment by saravananmnm** [comment]
C:\Saravanan\Flutter_Sdk\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19041.685], locale en-IN)
    • Flutter version 1.22.4 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision 1aafb3a8b9 (7 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.

**Comment by saravananmnm** [comment]
Any update on this issue?

**Comment by alextekartik** [comment]
I'm sorry I guess I did not understand what you are trying and what you expect. Do you have a unit test that could reproduce the issue in a simple way? `savedOrdersDetailsStore.record(key);` is a no-op in your code (it is just a reference)

**Comment by alextekartik** [comment]
Also don't rely on what you see in the database file and the data available to your app. Format (for information only, not direct access) explained here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md

**Comment by saravananmnm** [comment]
@alextekartik  Actually my problem is, when i retrieve the stored data from local DB, it was returned the duplicate of records. This is because of DB update is also inserted new one record.

**Comment by saravananmnm** [comment]
Still exists the same issue. When i get the particular record from local db. It has retrived as 3 records for same.

**Comment by alextekartik** [comment]
Not sure I understand what you mean by "It has retrived as 3 records for same". Can you help me reproduce the issue, or even better a unit test?

**Comment by saravananmnm** [comment]
@alextekartik 
Steps:

1. Save the object model into one local db store.
2. Update some fields from the same object model.
3. If you retrieve object the same model, it will get 2 type of same object model but different String keys.

**Comment by alextekartik** [comment]
Do you have some code to show how you "save" and "update" so I can help you? To update a record you must access it with a key (store.record(key).put). If you add a record, by default a key is generated, it will create a new record even if the data is the same (that is how it works on any databases). If you don't want to create record if it already exists, you should look for it first and and it if not found in a transaction.

More documentation on how to write to the database here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md

**Comment by saravananmnm** [comment]
For save the record;

` Future<bool> saveOrdersDetails(PobPodDetailsModel model,{bool isInsert = true}) async {
    bool result=false;
    var db = await storage.openDB();
    var data = await getSavedOrderDetails(model.orderId, model.statusId);
    if (data == null || data.length == 0) {
      await db.transaction((txn) async {
        var key = await savedOrdersDetailsStore.add(
            txn, PobPodDetailsModelSerializer().toMap(model));
        savedOrdersDetailsStore.record(key);
      }).catchError((e) {
        result= false;
      });
      print('table rows inserted');
      result=true;
    }
    return result;
  }`

For Update the record:

`  Future<bool> updateSavedOrderDetails(String orderId,String uploadStatus) async {
    var db = await storage.openDB();
    int updateCount = 0;
    List<Filter> fd = [];
    fd.add(Filter.equals('orderId', orderId));
    if (StringConstant.POD == uploadStatus)
      fd.add(Filter.equals('statusId', uploadStatus));
    var finder = Finder(filter: Filter.and(fd));
    var data = await getSavedOrderDetails(orderId, '');
    if (data != null) {
      for (var result in data) {
        result.uploadStatus = 1;
        await db.transaction((txn) async {
          updateCount = await savedOrdersDetailsStore.update(
              txn, PobPodDetailsModelSerializer().toMap(result),
              finder: finder);
        }).catchError((e) {
          return false;
        });
      }
    }
    return updateCount == 0 ? false : true;
  }`

**Comment by alextekartik** [comment]
A couple of notes:
- please use triple ticks to enclose your code (I updated your comments)
- You should use the latest lints or flutter lints and fix all lints warning as it helps finding issues
- You should use default dart formatting
- You call `savedOrdersDetailsStore.record(key);` without doing anything with it (dead code)
- You should update to null safety if not done yet
- In your insert you should check in the transaction whether an existing record exists (nothing prevent in your code to have multiple records with the same orderId)
- I don't know what getSavedOrderDetails do but in your update (get records by orderId and statusId or just orderId?), but you check records with status empty and you update record with a specific statusId).
- I cannot tell whether there is a unique row for a given orderId (and for sure, nothing prevent that in your code)

For me it is impossible to say whether your code is correct, or whether there is an issue in sembast implementation. You should test your database code in a unit test if you can (with an in memory database) or give a smaller example along with more print that explains the issue you are seeing.

**Comment by saravananmnm** [comment]
@alextekartik  Thanks for feedback.

In my code, I have checked whether records are existing (`var data = await getSavedOrderDetails(model.orderId, model.statusId);`) for the save the records.

Can you give some code snippets for insert and update the records without duplicate.

There are around 25 plugins used in our project. So that, still not update null safety.

**Comment by alextekartik** [comment]
> Can you give some code snippets for insert and update the records without duplicate.

Below is a small example that I will add to the docs:

## Add or update example

Let's assume a product store where the unique key is an integer.
But you want to have a unique 'code' field (each product having a unique code).
(Although as a side note, it is more clever to use the code as a string key)

```dart
var store = intMapStoreFactory.store('product');

// Add some data
await db.transaction((txn) async {
  await store.add(txn, {'code': '001', 'name': 'Lamp', 'price': 10});
  await store.add(txn, {'code': '002', 'name': 'Chair', 'price': 25});
});
```

Let's write a function that will either add or update a record. To handle
race conditions and avoid duplicates, this must be done in a transaction:

```dart
/// Either add or modify records with a given 'code'
Future<void> addOrUpdateProduct(Map<String, Object?> map) async {
  // Check if the record exists before adding or updating it.
  await db.transaction((txn) async {
    // Look of existing record
    var existing = await store
        .query(
            finder:
                Finder(filter: Filter.equals('code', map['code'])))
        .getSnapshot(txn);
    if (existing == null) {
      // code not found, add
      await store.add(txn, map);
    } else {
      // Update existing
      await existing.ref.update(txn, map);
    }
  });
}
```

Quick test:

```dart
// Update existing
await addOrUpdateProduct(
    {'code': '002', 'name': 'Chair', 'price': 35});
// Add new
await addOrUpdateProduct(
    {'code': '003', 'name': 'Table', 'price': 82});

// Should print:
// {code: 001, name: Lamp, price: 10}
// {code: 002, name: Chair, price: 35} - Updated
// {code: 003, name: Table, price: 82}
for (var snapshot in await store.query().getSnapshots(db)) {
  print(snapshot.value);
}
```
