### ISSUE TITLE
Will Sembast support non-nullable types?

### ISSUE THREAD

**Issue by lyio** [tekartik/sembast.dart#231]
I am in the process of updating to Flutter 1.25.0 and had to bump quite a bit of libraries to their respective null-safe prerelease versions.
This includes `synchronized`, which is used in Sembast, for example here in the `flush` method in `database_impl.dart` 

```dart
Future flush() async {
    // Wait for pending transaction
    await transactionLock.synchronized(null);
    // Wait for pending writes
    await databaseOperation(null);
  }
```

In `synchronized` 3.0.0 the argument to `synchronized()` can no longer be null, so they do not check for `null` before calling it. This understandably leads to a `NoSuchMethodError`.

Are there plans to support the null-safety features of Dart 2.12?

**Comment by alextekartik** [comment]
Yes there is already a pre-release for sembast like many packages that should get listed when you run `dart pub outdated`: https://pub.dev/packages/sembast/versions/3.0.0-nullsafety.3

**Comment by alextekartik** [comment]
And as you can seen, the flush implementation has evolved:
https://github.com/tekartik/sembast.dart/blob/8195c25fc2156d493c345003d64c4fb3a807ef5b/sembast/lib/src/database_impl.dart#L590-L596

One big change that you might encounter is that the type `Map<String, dynamic>` has changed to `Map<String, Object?>`. I have not used the nndb implementation  much yet as I have other dependencies in some project that have no null safe pre-release yet.

**Comment by lyio** [comment]
@alextekartik oh thank you for that!

I didn't notice that release, sorry for the bother.
