### ISSUE TITLE
Difference between add and put methods 

### ISSUE THREAD

**Issue by Maksimka101** [tekartik/sembast.dart#232]
Please, pay attention to the difference between `add` and `put` methods in readme. I spent a very long time looking for a bug in the code, not understanding why everything works, but wrong

Maybe my case a bit specific but I think that I'm not the only one

**Comment by alextekartik** [comment]
Hi, I'm not sure I understand what you get wrong. Can you clarify what I need to add?
- `add` adds a new record
- `update` update an existing record
- `put` will either add or update a record.

**Comment by Maksimka101** [comment]
I think you should add all three explanations next to each other, so that people understand exactly what they can do.

 - `add` adds a new record and generate a new record key
 - `update` update an existing record
 - `put` will either add or update a record

**Comment by ChristianKleineidam** [comment]
It also took me a while to figure out that I have to use put to be able to specify the key. How about writing:

> put will either create a new record with a user specified key or update a record

**Comment by alextekartik** [comment]
Thanks and sorry for not being clear. I've added your suggestion and an example. Basically you can add with or without a key:

```dart
// Add the data and get its new generated key
var key = await store.add(db, {'value': 'test'});

// Add the data with a specified key (1234)
// Fails if the record already exists
await store.record(1234).add(db, {'value': 'test'});
```

Added to: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md

Don't hesitate to ask for clarification (and PR welcome!)

**Comment by ChristianKleineidam** [comment]
So if I understand right the difference between add and put is that add fails when there's an existing record while put overwrites it? Are there other differences? If you say it fails, does it do nothing or throw an Error?

**Comment by alextekartik** [comment]
> add fails when there's an existing record while put overwrites it?

Correct

>  If you say it fails, does it do nothing or throw an Error?

I should indeed specify that. In general sembast does not throw exception. https://pub.dev/documentation/sembast/latest/sembast/SembastRecordRefExtension/add.html

Since add returns the inserted key. Failing means that null is returned when it fails. I would indeed prefer throwing an exception especially with nnbd support but for compatibility reason I cannot really change this behavior.

**Comment by ChristianKleineidam** [comment]
I just accidentially used .add for adding document with an already existing index and got as error:
```
E/flutter ( 5178): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String' of 'value'
E/flutter ( 5178): #0      Future._completeWithValue (dart:async/future_impl.dart)
E/flutter ( 5178): #1      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:264:13)
E/flutter ( 5178): #2      SembastStore.txnAdd (package:sembast/src/store_impl.dart)
E/flutter ( 5178): <asynchronous suspension>
E/flutter ( 5178): #3      SembastDatabase.transaction (package:sembast/src/database_impl.dart:1094:14)
E/flutter ( 5178): <asynchronous suspension>
E/flutter ( 5178): #4      SembastRecordRefExtension.add (package:sembast/src/record_ref_impl.dart:66:12)
E/flutter ( 5178): <asynchronous suspension>

```

**Comment by alextekartik** [comment]
Thanks for the report @ChristianKleineidam Indeed some tests were dropped during nnbd migration and there were some cast issues. Can you try with the updated sembast 3.0.0+5?

**Comment by ChristianKleineidam** [comment]
I can't reproduce it with 3.0.0+5, so hopefully the issue is solved.
