### ISSUE TITLE
get all records

### ISSUE THREAD

**Issue by rafekun** [tekartik/sembast.dart#233]
Are there any ways to get all records in a database?

**Comment by alextekartik** [comment]
Currently that is not possible since there is no way to get the list of stores (but you can get all records in a store using find). There used to be a way to get a list of store but the behavior was not consistent. If needed I could add a way to get the list of of non-empty store names.

**Comment by rafekun** [comment]
Thank you for your reply 😄 
If possible, I want to know the way to retrieve the list of non-empty store names.

**Comment by alextekartik** [comment]
I need to add this. I'll work on it now.

**Comment by rafekun** [comment]
Thank you so much!!

**Comment by alextekartik** [comment]
Published as a dev version. So you have to explicitly depend on `sembast: '>=2.4.9-dev.0'`.

You can get the list of non-empty store names using `getNonEmptyStoreNames(db)` from `utils/database_utils.dart`.

```dart
import 'package:sembast/utils/database_utils.dart';
...
// Get the list of non-empty store names
var names = await getNonEmptyStoreNames(db);
```
