### ISSUE TITLE
Set original key

### ISSUE THREAD

**Issue by rafekun** [tekartik/sembast.dart#235]
Hi,
How can I set unique key when adding data?
My data model is..
```dart
const String store = 'user_data';
const String key = user_id;
// doc is DocumentSnapshot of Firestore
const data = doc.data();
```
Or should I use auto-generated key?
Thanks!

**Comment by rafekun** [comment]
Sorry, I found this article

> A store is defined by its key and value type to enforce strong mode. A typically usage would be an auto-generated integer id and a Map containing the data as its value.
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/sembast_data.md

**Comment by rafekun** [comment]
A key maybe autogenerated.
But, how can I find specific record by the auto-generated key? How can I know which key has what data?

**Comment by rafekun** [comment]
My understanding of sembast is
- Store
corresponds to Firestore Collection  
- Record
corresponds to Firestore Document
So, is a key  equivalent to Firestore's document Id?

**Comment by alextekartik** [comment]
@rafekun 
You understanding is correct, a key is similar to a document id, a record is similar to a firestore document and store to a collection.

Some info on how to find a record from its generated key:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#using-auto-generated-int-key

To create a record with a key you want to specify you can do something like:
```
await store.record(my_key).put(my_data);
```

**Comment by rafekun** [comment]
Thank you!! 😄 
@alextekartik
