### ISSUE TITLE
Put() not overwriting existing record inside the db file

### ISSUE THREAD

**Issue by jezer07** [tekartik/sembast.dart#236]
I noticed that inside the db file generated by Sembast, when `put()` is called for the same `record(key)`, it doesn't actually overwrite the existing record but rather it will create a new record with the same key and with the new value, even if `merge:true` is called. 

Is that intentional? 

Although querying the db returns the correct size and correct data, the db file size may grow fast unnecessarily.. 

Example code:
`store.record(data.key).put(db, data.toMap(), merge: true);`

Am I missing something?

Thanks!

**Comment by alextekartik** [comment]
You can get more info on the file format here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md#sembast-storage-format

The file might get compacted at some point:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md#compacting

You can get more information on the format used here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md#example

This is for `sembast` in io mode. On mobile `sembast_sqflite` will use sqflite as the backend format. On the web `sembast_web` will use indexed db.
