### ISSUE TITLE
FileSystemException when debugging on ios

### ISSUE THREAD

**Issue by amini-rezza** [tekartik/sembast.dart#237]
Running the app on simulator is tottaly fine but,
when trying to debug on real device in ios a white screen is shown. Here is the stacktrace : 

_dart_state.cc(177)] Unhandled Exception: FileSystemException: Cannot create file, path = '/var/mobile/Containers/Data/Application/62095A41-4902-4406-A4AF-89B6E55A59A2/Documentsdatabase.db' (OS Error: Operation not permitted, errno = 1)
#0      _wrap.<anonymous closure> (package:sembast/src/io/file_system_io.dart:103:7)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

let me know if you need any extra information

**Comment by alextekartik** [comment]
Looking at the path (`Documentsdatabase.db`), it seems you are not building the path correctly (use path.join) as I think you meant `Documents/database.db`.

**Comment by amini-rezza** [comment]
You are right. I have built the path incorrectly.
final dbPath = '${dir.path}database.db'; 
It works on android both the release and debug version and it also works on ios simulator, only on iphone it doesn't work. I'm curious why it works on android though?

Thanks btw for quick response i really appreciate it.

**Comment by alextekartik** [comment]
On Android, the databases path is a sub folder and  the parent of the database path is writable. On iOS the parent of the document folder (which is the database path) is not writable

**Comment by alextekartik** [comment]
Sorry I was wrong, it is not the databases path but it is just a matter of what folder an application has access.

**Comment by amini-rezza** [comment]
Oh i see.
Thank you so much.
