### ISSUE TITLE
Unable to import database due to "OS Error: Read-only..."

### ISSUE THREAD

**Issue by DanMossa** [tekartik/sembast.dart#239]
Hello!

I'm having an issue when I'm trying to restore a backed up DB file.

This is my LocalDB

```
const DBName = 'localdb.db';

Database openedDatabase;

class LocalDB {
  static Future<Database> _getDatabase() async {
    if (openedDatabase != null) {
      return openedDatabase;
    }

    final Directory dir = await getApplicationDocumentsDirectory();
    await dir.create(recursive: true);
    final String dbPath = join(dir.path, DBName);
    return openedDatabase ??= await databaseFactoryIo.openDatabase(dbPath);
  }

  static Future<int> deleteDatabase() async {
    final Database db = await _getDatabase();
    final StoreRef<dynamic, dynamic> store = StoreRef<dynamic, dynamic>.main();
    return store.delete(db);
  }

  static Future<Map<String, dynamic>> export() async {
    final Database db = await _getDatabase();

    final Map<String, dynamic> dbContent = await exportDatabase(db);

    return dbContent;
  }

  static Future<void> import(Map<dynamic, dynamic> jsonEncodedDBContent) async {
    final DatabaseFactory dbFactory = databaseFactoryIo;

    await importDatabase(jsonEncodedDBContent, dbFactory, DBName);
  }
}
```

The error I'm getting is with 
`static Future<void> import(Map<dynamic, dynamic> jsonEncodedDBContent)`

The error I'm getting is 

`FileSystemException: Cannot create file, path = '/localdb.db' (OS Error: Read-only file system, errno = 30)`

I'm unsure what I'm doing wrong. I think it has to do with the `databaseFactoryIo` but I can't tell.
Thanks!

**Comment by alextekartik** [comment]
It seems that you are trying to write to the root folder `/localdb.db` which is indeed not writable. In `importDatabase` you should use the same db name (dbPath) that you are using for opening a db instead of `DBName` which has no path information.

**Comment by DanMossa** [comment]
Wow. I do feel really dumb. @alextekartik 
I've been looking through the github issues to see if other people had this issue and all I could see were people not reading the documentation and how frustrating that can get.

Sorry for adding to the problem.

The only suggestion I can think would be

```
var importedDb = await importDatabase(map, databaseFactory, 'imported.db');
```

I didn't realize that `'imported.db'` should be a path and not just the name. Do you think I should make a PR to make this more obvious?

**Comment by alextekartik** [comment]
No problem @DanMossa. It points out that the documentation is not good enough. PR (on doc or code) are always welcome! Depending on which platform it is used, just a name could work though (it would be in the current working directory on desktop for example and it would work on the web using sembast_web).
