### ISSUE TITLE
Filtering on a Field that is an Array

### ISSUE THREAD

**Issue by Mosely** [tekartik/sembast.dart#24]
Hi there!

Is it possible to filter on a field that's an array?  For instance, let's say I have a field called TextArray, and in all of my records, that field contains 3 string elements (different sentences).  Would I be able to make a Filter that matches by Regular Expression searching that TextArray field?

Thank you, and great work, by the way!

**Comment by alextekartik** [comment]
Thanks for the note. Indeed that was not possible but I can see the need. Support has been added in 1.15.1: <https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/queries.md#filtering-list-items>


`Filter.equals` and `Filter.matches` can also look for list items if a field is a list using the `anyInList` option. It
will match if one item in the list matches the criteria.

```dart
// Look for record with at least one category stating with f (i.e. food...), 
// if `categories` field is a list with text elements
var finder = Finder(filter: Filter.matches('categories', '^f', anyInList: true));
var record = await store.findFirst(db, finder: finder);
```

**Comment by Mosely** [comment]
That works for me, thank you for the quick fix!
