### ISSUE TITLE
error: Non-nullable instance field '_dbOpenCompleter' must be initialized.

### ISSUE THREAD

**Issue by chitgoks** [tekartik/sembast.dart#242]
Hi. im using the new version now that uses null safety.

my old code has this

// A private constructor. Allows us to create instances of AppDatabase
  // only from within the AppDatabase class itself.
  AppDatabase._();

but now, using the new null safety lib, it gives an error saying 

error: Non-nullable instance field '_dbOpenCompleter' must be initialized. (not_initialized_non_nullable_instance_field at lib\db\app_database.dart:22)

thoughts?

these are the first few lines of my code

```
  // Singleton instance
  static final AppDatabase _singleton = AppDatabase._();

  // Singleton accessor
  static AppDatabase get instance => _singleton;

  // Completer is used for transforming synchronous code into asynchronous code.
  Completer<Database> _dbOpenCompleter;

  // A private constructor. Allows us to create instances of AppDatabase
  // only from within the AppDatabase class itself.
  AppDatabase._();
```

**Comment by flrnd** [comment]
Hey how did you solve this?

**Comment by chitgoks** [comment]
hard to trace what i did to make it work. i forgot about it. sorry.

**Comment by flrnd** [comment]
@chitgoks No worries. Thanks anyway. 

In my case, if anyone comes someday with the same doubt, I just used the `late` keyword in the Database definition.
