### ISSUE TITLE
ImmutableList seems to produce problems with nested Lists

### ISSUE THREAD

**Issue by ChristianKleineidam** [tekartik/sembast.dart#244]
If I put a List<List<List<String>>> object into sembast_db the object that I can read from sembast db can't be cast to List<List<List<String>>>. This is very confusing. 

This problem seems to exist because sembast wraps lists with ImmutableList with does not subclass List directly. Given that ImmutableList currently looks like it's just a wrapper for list, I seems questionable to me what value gets provided by returning list objects in that format to the user. The ImmutableList wrapper is more likely to cost performance then increase performance.

If sembast continues to give out ImmutableList, that class should at least have a function that gives me a List<List<List<String>>> if that's what I put into the database. Such a function might be called `.toList()`.

**Comment by ChristianKleineidam** [comment]
It's also worth noting that ImmutableList makes it impossible to mock Sembast for unittests at the moment because it outputs with ImmutableList a class where the constructor is not exposed outside of the plugin.

**Comment by alextekartik** [comment]
This issue is not sembast specific. Every list (event a list of string) will be read as a List<Object?> since the content is simply json encoded in the storage.

You can try the following:

```dart
  var listOfListOfList = <List<List>>[];
    expect(listOfListOfList, const TypeMatcher<List<List<List>>>());
    var newList = jsonDecode(jsonEncode(listOfListOfList));
    expect(newList, const TypeMatcher<List>());
    // Not anymore
    expect(newList, isNot(const TypeMatcher<List<List<List>>>()));
```

**Comment by alextekartik** [comment]
Whether you're using sembast on Flutter or on the web you can easily mock
sembast in memory.

```dart
import 'package:sembast/sembast.dart';
import 'package:sembast/sembast_memory.dart';
import 'package:test/test.dart';

void main() {
  test('my_unit_test', () async {
    // In memory factory for unit test
    var factory = newDatabaseFactoryMemory();

    // Define the store
    var store = StoreRef<String, String>.main();
    // Define the record
    var record = store.record('my_key');

    // Open the database
    var db = await factory.openDatabase('test.db');

    // Write a record
    await record.put(db, 'my_value');

    // Verify record content.
    expect(await record.get(db), 'my_value');

    // Close the database
    await db.close();
  });
}
```
