### ISSUE TITLE
Ability to export/import specific stores

### ISSUE THREAD

**Issue by ChristianKleineidam** [tekartik/sembast.dart#247]
Part of my database is user data where it makes sense for the user to be able to export and import their user data. Other data isn't userdata and I don't want to export that other data. 

I would want to be able to pass a list of strings with store names to the exportDatabase and then if the string is passed only export stores with names that are in the list. 

Similarly I would want to be able to pass a list of store names to importDatabase so that only stores that are in the list get imported.

**Comment by alextekartik** [comment]
> I would want to be able to pass a list of strings with store names to the exportDatabase and then if the string is passed only export stores with names that are in the list.

Ok. That's easily feasible

> Similarly I would want to be able to pass a list of store names to importDatabase so that only stores that are in the list get imported.

That's also feasible.

That can be done  quickly, I'll keep you posted.

**Comment by alextekartik** [comment]
Implement in sembast 3.0.1

**Comment by ChristianKleineidam** [comment]
Thanks.
