### ISSUE TITLE
How do I Merge a List of bulk Data

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#248]
is there any way I can merge bulk data like 'addAll'? So I mean is it possible to update a whole store?
I need this because I have a store and I fetch data in the background every few seconds to update the local store but because its bulk I delete all every time before I update to avoid repeating data. Please How do I achieve this

**Comment by alextekartik** [comment]
Writing has a cost. Deleting and re-adding a record that has not changed costs far more than reading first whether a record exists. 

Let's assume that you fetch 100 records from a REST API that you want to save in a sembast store. Pseudo algo I would do:
- fetch data from the network
- read all records from sembast
- In a transaction
  - Find and ignore records that have not changed
  - Update records that have changed
  - Delete other records

If data don't change much, likely your "sync" algo won't write anything most of the time which is better than deleting everything and inserting again.

I'm not sure whether this answers you questions but `addAll` is just performing multiple `add`s in a transaction. Transactions are keys for data consistency and performance

**Comment by MichaelSowah** [comment]
Exactly what I was thinking but I wanted to find out this
can I compare a whole record like {'name': 'fish', 'age': 5} to another record like {'name': 'fish', 'age': 6}?

**Comment by alextekartik** [comment]
Yes you can use `DeepCollectionEquality().equals(v1, v2);` from the collection package to compare the records data.

**Comment by MichaelSowah** [comment]
so this then can help me in doing the Find and ignore records that have not changed right?

**Comment by alextekartik** [comment]
Correct

**Comment by MichaelSowah** [comment]
ok, sorry another quick one am trying to structure my db like https://github.com/alextekartik/flutter_app_example/blob/master/notepad_sembast/lib/provider/note_provider.dart

this but the Lock is giving me error saying the Lock method isnt defined

**Comment by MichaelSowah** [comment]
this is my current db class
class ProjectDB{
  ProjectDB._internal();
  static ProjectDB get instance => _singleton;
  static final ProjectDB _singleton = ProjectDB._internal();

  static Database _db;

  Future<Database> get db async{
    if (_db != null) {
      return _db;
    }

    _db = await initDB();

    return _db;
  }

  Future initDB() async{
    final appDoc = await getApplicationDocumentsDirectory();
    final dbPath = join(appDoc.path, 'ProjectDB.db');
    final database = await databaseFactoryIo.openDatabase(dbPath, version: 1);

    return database;
  }

  Future close() async {
    await _db.close();
  }
}


but any time I do this Future<Database> get db async => await ProjectDB.instance.db; and I call await db.transaction((txn) async {
      
      
    }); I get an error...

**Comment by MichaelSowah** [comment]
ok so how do I find and compare, I got a bit lost there...

**Comment by alextekartik** [comment]
Hard to help you more here on why it does not work (you can try jsonEncode on confirm the data is exactly the same (if age is a string instead of an int, it would fail). Synchronization is a whole topic, you could typically store a local reference to a remote record so comparing content might involve skipping some information. `DeepCollectionEquality().equals(v1, v2);` was one solution, if it does not work you can compare manually each field to know if a record has changed.

**Comment by MichaelSowah** [comment]
@alextekartik I figured one particular variable which actually changes and the rest does not so on the pull to refresh I fetch from the network, do a for each on the data in transaactions then find and update the records that have changed...I hope its ok to perform the task in that manner in transactions right?

**Comment by alextekartik** [comment]
I would avoid doing http fetch during a transaction (i.e. fetch the data from the network before the transaction, which is maybe already what you are doing) but other than that you should be fine, transactions do not block other concurrent reads.

**Comment by MichaelSowah** [comment]
Thanks so much for the help
