### ISSUE TITLE
Not able to access the getEncryptSembastCodec method.

### ISSUE THREAD

**Issue by PCIHD** [tekartik/sembast.dart#249]
Has the implementation for encryption changed for sembast, perhaps a update is required in the documentation

**Comment by alextekartik** [comment]
Thanks for the report:

You can find an implementation up to date here (in sembast_test project): https://github.com/tekartik/sembast.dart/blob/3f3f8fd943118643f456cd561de83e414691e667/sembast_test/lib/encrypt_codec.dart

ICan you help and give me the link where you found outdated information? Thanks!

**Comment by allomy** [comment]
@alextekartik The outdated information might be this page (https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/codec.md), where the the hyperlink is outdated.
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/74531411/211444311-3984633a-3631-428f-b5d1-03b8079c8c93.png">
