### ISSUE TITLE
Windows UWP platform support

### ISSUE THREAD

**Issue by henilagile** [tekartik/sembast.dart#265]
Unable to run note pad demo for windows UWP platform.

https://github.com/alextekartik/flutter_app_example/tree/master/notepad_sembast

**Comment by alextekartik** [comment]
Thanks for the report. I need to be on the dev channel to reproduce, correct?

**Comment by alextekartik** [comment]
I tried on windows both on stable and dev (2.3.0-24.0.pre) and was able to run the nodepad sembast example.

```bash
# (Optional) Delete/recreate existing project files
#            Might be needed when switching flutter branch
rmdir -Recurse -Force windows
flutter create --platforms windows .

# Run
flutter run -d windows
```

Are you able to run the default flutter template on Windows? What error are you facing when running notepad_sembast example?
