### ISSUE TITLE
Unhandled Exception: FileSystemException: Cannot create file, path = '/var/mobile/Containers/Data/Application/D3F0BC12-0483-4617-9CFC-D58E9AC06670/Documentstr.db' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by gmalmeida** [tekartik/sembast.dart#266]
When running on my iOS device.
![image](https://user-images.githubusercontent.com/5320909/122916484-39331380-d35d-11eb-9c03-9fbc99b6febb.png)

I do not see this issue on Android device although.

**Comment by alextekartik** [comment]
You db path looks incorrect. Instead of
```
/var/mobile/Containers/Data/Application/D3F0BC12-0483-4617-9CFC-D58E9AC06670/Documentstr.db
```
I guess it should be:
```
/var/mobile/Containers/Data/Application/D3F0BC12-0483-4617-9CFC-D58E9AC06670/Documents/tr.db
```
 Try
```
dbPath = join(dir.path, 'tr.db');
```

**Comment by gmalmeida** [comment]
Hi Alex,

Shame on me, sorry for having overlooked at that.

Many thanks for your fast support. 

All the best.
