### ISSUE TITLE
type 'String' is not a subtype of type 'int' of 'key'

### ISSUE THREAD

**Issue by alaindixon** [tekartik/sembast.dart#267]
Really weird, I can't use a string as a key.
I have replace de md5 by timestamp int, the error has disappear :/
`await storeInstance.record(md5).put(db, {'longUrl': url, 'shortUrl': jsonResponse['shorturl']});`

**Comment by alextekartik** [comment]
The type of the key is enforced by the type of `storeInstance`. If you use something like:
```
var storeInstance = stringMapStoreFactory.store('my_store');
```

The key will be a string. If you use:
```
var storeInstance = intMapStoreFactory.store('my_store');
```

The key will be an int.

**Comment by alaindixon** [comment]
Thank you very much, sorry I've switched from a very old verion.
