### ISSUE TITLE
Test if updated was successful

### ISSUE THREAD

**Issue by CodeDoctorDE** [tekartik/sembast.dart#269]
I use `usersStore.update(db, user.toJson(), finder: Finder(filter: Filter.byKey(user.id)));` to update my database. How can I check if the finder find anything and updatet it?

**Comment by alextekartik** [comment]
`StoreRef.update` returns the number of items updated, hence 0 if none, 1 if the user was found. See doc here: https://pub.dev/documentation/sembast/latest/sembast/SembastStoreRefExtension/update.html

```dart
/// count if 0 if the object was not found
var count = await usersStore.update(db, user.toJson(),
          finder: Finder(filter: Filter.byKey(user.id)));
```

You could also access the record by key (direct access much faster). Here the object returned is null if the record was not found, or the resulting map if the record was found and updated. See doc here: https://pub.dev/documentation/sembast/latest/sembast/SembastRecordRefExtension/update.html

```dart
/// map is null if the record does not exist
var map = usersStore.record(user.id!).update(db, user.toJson());

**Comment by CodeDoctorDE** [comment]
okay thanks
