### ISSUE TITLE
About relationship with tables?

### ISSUE THREAD

**Issue by kalismeras61** [tekartik/sembast.dart#27]
I dont know more about Nosql db. 
I have some quesitons.

store = table? Can we create multible stores?
How do we relate between tables?

**Comment by alextekartik** [comment]
I'm not sure about the proper wording. A store can be considered like an unorganized table where you store and fetch data in a specific way. You don't define the schema (you don't specify for example that a given column will be an int), you just store documents and retrieve them by queries. Practically yes, store can be used like table. And yes you can have multiple stores. I guess you will find better definition on the web; sembast is just a simple opiniated NoSQL API.

**Comment by kalismeras61** [comment]
Ok, I was using sqlite db and want to move sembast. In sqlite i have multiple tables so what is the best practise for that? I must create multiple store for saving different value? Or one store is enough for that?

**Comment by alextekartik** [comment]
multiple stores, mapped to the existing tables should be a good start

**Comment by kalismeras61** [comment]
Thanks
