### ISSUE TITLE
Any way to get the index of the record in list

### ISSUE THREAD

**Issue by deep1931** [tekartik/sembast.dart#270]
I want to implement a search like WhatsApp, for this, I need an index of matched records, so that I can jump to that list item, is there any way in sembast to get the index of a particular record.

**Comment by alextekartik** [comment]
There is no index or position in a list since this info is only valid at a given time when the record was fetched. One solution I think of is the following. Let's assume that you have the 2 following information:

```dart
// A list of records from a query
List<RecordSnapshot> snapshots =
          await store.query(finder: finder).getSnapshots(db);
// An item in this list
RecordSnapshot snapshot = ....
````

You can get the index of the record in the list using the following:

```dart
var index = snapshots
     .map((snapshot) => snapshot.key)
     .toList()
     .indexOf(snapshot.key);
```

**Comment by deep1931** [comment]
Thanks, I am currently working on it, I will update you after finishing this. Thanks a lot for the quick response.
