### ISSUE TITLE
Crash on iOS without Log

### ISSUE THREAD

**Issue by zl910627** [tekartik/sembast.dart#274]
app has crashed without any log!

https://user-images.githubusercontent.com/53897531/127888037-bf9637d3-9b63-49b1-aff1-e7d7fb474ec7.mov

Please check above screen capture.
This came from `get` method.
No then or exception and crashed without any log!

cooperator.dart / ln61~ln82

**Comment by alextekartik** [comment]
Puzzling indeed. I'm aware of such issue during unit test (https://github.com/tekartik/sembast.dart/issues/268). See https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/how_to.md#flutter-test-testwidgets

And the solution is to call:
```dart
disableSembastCooperator();
````
before your tests.

Are you simply running from XCode on iOS? Or just running flutter test? Can you try to add the call above to see if it fixes your issue.

**Comment by zl910627** [comment]
Hi @alextekartik 
Thank you for your reply.
I already have solved this problem by call `disableSembastCooperator();` at isolate entry point.
As you can see, code is running on vscode.

But it is not any unit test, but really app with another isolate rather than main isolate.
![image](https://user-images.githubusercontent.com/53897531/128325075-93b64631-9a17-45a5-9655-fb07e1ed8d89.png)

How can app access to a database file from two isolate?
There are no way to share big data between isolate without via db..

**Comment by zl910627** [comment]
Hi @alextekartik 
how could it work thread safe ?
It is really need to be solved.

**Comment by alextekartik** [comment]
Unfortunately sembast is not cross isolate safe and should only be called from the main isolate. You could consider doing your background operation from the main isolate or have you second isolate access the db through the main isolate
