### ISSUE TITLE
Query With Key Greater/Less Than a Value

### ISSUE THREAD

**Issue by TheRedPanda17** [tekartik/sembast.dart#275]
I've been reading through the docs, but I can't seem to find any way to get records where the key is greater than X. I have a db of auto-incremented keys that are used to record the history of a user's choices. They can go back in time to a certain point, at which I would like to delete everything after that id. Is there a way to do this?

**Comment by alextekartik** [comment]
Sorry for the poor documentation. There is a special field named `Field.key` that can be used in filters.

```dart
 var values = (await store
              .query(finder: Finder(filter: Filter.greaterThan(Field.key, <your_min_id>)))
              .getSnapshots(db))
```
