### ISSUE TITLE
Can I transport data from sqflite to sembast?

### ISSUE THREAD

**Issue by icoriha** [tekartik/sembast.dart#278]
Hello, I have an active app which has many users.
This app uses sqflite to store data in local DB.
Today, my app is approaching a turning point and needs big refactoring and rearchitecting.

As part of that, I want to change local DB package from sqflite to sembast.
I searched the way to do so, but no way was found.
Is there a good means to transport data from sqflite to sembast?

For example, Can I call openDatabase method of sembast inside onUpgrade method of sqflite?
I think this is the only way to meet my requirement.

But if there is a more smart way, Could you tell me that?

**Comment by alextekartik** [comment]
I'm not aware of any good way for migrating between 2 databases. You could likely map tables to store but you will be missing any join feature.

> Can I call openDatabase method of sembast inside onUpgrade method of sqflite?

Personnally I would do the opposite and perform the migration if the sembast database does not exist (in onVersionChanged of sembast, read data from sqflite and copy it to sembast then delete the sqflite database).

**Comment by icoriha** [comment]
Thank you very much for your advice.
I tried to write code that may match my needs roughly.
Does this look like OK?

```
var db = await factory.openDatabase(path, version: 1,
    onVersionChanged: (db, oldVersion, newVersion) async {

  if (oldVersion == 0) {
    // This block is called when no sembast DB exists

    if (_sqfliteRepository.hasData) {
      // read data from sqflite DB
      // and copy it to sembast
      // delete sqflite DB
    } else {
      // This block is for new user who has no sqflite data
      // Actually I don't have to write any code here
    }
  }
});
```

**Comment by icoriha** [comment]
Thank you so much.
I'll try it.
