### ISSUE TITLE
adding a record duplicates the data

### ISSUE THREAD

**Issue by ArielM24** [tekartik/sembast.dart#280]
Using this code to add a record of a map writes in the database two or more times the map, with the same key, store name, etc. 
(The insert function is only called once in the process)

```dart
class FolderDao {
  static const String FOLDERS_STORE_NAME = 'folders';
  final _folderStore = intMapStoreFactory.store(FOLDERS_STORE_NAME);
  Future<Database> get _db async => await AppDatabase.instance.database;

  Future<Folder> insert(Folder folder) async {
     final key = await _folderStore.add(await _db, folder.toMap());

     final readMap = await _folderStore.record(key).get(await _db);

     if (readMap == null) return null;
     final _folder = Folder.fromMap(readMap);
     return _folder;
  }
}
```

**Comment by alextekartik** [comment]
>  writes in the database two or more times the map

Can you elaborate what you mean here. Are you talking about the file format - you can find some explanation [here on why some records look duplicated in the storage file](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md).

When you add, a new unique key is generated. You could try to print the key for debugging purpose.

Good if you could reproduce the issue you are seeing in a [unit test](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/how_to.md#unit-test)

**Comment by ArielM24** [comment]
If I open the .db file there are always 2 records with some values null and others with the correct data. 
I put a listener in the storeage and always writes the first time when is is suposed to do that, and when the next line of the code executes another transaction is detected (and duplicates the last record with the same key).

I print the values of the transaccion in the listener.
The first add a record like this (some values are recorded as null)
 (null, H8KIR819VNtK3LLA54H2VTY224S7IK3X, lolol, ..., null, null)
And the duplicated transaccion records some like that (the values that were null in the first transaction now has the correct values)
(6140f1b04eda8f4a554fb5b2, H8KIR819VNtK3LLA54H2VTY224S7IK3X, lolol, ..., 2021-09-14T19:02:08.937Z, null)

**Comment by alextekartik** [comment]
Hard to see what is going wrong, sorry. It seems you have not enabled null safety nor new dart lints that definitely helps in finding issue in the code. To confirm, you say that you insert only once but you have 2 records in the db? if you have way to help reproducing the issue, that would help in investigating what is going wrong.

**Comment by ArielM24** [comment]
Okay, I'll try to find out what is happening with the records!
