### ISSUE TITLE
[Flutter] Saving doesn't work from another main isolate

### ISSUE THREAD

**Issue by proninyaroslav** [tekartik/sembast.dart#284]
I know that sembast is not recommended for use in another isolate, so I tried to work with sembast from another main isolate. This method is used in the `workmanager` plugin: we need to run the callback from the native code using `FlutterEngine`. In fact, we are creating another main isolate. Saving to the database occurs in the background when the first main isolate is closed, but the process is still alive and the second main isolate is running. The problem is that if I save a record in the second main isolate, then after starting the application, the changes in the database are not visible. I did something similar with Floor and it worked. I tried using sembast and sembast-sqflite and the result is the same.

**Comment by alextekartik** [comment]
I did not know we could have 2 main isolates. That's definitely a non tested scenario. sembast is not cross-isolate safe so you might corrupt data. In theory `sembast_sqflite` should work (or at least not corrupt data) but you might get stale values until you write on the database (that's only at this point that the changes would be reloaded - but that could be solved if that's indeed the only remaining issue)

**Comment by proninyaroslav** [comment]
@alextekartik 
How can I reload the DB?

**Comment by alextekartik** [comment]
This only works for sembast_web and sembast_sqflite and the only public way to force that is to write some data (you can just set a singleton with the current time). If that works I would consider exporting it in a better way. It does really reload the whole database, just the new changes.
