### ISSUE TITLE
Is there any way to overwrite local database on sembast web?

### ISSUE THREAD

**Issue by ductranit** [tekartik/sembast.dart#290]
I have the setup database like this:
```
if (kIsWeb) {
        var db = await databaseFactoryWeb.openDatabase('myDatabase.db'');
 } else {
        var root = final documentPath = await getApplicationSupportDirectory();
        final dbPath = '${root.path}/myDatabase.db';
        var db = await databaseFactoryIo.openDatabase(dbPath);
 }
```
On mobile I know exactly the database file path, then I can overwrite it with my custom snapshot file (I know there is a way to import/export data, but it isn't suitable for my requirements), like this:
```
// overwrite database by snapshot before init
final dbFile = File(dbPath);
if (await dbFile.exists()) {
    await dbFile.delete();
}
await snapshotFile.copy(dbPath);
```

But on web, I don't know how to do the same because there is no the file path.
I wonder where does the database locate on web?

**Comment by alextekartik** [comment]
> Is there an option to clear old data before importing?

import creates the database, so the database is clear before

> I guess it doesn't have stream copy json? I have to load the whole json file to import?

You need the whole json in memory

> I didn't test it yet, but do you think the import speed is good? As my database can have over 1 million records

sembast won't work for 1 million records. I suggest switching to another database for such requirements (SQLite).

--alex
