### ISSUE TITLE
Need Documentation Regarding Group By 

### ISSUE THREAD

**Issue by deep1931** [tekartik/sembast.dart#292]
Hello, 

I have a requirement, I have a table which is storing chats of different users on the basis of a unique id, I want to show a chat list with the recent entries of every user. Right now I am saving the latest message in a separate table to make a chat list, that is not an idle way and more difficult to manage two tables for the same functionlaity. I have tried to find out about the grouping option in Sembast but was not able to find. 

Please help to find the proper way to do this and put some light on how to group data.

Regards

**Comment by alextekartik** [comment]
There is no grouping option in sembast. In the No SQL world, it makes sense sometimes do duplication data. You could also add listener to populate a store with the most recent entries.

**Comment by deep1931** [comment]
Thanks for the reply, 
I have already fixed this issue, got the list as I was wanted. 

Regards
