### ISSUE TITLE
Sembast filter.equals comparing 2 identical Map<String, dynamic> returns false

### ISSUE THREAD

**Issue by guillaumeboussion** [tekartik/sembast.dart#298]
Hi, 

In my store, I store a record to this format : 
`
{
"query": "query homeCategories{ [...] }, 
"variables": {"nOffers": 10},
"data": {"categories" : [...]}
 }
 `

I'm using Filter.equals to compare a Map<String, dynamic> that are exactly the same, but the comparison is the "==" operator, which returns false.

I solution could be to add 
`
if (value is Map) {
// From the package flutter/foundation
return mapEquals(value, fieldValue);
}
`

to the SembastEqualsFilter.matchesRecord method.

Or is there a solution that I haven't heard about ?

See below the debug local variables

![image](https://user-images.githubusercontent.com/91058384/150553012-abf7e538-4da8-49c6-9f96-018c941f58a0.png)

Thanks

**Comment by guillaumeboussion** [comment]
Just tested this code sample, and feature is working : 

```
import 'package:collection/collection.dart';

@override
bool matchesRecord(RecordSnapshot record) {
    if (!canMatch(field, record.value)) {
      return false;
    }
    var fieldValue = record[field];
    if (anyInList == true) {
      if (fieldValue is Iterable) {
        for (var itemValue in fieldValue) {
          if (itemValue == value) {
            return true;
          }
        }
      }
      return false;
    } else {
      if (value is Map) {
        return DeepCollectionEquality().equals(fieldValue, value);
      }
      return fieldValue == value;
    }
  }
```

Sorry I'm new to GitHub and don't know how to do a PR, but hope this will help 👍

**Comment by guillaumeboussion** [comment]
Great, thanks for the reactivity, this will be really useful to me 👍

**Comment by guillaumeboussion** [comment]
Hi, 
Just been setting up my filters to handle my cache, and I have the following problem : 
One of my attributes is a Map<String, dynamic>. The dynamic element can contain a list, that can contain itself a Map. And it looks like `valueAreEquals(list, anotherList)` returns true if they contain the same type --> a Map.

Below the architecture of the content : 
```dart
Map<String, dynamic> variables : {
"orderBy" : [
{"column": "reduction", "direction": "DESC"}
]
}

Map<String, dynamic> otherVariables : {
"orderBy" : [
{"column": "views_count", "direction": "DESC"}
]
}

valueAreEquals(variables, otherVariables) = true;
```

Do I have to handle this by myself with a custom filter ?

**Comment by alextekartik** [comment]
That is indeed not expected if you pulled the latest version. valueAreEquals handle nested maps and lists. The following test works for me:

```dart
import 'package:sembast/src/value_utils.dart' show valueAreEquals;
import 'package:test/test.dart';

void main() {
  test('issue#298 valueAreEquals', () {
    expect(
        valueAreEquals({
          'orderBy': [
            {'column': 'reduction', 'direction': 'DESC'}
          ]
        }, {
          'orderBy': [
            {'column': 'views_count', 'direction': 'DESC'}
          ]
        }),
        isFalse);
  });
}
```

Can you confirm that is returned true for you?
