### ISSUE TITLE
Using put with merge true adds a record instead of update an existing one

### ISSUE THREAD

**Issue by ArielM24** [tekartik/sembast.dart#301]
Im making an app to get data from a page about a game (web scrapping) and saving the data in a data base. 
When I try to update the data (with a floating action button) I use the method put of a storeFactory and the last records are not updated, they are added again, even the same keys.

This is the function that I call to update the database

temtem_dao.dart: 

` static upsert(Temtem temtem) async {
    await store
        .record(temtem.number)
        .put(DatabaseDao().db, temtem.toMap(), merge: true);
  }`

This is the repo of the project. 
[https://github.com/ArielM24/temtem_wiki](url)

**Comment by ArielM24** [comment]
I'm running the app in Ubuntu

**Comment by alextekartik** [comment]
> the last records are not updated, they are added again, even the same keys.

When you read the record, you get the updated data, correct?

My guess is that you are looking directly at the database file in a sembast io format (i.e. ljson file). Some information here on the format should explain what you are seeing (changes are appended to the file which explain why some records are duplicated): https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md

If I'm wrong can you try to reproduce what you are seeing in a unit test? thanks

**Comment by ArielM24** [comment]
Yes, I have the updated info, the problem is that I'm storing some bytes to use as icons and sometimes they were duplicated (increasing the size of the database). Now that I know that the database is optimized for reading and not for size I will consider write the bytes into external files.
