### ISSUE TITLE
I can't filter data with EnumType.

### ISSUE THREAD

**Issue by kalismeras61** [tekartik/sembast.dart#31]
I have i lot of records in my store. I want seperate them with enum type. I can save it to db but when i want to filter them it doesnt show me any result.

```
Enum Type :

enum ItemState { health, diaper, sleep, measure, feed } 
```

```
  Future<List<WeightNHeight>> getAllSortedByName() async {
    final babyId = await Preferences.getId();
    final finder = Finder(
      filter: Filter.and([
        Filter.equal("babyId", babyId),
        Filter.equal('state', ItemState.measure),
      ]),
      sortOrders: [
        SortOrder("date", false),
      ],
    );

    final recordSnapshots = await _itemStore.find(
      await _db,
      finder: finder,
    );
    return recordSnapshots.map((snapshot) {
      final items = WeightNHeight.fromMap(snapshot.value);
      // An ID is a key of a record from the database.
      items.id = snapshot.key;
      return items;
    }).toList();
  }
```

**Comment by kalismeras61** [comment]
found the solutions.

**Comment by alextekartik** [comment]
enum are not supported. Please see the list of supported types here https://github.com/tekartik/sembast.dart/blob/master/sembast/README.md#values

In fact storing should not even work. Consider converting your enum to int or String value.

**Comment by alextekartik** [comment]
Ah and if you find a solution for your reported issue, good if you can share it! Thanks!

**Comment by kalismeras61** [comment]
I change it store field to enum index ( it is int value), So it works :)
