### ISSUE TITLE
Encyption

### ISSUE THREAD

**Issue by ElieDouaihy3** [tekartik/sembast.dart#312]
How i can see the database codec and make sure that the data has been saved encrypted please,
thank you

**Comment by alextekartik** [comment]
> How i can see the database codec

You cannot really "see" the codec used, only an encrypted signature is saved.

There some explanation of the encrypted format here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/codec.md

> and make sure that the data has been saved encrypted please,

As a proof, you should be able to decode each line using your codec!

**Comment by ElieDouaihy3** [comment]
Hello,

The Databse set to encrypted you can find the whole code here :
https://github.com/ElieDouaihy3/sembast_test/blob/master/lib/sembast_manager.dart
  Future<void> openDB() async {
    String dbPath = 'INTELLECT.db';
    final appDocDir = await getApplicationDocumentsDirectory();
    await databaseFactoryIo.openDatabase(
        join(appDocDir.path, dbPath),
        version: 1,
        codec:SembastCodec(
            codec:MyJsonCodec(),
            signature: 'AES'
        )
    ).then((value){
      semBastDB = value;
    });
  }

getAllDataDB return the data without encoding or decoding is that true or something missing? or find function decode them by default?

thank you

**Comment by alextekartik** [comment]
Yes the data returned by the API is not encrypted, only the data in the storage (io, sqflite, indexed_db) is encrypted.
