### ISSUE TITLE
Project Logo

### ISSUE THREAD

**Issue by ghost** [tekartik/sembast.dart#314]
I create a logo for the project using the concept about DB and NoSQL. This is the image and the source in SVG. Thanks for the project.

![rect7910](https://user-images.githubusercontent.com/73236147/172914983-5e420ca6-e659-45d3-8a05-fddaa79a7b80.png)
![sembast_logo](https://user-images.githubusercontent.com/73236147/172914990-8e126006-58fc-49dd-bb93-5abe60febb4e.svg)

**Comment by alextekartik** [comment]
Thanks! I cannot open the SVG using inkscape (I'm on linux). Also the SVG display weird in Chrome for me:
![image](https://user-images.githubusercontent.com/1721046/173026130-beef28a6-8e8d-42db-8439-d598f9f754c7.png)

**Comment by yagoagrosmart** [comment]
> Thanks! I cannot open the SVG using inkscape (I'm on linux). Also the SVG display weird in Chrome for me: ![image](https://user-images.githubusercontent.com/1721046/173026130-beef28a6-8e8d-42db-8439-d598f9f754c7.png)

sorry for the delay in responding

I create in Inkscape too. You need install the font, I create a zip with the file and the font. 

[sembast_logo.zip](https://github.com/tekartik/sembast.dart/files/8911932/sembast_logo.zip)
