### ISSUE TITLE
db file is getting wiped on open

### ISSUE THREAD

**Issue by dmrickey** [tekartik/sembast.dart#317]
I know I'm missing something, but I can't seem to find what that something is. I've got a simple .db file filled with some test data

```
{"foo":123}
{"foo":456}
```
I'm attempting to open it like so:
```
    String dbPath = 'assets/database/test.db';
    DatabaseFactory dbFactory = databaseFactoryIo;
    Database db = await dbFactory.openDatabase(dbPath);
```
But each time I do, its contents are immediately replaced with just the following:
```
{"version":1,"sembast":1}
```

How do I open an existing db file without wiping out what's already there?

After a bit more digging, it looks like it's expecting each row to be formatted like `{"key":"...","value":"..."}` (at least that's the format after calling `store.record('test').put(db, 'test value')`). So it looks like my problem is that it's erasing any lines that aren't formatted how it's expecting. My real use case (and initial file I was testing with until I swapped to the simple example above) is an NeDB where each row is formatted like `{"_id":"...",...}`. What do I have to do to open this file without each row getting wiped out?

edit: Ugh..I think I misread the doc. It doesn't say that it works with NeDB files. It says it's _inspired by_ NeDB. I'm guessing there's no way to do this without changing my data format?

**Comment by alextekartik** [comment]
There are some explanation of the internal format here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md

Indeed unless the file match the expected data format (that in theory you should not have to care about), it will be wiped out.

I don't know NeDB format enough but yes you would have to convert it.

**Comment by dmrickey** [comment]
Thanks, that's pretty helpful. It looks like I can easily transform my NeDB file into the same format that sembast would export, then import it and it _should_ put it in your expected format. NeDB is just one json object per line (no comma at the end of each line) and each object has an `_id` field.

Quick question about the exported file. Why does the export have a `keys` array? Isn't that basically just the index of each value? Or is there something else going on there?

**Comment by alextekartik** [comment]
The keys could be a list of string (sembast supports both int and String keys)
