### ISSUE TITLE
How to start with an existing database in flutter instead of starting with no database?

### ISSUE THREAD

**Issue by dmrickey** [tekartik/sembast.dart#318]
I found this section for flutter, but how do I get an existing file into that location instead of the app assuming it's creating a db?

https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/open.md#flutter

**Comment by alextekartik** [comment]
One solution is to import from an export you store in your flutter assets.

If you use sembast io, you could also copy the database file to the proper file system from your flutters asset.

Anyway this is not different from other database system. You can see the sqlite doc on how to open a database from an asset:
https://github.com/tekartik/sqflite/blob/master/sqflite/doc/opening_asset_db.md
