### ISSUE TITLE
How to insert a record with custom key?

### ISSUE THREAD

**Issue by purplecandy** [tekartik/sembast.dart#32]
```
var store = intMapStoreFactory.store();
var key = await store.add(db, {'offline': true});
var value = await store.record(key).get(db);
```
The above method generates an int key.
How do I create my own key ? and use it to get the record ?

**Comment by alextekartik** [comment]
Just set a value to the key

```dart
// Specify the key to use
int key = 1234;
await store.record(key).put(db, {'offline': true});
```

Documentation updated here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md#after
