### ISSUE TITLE
Multiple entries of the same record on the db

### ISSUE THREAD

**Issue by ivoleitao** [tekartik/sembast.dart#33]
I'm unable to execute put nor update without generating additional entries on the database. I've tried the following: 

`import 'package:path/path.dart';
import 'package:sembast/sembast.dart';
import 'package:sembast/sembast_io.dart';

main(List<String> arguments) async {
  Database db = await databaseFactoryIo
      .openDatabase(join(".dart_tool", "sembast", "example", "record_demo.db"));

  int key = 1;
  StoreRef<int, Map<String, dynamic>> store = intMapStoreFactory.store();
  await store.record(key).put(db, {'offline': true}, merge: true);
  await store.record(key).put(db, {'offline': false}, merge: true);
}
`

This generated in the db:

`{"version":1,"sembast":1}
{"key":1,"value":{"offline":true}}
{"key":1,"value":{"offline":false}}
`

As far as I understand this shouldn't be happen. This is irrespective of the type of key int or String. I've spotted this with a String key but it seems that int is the same.

**Comment by alextekartik** [comment]
Yes, that's an implementation detail (i.e. from the application you only see 1 record) but I guess it deserves some explanation! I started documenting the file format here:
<https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md>

I created a similar example to what you tried:
<https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md#example>

The file format is a personal choice mostly optimized for performance.

**Comment by ivoleitao** [comment]
Ha ok that explains it :-) Thanks a lot for the heads up
