### ISSUE TITLE
How do I chain/make compound filters?

### ISSUE THREAD

**Issue by daveshirman** [tekartik/sembast.dart#353]
The documentation is really unclear whether it's possible to do this.

Where:

- The `searchText` is found in **either** of the fields `clientName` **or** `buildingName`
- AND the results must be between the 2 dates which are integers e.g. 20231001.

Something like this:

```
    final finder = Finder(
      filter: Filter.and([
        Filter.or([
          Filter.matchesRegExp(
            'clientName',
            RegExp(searchText ?? "", caseSensitive: false),
          ),
          Filter.matchesRegExp(
            'buildingName',
            RegExp(searchText ?? "", caseSensitive: false),
          ),
        ]),
        Filter.greaterThanOrEquals('job_First_Start_Date_Int', startDateInt),
        Filter.lessThanOrEquals('job_First_Start_Date_Int', endDateInt),
      ]),
      sortOrders: [SortOrder('buildingName')],
    );
```

It should be updated to make clear how to do compound `and` and `or` filters.

Thanks

**Comment by alextekartik** [comment]
That looks like a perfect filter to me. I know the documentation is poor, sorry, especially on the filter section. I look into getting it better but PRs are always welcome. For example I might use your example as an example (I will likely replace the date with Timestamp for demonstration purpose) if that's ok for you.

**Comment by alextekartik** [comment]
I have added more document here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/queries.md#filtering-and-sorting

and added an example close to what you have provided.

**Comment by daveshirman** [comment]
No worries and thanks very much. Hopefully it helps other people too.
Cheers.
