### ISSUE TITLE
[Help] How to import the export/Import helper functions?

### ISSUE THREAD

**Issue by StrayDragon** [tekartik/sembast.dart#36]
Hello, I am a beginner with using Dart and Flutter, thanks for your useful package.
But I encountered a problem when I wanted to use these helper [functions](https://pub.dev/documentation/sembast/latest/sembast.utils.sembast_import_export/sembast.utils.sembast_import_export-library.html) to test some examples([here](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md#importexport)) in document , Have these functions been exported to the package in the latest version?

**Comment by alextekartik** [comment]
Yes it is exported, not from the main lib file but from the following public (i.e. what is not in src is public) import:
```dart
import 'package:sembast/utils/sembast_import_export.dart';
```

**Comment by StrayDragon** [comment]
Ok, It works well, Thank you! :smile:
