### ISSUE TITLE
Export JsonEncodableCodec type

### ISSUE THREAD

**Issue by TyBarthel** [tekartik/sembast.dart#365]
Can you please export the `JsonEncodableCodec` type so we can use that to handle custom type serialization with adapters and override the default on `SembastCodec`?

**Comment by alextekartik** [comment]
Done in sembast 3.5.0

> Export `SembastTypeAdapter` and `JsonEncodableCodec` from `utils/type_adapter.dart`

As a demo, you can look at a simple adapter (that converts native cloud firestore types) here:
https://github.com/tekartik/sembast_flutter_more.dart/tree/master/cloud_firestore_type_adapters

The import is safe (not in src) and will maintained like a regular API (but I did not want to pollute more the main sembast.dart)
```dart
import 'package:sembast/utils/type_adapter.dart';
```

**Comment by TyBarthel** [comment]
Thanks!

**Comment by TyBarthel** [comment]
Should probably export `JsonEncodableEncoder` and `JsonEncodableDecoder` as well right?

**Comment by alextekartik** [comment]
Indeed, done in 3.5.0+1. So far I did not use it outside of the package
