### ISSUE TITLE
remove all documents in store

### ISSUE THREAD

**Issue by rasmuschristensen** [tekartik/sembast.dart#37]
Hello

What is the best way to remove all documents in a store?

**Comment by alextekartik** [comment]
I was wondering where is this clear method...Actually the delete <https://pub.dev/documentation/sembast/latest/sembast/StoreRef/delete.html> method can (and should) be used. Maybe there should be a `clear` method that simply calls `delete` without filtering, it would be similar to the indexed db API...

As many things, it was not well documented. I added some info here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#delete-records

**Comment by rasmuschristensen** [comment]
Perfect, just what I needed. It works great!
