### ISSUE TITLE
Sembast web limitation

### ISSUE THREAD

**Issue by ilovekimchi6** [tekartik/sembast.dart#376]
**Features and limitations
Use int or key string only**

Reading that I understand it as only two datatypes can be used on Sembast Web.

https://github.com/tekartik/sembast.dart/tree/master/sembast_web

In the readMe.

Thank you!

**Comment by alextekartik** [comment]
The record KEY has to be an int or a String. The VALUE can be anything (Map, List, bool, num, String, Timestamp, Blob).

**Comment by ilovekimchi6** [comment]
Thank you, reading that I misunderstood!
