### ISSUE TITLE
is there support for custom primary keys?

### ISSUE THREAD

**Issue by KorbinianMossandl** [tekartik/sembast.dart#38]
I am storing items from an API response that already have a primary key attached. is there a way to make sembast use that key instead of the ones it auto generates?

**Comment by alextekartik** [comment]
Yes, if you set the key (an int or a String), il won't generate one. See here (in `Create a record with a given key`)
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md#after

**Comment by KorbinianMossandl** [comment]
thanks, i don't know how i could overlook this.
