### ISSUE TITLE
null check on null value

### ISSUE THREAD

**Issue by xfqqq** [tekartik/sembast.dart#384]
Here is a null check on null value, which will cause flutter exception, and there is a pr: https://github.com/tekartik/sembast.dart/pull/383, please take a look

```
#0 new _IoFileSystemException (package:sembast/src/io/file_system_io.dart:85)
1
#1 _wrap.<anonymous closure> (package:sembast/src/io/file_system_io.dart:119)
2
#2 _rootRunBinary (dart:async/zone.dart:1423)
3
#3 _CustomZone.runBinary (dart:async/zone.dart:1315)
4
#4 _FutureListener.handleError (dart:async/future_impl.dart:177)
5
#5 Future._propagateToListeners.handleError (dart:async/future_impl.dart:850)
6
#6 Future._propagateToListeners (dart:async/future_impl.dart:871)
7
#7 Future._completeError (dart:async/future_impl.dart:651)
8
#8 Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:556)
9
#9 _rootRun (dart:async/zone.dart:1399)
10
#10 _CustomZone.run (dart:async/zone.dart:1301)
11
#11 _CustomZone.runGuarded (dart:async/zone.dart:1209)
12
#12 _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249)
13
#13 _microtaskLoop (dart:async/schedule_microtask.dart:40)
14
#14 _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
15
Null check operator used on a null value
```

**Comment by alextekartik** [comment]
Thank you for the report and PR. Do you have any easy way to reproduce the exception? On which platforms did it occur?

**Comment by alextekartik** [comment]
Published in sembast 3.7.1+3. Thank you for the PR. I added a simple test to verify it

**Comment by xfqqq** [comment]
> Thank you for the report and PR. Do you have any easy way to reproduce the exception? On which platforms did it occur?

Sorry, actually i have not reproduced it successfully. Users of my company produced this exception and i saw the exception report on the report platform

**Comment by alextekartik** [comment]
Ok thanks, indeed osError could be null, I have added a simple unit test mocking that.
