### ISSUE TITLE
Problem: record is updated even merged is false

### ISSUE THREAD

**Issue by xOldeVx** [tekartik/sembast.dart#385]
I want to put a new record only if it doesn't exists, i'm using `merge: false` and still it's update the current exist record instead of just skip the update (just do nothing like `putIfAbsent` in flutter).

Here's the code:
```
  Future<void> addRecord(MyRecord myRecord) async {
    Map? file = await recordsStore.record(myRecord.name).get(db) as Map?;
    print('🔥file: $file');
    await recordsStore.record(myRecord.name).put(db, myRecord.toJson(), merge: false); <----- merge: false
    Map? file2 = await recordsStore.record(myRecord.name).get(db) as Map?;
    print('🔥file2: $file2');
  }
```

As you can see in the log below, the first insertAt is `1722510750560087` and the second is `1722510788206765`:

I/flutter ( 4067): 🔥file: {name: record_abc.bin, size: 67644, data: [], insertAt: `1722510750560087`}
D/[FBP-Android]( 4067): [FBP] onMethodCall: writeCharacteristic
I/flutter ( 4067): 🔥file2: {name: record_abc.bin, size: 67644, data: [], insertAt: `1722510788206765`}

**Comment by alextekartik** [comment]
merge does not really mean "check if it exists then update". It tries to merge the content of the existing record overriding with the fileds in the new content. You should better check if the record exists (better if you do this in a transactio, with code such as:

```dart
if (!recordsStore.record(myRecord.name).existsSync(db) {
   ...
   // put new record
}
```

**Comment by xOldeVx** [comment]
Thanks about the solution, I have been using it for a while, but I thought the package had some built-in solution instead of adding these checks manually on my end, it can be very useful to add this option.
By the way I checked the `merge` parameter, and the result is some no matter if it's `true` or `false` for example :

```
    text = 'test1';
    await recordsStore.record('test').put(db, text, merge: false);
    String? result1 = await recordsStore.record('test').get(db) as String?;
    print('First - merge false: text: $text, result: $result1');

    text = 'test2';
    await recordsStore.record('test').put(db, text, merge: true);
    String? result2 = await recordsStore.record('test').get(db) as String?;
    print('Second - merge true: text: $text, result: $result2');

    text = 'test3';
    await recordsStore.record('test').put(db, text, merge: false);
    String? result3 = await recordsStore.record('test').get(db) as String?;
    print('Third - merge false: text: $text, result: $result3');
```

As you can see in the log, all `put` using the same behavior (overriding the exist value), so what's the different?

```
I/flutter (13437): First - merge false: text: test1, result: test1
I/flutter (13437): Second - merge true: text: test2, result: test2
I/flutter (13437): Third - merge false: text: test3, result: test3
```

**Comment by alextekartik** [comment]
>  but I thought the package had some built-in solution instead of adding these checks manually on my end, it can be very useful to add this option.

I understand the request. I have added the `ifNotExists` options to `RecordRef.put()` to only create a record if does not exist.
Published in sembast 3.7.2

> By the way I checked the merge parameter, and the result is some no matter if it's true or false

If follows the same behavior than firestore. Only the fields specified are updated (so you can update only one field). If you give a full record, the behavior remains unchange. See the example below:

```dart
var dbStoreRef = intMapStoreFactory.store('store1');
var dbRecordRef = dbStoreRef.record(1);

await dbRecordRef.put(db, {'value': 1});

// Merging here, `value\ field remains unchanged and a new field `other_value` is added
var result = await dbRecordRef.put(db, {'other_value': 2}, merge: true);
print(result);
// {value: 1, other_value: 2}

// Not merging here, the whole record is replaced
result = await dbRecordRef.put(db, {'other_value': 2});
print(result);
// {other_value: 2}
```

**Comment by xOldeVx** [comment]
Thank you! 🙏

**Comment by alextekartik** [comment]
Documentation updated here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/writes.md#update-data
