### ISSUE TITLE
Auto-increment after deleting all files

### ISSUE THREAD

**Issue by GMC254** [tekartik/sembast.dart#39]
Is there a way of making the integer auto-increment keys to revert back to one (key-1) after deleting all files in a store. (i.e delete method without providing a finder). Thanks.

**Comment by alextekartik** [comment]
Unfortunately no (and other databases, including sqlite have a similar behavior). One solution is to have your own counter in a singleton

**Comment by GMC254** [comment]
Thanks. Will try that. My data is dynamic so I can't work with other databases. Again, thanks for the package.
