### ISSUE TITLE
Reactive Streams NoSQL

### ISSUE THREAD

**Issue by AndryHTC** [tekartik/sembast.dart#40]
I really would like to query the sembast DB and retrieving a stream of data that updates itself once the underlying data change. I can see that there are some reactive wrappers in sqlite, to simulate the firestore realtime... I hope is possible to implement it, as that is the only main missing feature

**Comment by alextekartik** [comment]
It is definitely possible to implement (everything is in memory) even on top of sembast itself. One important step is to define an API that matches everyone's need. Like firestore there could be subscriptions on single document and on queries. The later is the most complex (should the stream send the whole data set again or only the changes - changes/deletion). It could also have an impact on performance (on writes). If you know an existing wrapper (on top on another database) that matches your needs, let me know so I can take a look.

**Comment by AndryHTC** [comment]
Really I'm not concerned about the API you will implement, I think that a transparent API like the one created in firestore will be perfect for most of the devs. I think that (except some advanced cases) people wants the possibility to simply subscribe to a stream of data, just for starting.

If you want to take inspiration for some more advanced APIs, you can have a look to [sqlcool](https://pub.dev/packages/sqlcool) that has 3 different APIs for matching everyone's need. But I still think that these are too exposed for the majority.

I can't wait to have this feature implemented :). Thanks for your time

**Comment by alextekartik** [comment]
I published a new version (dev only so you have to specify the version number >=1.16.0-dev.1) that has support for tracking changes on records and queries. Some information here:
https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md#listen-to-changes

Let me know if it suits your needs.

**Comment by alextekartik** [comment]
Published as 1.16.0
