### ISSUE TITLE
Store uint8 array?

### ISSUE THREAD

**Issue by njovy** [tekartik/sembast.dart#42]
Is it possible to store an array of uint8 (byte array) to this database?
I can just encode a given data to base64 to store in string but it would be nice to have this type as I use protocol buffer.

**Comment by alextekartik** [comment]
Unfortunately no for now as it uses JSON. `Uint8List` is not a supported type. It will be stored and read as `List<int>`. You can also encode it as base64 (like you did) and save it
as a `String`. Big blob could also be stored in a dedicated file.
