### ISSUE TITLE
Initial value during subscription

### ISSUE THREAD

**Issue by bmelnychuk** [tekartik/sembast.dart#43]
When I am subscribed to the data
`_store.query(finder: finder).onSnapshots(_db))` 
is it possible somehow receive surrent snapshot as initial data? I get notified only after changes to the store

Thanks,

**Comment by alextekartik** [comment]
Indeed that should be the behavior. I'm currently testing it and seeing issues on this quite immature feature. Good if you have a unit test that reproduce the issue you are seeing. Thanks!

**Comment by alextekartik** [comment]
This should be implemented/fixed in 1.6.0+3 just published. Let me know.
