### ISSUE TITLE
type 'Utf8Decoder' is not a subtype of type 'StreamTransformer<Uint8List, String>' of 'streamTransformer'

### ISSUE THREAD

**Issue by benjaminhorner** [tekartik/sembast.dart#45]
Hi,

First of all thank you for putting in such an effort.

_Here is the issue:_
I just upgraded to the latest flutter version on 'master' and I am now getting the following error when calling `databaseFactoryIo.openDatabase(databasePath)`:

`type 'Utf8Decoder' is not a subtype of type 'StreamTransformer<Uint8List, String>' of 'streamTransformer'`

All was running smoothly until the update.

**Comment by alextekartik** [comment]
Thanks for the report. Indeed there are some upcoming changes in the SDK regarding switching some types from List<int> to Uint8List. This has not landed on dart dev yet to tackle it in a convenient way, the current workaround being to switch flutter stable/beta/dev but not master.

**Comment by benjaminhorner** [comment]
Switching to dev channel does work indeed. However, this is rather bothersome as we are using master channel on CI/CD.

**Comment by alexelisenko** [comment]
@alextekartik I am using flutter desktop for a project, which requires the master branch. flutter is also developing missing desktop features quickly, so it would be nice to be able to update as needed. Do you have a ballpark estimate on when sembast might have an update to support this change?

Thank you.

**Comment by alextekartik** [comment]
The change will be easy (I've tried it)...when it will be possible. Using current flutter sdk dev (1.8.1-pre.23) even simple code like that:
```dart
File('test').openRead().transform(utf8.decode);
```
does not compile.

The sdk change (https://github.com/dart-lang/sdk/issues/36900) is not finished yet so any coding on this unreleased sdk version will be temporary and would need to be changed. So yes it will be done (I'm tracking it) but for now the safe bet is to revert to a previous master revision.

**Comment by alextekartik** [comment]
Fixed in 1.17.0 published
