### ISSUE TITLE
Preparing for 2.0

### ISSUE THREAD

**Issue by alextekartik** [tekartik/sembast.dart#48]
The plan for sembast v2 is to remove the old API in favor of the new 'sounded' [Store API](https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md).

The following class will be removed:
- Store
- Record
- CompositeFilter
- DatabaseExecutor
- StoreExecutor
- StoreTransaction
- CompositeFilter
- FilterOperation
- FilterPredicate
- ByKeyFilter

This particularly means that the convenient (unsounded) `db.put/delete/get` will not exist anymore in favor of `RecordRef.put/delete/get` allowing to type (or not) the key and the value)

The plan is to make an initial version 1.19.0-dev where the old APIs are deprecated allowing for people to make a smooth transition to 2.0.0 where they will be removed.

As of today (1.17.1), the future deprecated APIs are commented using `// @deprecated v2` so that you can easily find them.

If you have any concern (one will likely be the documentation), please comment here.

**Comment by alextekartik** [comment]
Use dependency
```
sembast: '>=1.19.0-dev.1'
```
to try sembast with the deprecated APIs

**Comment by alextekartik** [comment]
2.0.0 published. Currently deprecated APIs will be removed.

**Comment by barfomellow** [comment]
Do you have any way to query for store names in the new API? I'm thinking about something like the deprecated database.storeNames that was an Iterable<String> . While I didn't use that before, it sounds like what I would need. I have multiple stores and I would like to list their names. But currently I could only do it if I record the name of the stores in a store when I add them and get my list from there. 
Any thoughts?

**Comment by alextekartik** [comment]
Actually you did it right. storeNames was buggy as a store only exists when they are records in it (there is no way to create/delete a store) but there were some cases where a store could be listed even though it did not exist so the behavior was not consistent. The analogy is the collection in firestore (and you cannot list collections in firestore neither). So I would recommend that you keep doing it as you did before (hold the list of stores in a singleton)

**Comment by barfomellow** [comment]
okay, nice. thanks!

**Comment by alextekartik** [comment]
As of 2.3.0, old pre 1.15 APIs (deprecated since 2.0.0) have been removed
