### ISSUE TITLE
storage

### ISSUE THREAD

**Issue by allessandrosj** [tekartik/sembast.dart#53]
What is the storage capacity?

**Comment by alextekartik** [comment]
The main limitation is that is has to fit in memory...Otherwise the limitation is the available disk space but the bigger the slower

**Comment by allessandrosj** [comment]
The smartphone I'm testing has 3 GB
RAM and 128 GB Total Internal Memory (HD), so I can store 64GB of information? And the only problem I would have is a little slow?

**Comment by alextekartik** [comment]
No. The entire DB is loaded into memory (!!!) so 64GB won't fit in 3GB. See info here: https://github.com/tekartik/sembast.dart/blob/3e9b0395c8bf9063261068fa5ee25cb739e4d1e0/sembast/README.md#general
