### ISSUE TITLE
Way to find items by Filter.matches() with ignore case

### ISSUE THREAD

**Issue by carotkut94** [tekartik/sembast.dart#60]
is there a way to filter out the data, one the basis of some match in the name of item, yes there is 
Filter.matches() works for it, but it really does not allow any thing like enable/disabling case sensitive check. or am I missing something?

**Comment by alextekartik** [comment]
I'm not an expert in regular expression matching but I think you can use `Filter.matchesRegExp` to do something like:

```dart
var text = 'cat';
var result = await store.find(db,
  finder: Finder(
  filter: Filter.matchesRegExp(
    'name', RegExp('^$text\$', caseSensitive: false))));
```

If it does not work or if you need advanced filtering, you can use `Filter.custom` to do any filtering you want.

**Comment by carotkut94** [comment]
I tried that, regex already, with caseSensitive set to false, but didn't worked , will try the Filter.custom
