### ISSUE TITLE
Bad UTF-8 encoding 0x0 (at offset 32) error when initialising database using databaseFactoryIo.openDatabase(dbPath)

### ISSUE THREAD

**Issue by akasantony** [tekartik/sembast.dart#62]
When I run `final database = await databaseFactoryIo.openDatabase(dbPath);` to initialise my database I get the following error in iOS. Works fine in Android. 

`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: FormatException: Bad UTF-8 encoding 0x0 (at offset 32)
      _Utf8Decoder.convert (dart:convert/utf.dart:444:15)
      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:309:14)
      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
      _rootRunUnary (dart:async/zone.dart:1132:38)
      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11<…>
`

**Comment by alextekartik** [comment]
hard to say without a full stack trace. Can you confirm (by surrounding openDatabase by a try/catch and getting the full stack trace) that the error is thrown here?

**Comment by akasantony** [comment]
This issue got resolved the I changed the dbPath to assets/ directory. I guess it's a permission issue.
