### ISSUE TITLE
does it possible merge or join store for Finder??

### ISSUE THREAD

**Issue by mccol** [tekartik/sembast.dart#63]
I have 2 stores in aaa.db
ex) StoreRef('dataA') , StoreRef('dataB') 

For sortorders value
when i use Finder I'd like to instance merge(like snapshot) stores to one   
How can i instance merge or join stores for Finder?

I think two ways like this;;
but not working..

ex1) 
var twoStoreMergeForFind = await StoreRef('dataA', dataB').find(db, finder: finder); 

ex2)
 var myDatas = ['dataA', 'datab'];
 var storeMergeTwoData = StoreRef((joinAll(myDatas)));
 var twoStoreMergeForFind = await storeMergeTwoData.find(db, finder: finder);

does it possbile  join or merge mutiple stores for Finder ???

**Comment by alextekartik** [comment]
Unfortunately, like many NoSQL databases (firestore, indexed db, ...), this is not supported. If you need efficient join query you should use a relational database (sqflite). One query can only happen on one store (so one solution can be to duplicate some data).

**Comment by mccol** [comment]
I think Sembast is great!!!!
Thank you very much. I really appreciate it
