### ISSUE TITLE
Error occured while checking cache list for keys!

### ISSUE THREAD

**Issue by afnx** [tekartik/sembast.dart#65]
Hello. First of all, thank you for this great package! I use `records()` method to get numbers of data from a store that I create. However, I see an error like `Error occured while checking cache list for keys!` when I try to fetch a key that doesn't exist in my store. I guess it doesn't support the cases like that. I might use `find()` or `query()` instead, but wouldn't it be more practical if the `records()` method ignores the keys which aren't in store?

**Comment by alextekartik** [comment]
Hi and thanks for the report. Indeed that should not be the case and null value/snapshot should be returned if a record is missing. Although I only added a few unit test on this (<https://github.com/tekartik/sembast.dart/blob/master/sembast/test/records_test.dart>), I could not reproduce the issue. Do you have some sample code, or even better a unit test to reproduce the issue?
