### ISSUE TITLE
Auto increment is not working

### ISSUE THREAD

**Issue by saravananmnm** [tekartik/sembast.dart#68]
`import 'package:flutter_image/model/documenttriptransaction.dart';
import 'package:sembast/sembast.dart';

import 'db.dart';

class FruitDao {
  static const String DOCUMENT_TABLE_NAME = 'documentTripTransactionModel';

  // A Store with int keys and Map<String, dynamic> values.
  // This Store acts like a persistent map, values of which are Fruit objects converted to Map
  final _fruitStore = intMapStoreFactory.store(DOCUMENT_TABLE_NAME);

  // Private getter to shorten the amount of code needed to get the
  // singleton instance of an opened database.
  Future<Database> get _db async => await AppDatabase.instance.database;

  Future insert(DocumentTripTransactionModel fruit) async {
    if (fruit.mPrimaryId == null) {
      var data = await getAll();
      fruit.mPrimaryId = data.length + 1;
    }
    await _fruitStore.add(await _db, fruit.toMap());
    print('table rows inserted');
  }

  Future<int> getCount(DocumentTripTransactionModel model) async {
    final finder = Finder(filter: Filter.byKey(model.mPrimaryId));
    var records = await _fruitStore.find(await _db, finder: finder);
    print('${records.length}');
    return records.length;
  }

  Future update(DocumentTripTransactionModel fruit) async {
    // For filtering by key (ID), RegEx, greater than, and many other criteria,
    // we use a Finder.
    final finder = Finder(filter: Filter.byKey(fruit.mPrimaryId));
    await _fruitStore.update(
      await _db,
      fruit.toMap(),
      finder: finder,
    );
  }

  Future delete(DocumentTripTransactionModel fruit) async {
    final finder = Finder(filter: Filter.byKey(fruit.mPrimaryId));
    await _fruitStore.delete(
      await _db,
      finder: finder,
    );
  }

  Future<List<DocumentTripTransactionModel>> getAllSortedByName() async {
    // Finder object can also sort data.
    final finder = Finder(sortOrders: [
      SortOrder('id'),
    ]);

    final recordSnapshots = await _fruitStore.find(
      await _db,
      finder: finder,
    );

    // Making a List<Fruit> out of List<RecordSnapshot>
    return recordSnapshots.map((snapshot) {
      final fruit = DocumentTripTransactionModel.fromMap(snapshot.value);
      // An ID is a key of a record from the database.
      fruit.mPrimaryId = snapshot.key;
      return fruit;
    }).toList();
  }

  Future<List<DocumentTripTransactionModel>> getAll() async {
    List<DocumentTripTransactionModel> list = [];
    final finder = Finder(sortOrders: [
      SortOrder('mPrimaryId'),
    ]);
    // Making a List<Fruit> out of List<RecordSnapshot>
    final recordSnapshots = await _fruitStore.find(await _db, finder: finder);

    recordSnapshots.map((snapshot) {
      final fruit = DocumentTripTransactionModel.fromMap(snapshot.value);
      // An ID is a key of a record from the database.
      fruit.mPrimaryId = snapshot.key;
      list.add(fruit);
    }).toList();
    return list;
  }

  Future<DocumentTripTransactionModel> getDocuments(
      DocumentTripTransactionModel model) async {
    final finder = Finder(
        filter: Filter.equals('mServerPrimaryId', model.mServerPrimaryId));
    final recordSnapshots =
        await _fruitStore.findFirst(await _db,finder: finder);
    print('${recordSnapshots.value}');
    return DocumentTripTransactionModel.fromMap(recordSnapshots.value);
  }
}
`

**Comment by saravananmnm** [comment]
class DocumentTripTransactionModel implements DocumentContract {
  int mPrimaryId;
  int mServerPrimaryId;
  int mDocumentTypeId;
  String mDocumentType;
  String mDocumentNumber;
  String mFileName;
  String mFileFormat;
  String mServerPath;
  String mLocalPath;
  String mDate;
  int mUserId;
  int mLoggedUserID;
  int mTypeId;
  int mTruckId;
  int mTripId;
  int mMappingPoint;
  int mVerifiedBy;
  int mUploadedThrough;
  int mCreatedBy;
  bool mImageReplace;
  int mModifiedBy;
  bool mActive;
  int mUploadStatus;
  bool mSelected;
  String mCompressedPath;
  String mNotes;
  String mLrMappingId;
  int mLrRefID;
  double mLoadWeight;
  String mUomType;
  String mSource;
  String mOldDocNumber;
}

**Comment by alextekartik** [comment]
Good if you could explain the issue you are seeing. Just sending your (unformatted - please use triple backticks) some source code without much explanation won't help in trying to help you. Even better if you can write a unit test so I can see easily what is wrong.

As a side note, instead of using Filter.byKey, you can use simply store.record(key).

Looking quickly, this:
```dart
fruit.mPrimaryId = data.length + 1;
```
is a wrong assumption. You should get the id from `store.add` instead.

**Comment by saravananmnm** [comment]
Here, my model has int mPrimaryId; field. How pass as auto-increment value for this particular field

`class FruitDao {
static const String DOCUMENT_TABLE_NAME = 'documentTripTransactionModel';

// A Store with int keys and Map<String, dynamic> values.
// This Store acts like a persistent map, values of which are Fruit objects converted to Map
final _fruitStore = intMapStoreFactory.store(DOCUMENT_TABLE_NAME);

// Private getter to shorten the amount of code needed to get the
// singleton instance of an opened database.
Future get _db async => await AppDatabase.instance.database;

Future insert(DocumentTripTransactionModel fruit) async {
if (fruit.mPrimaryId == null) {
var data = await getAll();
fruit.mPrimaryId = data.length + 1;
}
await _fruitStore.add(await _db, fruit.toMap());
print('table rows inserted');
}
}`

**Comment by alextekartik** [comment]
(please use triple backticks around your code). Auto-increment is for the key only, you cannot set a field as auto-increment. I would recommand not to try to maintain a field equals to the key currently (as it it is easy to mess up) but one solution is to add in a transaction then set the resulting key in the primaryId field, something like this (sorry untested):

```dart
Future insert(DocumentTripTransactionModel fruit) async {
  var db = await _db;
  await db.transaction((txn) {
    // Add the object, get the auto incremented id
    var key = await _fruitStore.add(txn, fruit.toMap());
    // Set the Id in our object
    await _fruitStore.update(txn, {'mPrimaryId': key});
  });
}
```

Otherwise simply don't save mPrimaryId in sembast but simply set it in memory equals to the key (after add and read).

**Comment by saravananmnm** [comment]
> (please use triple backticks around your code). Auto-increment is for the key only, you cannot set a field as auto-increment. I would recommand not to try to maintain a field equals to the key currently (as it it is easy to mess up) but one solution is to add in a transaction then set the resulting key in the primaryId field, something like this (sorry untested):
> 
> ```dart
> Future insert(DocumentTripTransactionModel fruit) async {
>   var db = await _db;
>   await db.transaction((txn) {
>     // Add the object, get the auto incremented id
>     var key = await _fruitStore.add(txn, fruit.toMap());
>     // Set the Id in our object
>     await _fruitStore.update(txn, {'mPrimaryId': key});
>   });
> }
> ```
> 
> Otherwise simply don't save mPrimaryId in sembast but simply set it in memory equals to the key (after add and read).

Thanks alex:)
