### ISSUE TITLE
Is it possible to combine finder objects

### ISSUE THREAD

**Issue by mufle-tonmoy** [tekartik/sembast.dart#69]
Hi @alextekartik. Hope you're doing well. Thank you very much for this great package. I have this particular scenario where I want to combine multiple finder objects into one finder to have a combined logical effect. For example, combining the finders and applying would give a result set of applying the sortOrders of each finder object (probably in the order they were combined) within the store. Any pointers would help a lot.

**Comment by alextekartik** [comment]
Currently you can combine filters - [AND](https://pub.dev/documentation/sembast/latest/sembast/Filter/Filter.and.html)/[OR](https://pub.dev/documentation/sembast/latest/sembast/Filter/Filter.or.html) - but not finders.

You have to combine yourself the filters and the sort orders to build a new finder along with boundaries in any - https://pub.dev/documentation/sembast/latest/sembast/Finder/Finder.html - and limit/offset.

Maybe there could be an elegant way to combine finders - dealing with eventual conflicts and some behavior choice: multiple limit/offset specified, order -. Suggestions are welcome if there is a strong need.
