### ISSUE TITLE
How to use custom primary key?

### ISSUE THREAD

**Issue by vifird** [tekartik/sembast.dart#73]
The `int` primary key is meaningless for us, we need a 32-length primary key of `string` type . Because these records may be transfered from server side.

**Comment by alextekartik** [comment]
Yes you can use key of type String:

```dart
var store = stringMapStoreFactory.store('my_store');
await store.record('my_custom_key').put(db, {'my': 'data'});
```

**Comment by ManojMM026** [comment]
can you tell me how to do this for list of objects?
like store.addAll()
is there anything store.putAll(

**Comment by anuragarwalkar** [comment]
But how to add custom primary key

**Comment by alextekartik** [comment]
Currently a primary key is an index or an int. I'm still figuring out how to maintain a custom index to fill this scenario as there are many ways to implement that on top of the existing.

I have an experimental unique index implemented here:
- https://github.com/tekartik/app_common_utils.dart/blob/master/app_sembast/doc/unique_index.md

It might not fit your requirements but it is hard to figure out what everyone's requirement is (multiple field, unique, sort, direct access...). Maybe @anuragarwalkar you can elaborate on your needs to see what could be the solution.
