### ISSUE TITLE
How to change RecordSnapshot to Map?

### ISSUE THREAD

**Issue by vifird** [tekartik/sembast.dart#77]
How to change RecordSnapshot to Map?
Get by `store.find()` is a `Object` of `List<RecordSnapshot<K, Map<K, V>>>`, need to change it to `List<Map<K, V>>`

**Comment by alextekartik** [comment]
you should be able to do something like that:
```dart
snapshots.map((snapshot) => snapshot?.value).toList(growable: false)
```
