### ISSUE TITLE
Is sorting by Key ascending or descending working ?

### ISSUE THREAD

**Issue by fvisticot** [tekartik/sembast.dart#8]
I try to make a search filtered on document property (macAddress) and sorted by key (created by plugin)
I would like to get a returned record with the biggest key (sort order = false).

Setting false or true to the order parameters seems to return the same result.

How to return the last created document (with the biggest key) ?

`Finder finder = new Finder(filter: Filter.equal('macAddress', macAddress), sortOrders: [SortOrder('key', false, true)], limit: 1);`

or

```
finder.filter = new Filter.equal('macAddress', macAddress);
finder.sortOrder = new SortOrder('key', false, true);
finder.limit=1;
```

**Comment by alextekartik** [comment]
Yes that's possible. Sorry for the undocumentation. I added some [here](https://github.com/tekartik/sembast.dart/blob/master/doc/queries.md#sorting-by-key)

In your case you should rather use

```dart
// Sorting by key requires using the special Field.key
var finder = Finder(
  filter: Filter.equal('macAddress', macAddress),
  sortOrders: [SortOrder(Field.key, false)]);
// finding one record automatically set limit to 1
var record = await db.findRecord(finder);
```

I added an example for your case [here](https://github.com/tekartik/sembast.dart/blob/576108a93dade1becbe2fdb29932f1d1c1c1ca87/test/exp_test.dart#L36-L51)
