### ISSUE TITLE
How to turn logging off on Sembast package

### ISSUE THREAD

**Issue by kabnfever** [tekartik/sembast.dart#80]
I know that the "sembast" package is using the "Logging" package @ https://pub.dev/packages/logging for console logging and the amount of logging that sembast does is quite excessive.

Is there anyway to set the "Logging Level" to NONE in the "sembast" package?

Thanks.
Kevin

**Comment by alextekartik** [comment]
Actually, unless set to FINEST, it should not print anything. I almost wonder whether I should get rid of this poorly maintained dependency. Maybe you have an app that set the global level to FINEST. Do you have some logs to share and some sample code that is producing such logs? Thanks!

**Comment by kabnfever** [comment]
Hi Alex, thanks for responding so fast!  Before sending you any logs know that we are actually not using the "Logging" package, we wrote our own logging implementation. So we are not touching the global logging level in the "Logging" package.  That changes things a bit, right?  

With the above in mind is there any way to set the "Logging Level" to NONE via the "sembast" package or should we just implement the "Logging" package in our app and set the global logging level to NONE?

Thanks.
Kevin

**Comment by alextekartik** [comment]
Indeed...Maybe an imported package is using the logging package itself. What you can try, before I definitely get rid of it is to act on the logger itself (sembast does not expose the logger) before any call to sembast (the best is at the beginning of the main)

```dart
void main() {
  hierarchicalLoggingEnabled = true;
  Logger('Sembast').level = Level.OFF;
  ...
  // run your app
}
```

**Comment by kabnfever** [comment]
I cannot provide a full log sample as much of our data is highly-sensitive.  Tried basic implementation of "Logging" package and setting the root.setting the "Logger.root.level" to Level.OFF, but sembast continues to log at the "FINE" level.  Here's a small sample of our console log:

I/flutter (30226): [2019-09-30 13:10:04.127701 | Sembast | FINE] txn 2 get Record(facility, 100000112) {facCommon: ASP-S, facName: ASP-Central Service, instID: 100000000, instCommon: ASP, instName: Fictional State Prison} key 180000112
I/flutter (30226): [2019-09-30 13:10:04.128835 | Sembast | FINE] txn 2 get Record(facility, 100000105) {facCommon: ASP-A, facName: ASP-Facility A, instID: 100000000, instCommon: ASP, instName: Fictional State Prison} key 180000105
I/flutter (30226): [2019-09-30 13:10:04.129051 | Sembast | FINE] txn 2 get Record(facility, 100000106) {facCommon: ASP-B, facName: ASP-Facility B, instID: 100000000, instCommon: ASP, instName: Fictional State Prison} key 180000106
I/flutter (30226): [2019-09-30 13:10:04.129183 | Sembast | FINE] txn 2 get Record(facility, 100000107) {facCommon: ASP-C, facName: ASP-Facility C, instID: 100000000, instCommon: ASP, instName: Fictional State Prison} key 180000107

**Comment by alextekartik** [comment]
Yes I understand. Indeed that's an issue. I just published a version 2.1.0 where the dependency on logging has been removed (and so should the logs)

**Comment by kabnfever** [comment]
I must apologize Alex.  I had only set the root level, not the "sembast" instance as in your example above. Once I set the level on the "sembast" instance using the older v2.0.1 version I was able to control the logging as intended.  However, using the new version you just created v2.1.0 works fine as well.  Thank you very much!!!  Just as a final question: Regarding the new v2.1.0 version, if we run into any issues is there way to turn logging back on in order to report the issue and data to you?

**Comment by alextekartik** [comment]
I have used logging at the beginning of the development and don't use it anymore. It is not exported. One solution is to import an internal `src/log_level.dart` file and do what is done here: https://github.com/tekartik/sembast.dart/blob/320dc8c5f263940ee9617888a68e1bfd8722ebf0/sembast/test/src/log_test.dart#L20-20

However debug logging is incomplete and not very useful. Since it is easy to setup unit test with sembast, it is better to try to reproduce an issue this way so that you don't have to expose your data.

**Comment by kabnfever** [comment]
Cool thanks Alex, much appreciated.  Closing this issue now.
