### ISSUE TITLE
databaseFactoryIo do not support on the web

### ISSUE THREAD

**Issue by taoszu** [tekartik/sembast.dart#84]
Skipping compiling show_code|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

sembast|lib/src/io/file_mode_io.dart
sembast|lib/src/io/file_system_io.dart

**Comment by alextekartik** [comment]
sembast is based on dart:io. unless used in memory (which is useless but for testing), sembast does not support flutter_web. Sorry! 

The main issue wih web support is to allow multiple tab/window accessing the database in a concurrent way. The alternative is to use indexeddb. [idb_shim](https://pub.dev/packages/idb_shim)/[idb_sqflite](https://pub.dev/packages/idb_sqflite) - disclaimer: I'm the author - is a way to have a database on both flutter and flutter_web). [Hive](https://pub.dev/packages/hive) is another alternative; I have not tried it personally and I don't know how if behaves when multiple tabs/windows access the same database.

**Comment by taoszu** [comment]
@alextekartik  thanks.

**Comment by alextekartik** [comment]
An experimental version of [sembast_web](https://pub.dev/packages/sembast_web) has been published
