### ISSUE TITLE
How do I listen to a store instead of just a record?

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#91]
How do I listen to a store instead of just a record?

**Comment by alextekartik** [comment]
You can create a query on a store (without any finder) to listen for the whole store, see <https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/new_api.md#listen-to-changes>

```dart
// Track store changes
var query = store.query();
var subscription = query.onSnapshots(db).listen((snapshots) {
  // snapshots always contains the list of all the records in the store

  // ...
});
```
