### ISSUE TITLE
It takes too long to open the database！

### ISSUE THREAD

**Issue by lixingmao** [tekartik/sembast.dart#95]
I used Sembast on flutter and tested it on the real machine (samsung S8) when I opened a database file about 26M in size (about 10,000 records), it took me nearly 8 seconds.

1. Is this normal?
2. Our database is loaded with memory once when it is opened, right? Does it provide lazy loading or paging loading, such as I just want to load the first 100 pieces of data, or I just want to insert some data without caring about the existing data?

**Comment by alextekartik** [comment]
Unfortunately I would say that it is normal to load 26Mb in 8 seconds. Maybe it could be improved...Unfortunately this behavior is by design. Lazy loading is not possible as is. I would recommend using sqflite instead for better performance.

**Comment by lixingmao** [comment]
多谢回复， 稍后我综合评估一下 对比 sqflite 的性能差异，再做进一步切换考虑吧。
