### ISSUE TITLE
Random updates within consecutive transactions not applied

### ISSUE THREAD

**Issue by Lootwig** [tekartik/sembast.dart#97]
Is there a known problem regarding simultaneous transactions/multiple consecutive transactions? I can try to boil down the affected code into an example, but since this will take a significant amount of time away from working on my actual project, I wanted to check first if this has already been reported. Couldn't find anything in the open issues.

Note: within the transaction, the `update()` method returns the intended record (so, not `null`) with the desired updates applied. They just are not retrieved by `find()` after the transaction is done.

**Comment by alextekartik** [comment]
Thanks for the note. I am not aware of such issue. I'll to some tests on my side (transaction/update, transaction/update, transaction/find)

**Comment by alextekartik** [comment]
Could not reproduce
