### ISSUE TITLE
help in using the store listening

### ISSUE THREAD

**Issue by MichaelSowah** [tekartik/sembast.dart#98]
is there any sample project to see how this feature is used in a project?

var query = store.query(finder: finder);
var subscription = query.onSnapshots(db).listen((snapshots) {
  // snapshots always contains the list of records matching the query

  // ...
});

**Comment by alextekartik** [comment]
I don't have any public example. This is similar to firestore. In flutter, it can be used with StreamBuilder.

**Comment by MichaelSowah** [comment]
How do you use it with StreamBuilder, thats what am looking for in flutter

**Comment by alextekartik** [comment]
onSnapshots() is a stream you can use with StreamBuilder. I started a super basic example here: https://github.com/tekartik/sembast_flutter_more.dart/tree/master/sembast_flutter_example
